### ISSUE TITLE
请问文档的整理情况？

### ISSUE THREAD

**Issue by Dwwwwww** [liulex/Snipaste-Feedback#1]
刚才看到官网的文档依旧在整理中，所以特意来询问一下整理情况，还有有没有什么可以帮上忙的。
【这是第一个issue嘛】

**Comment by liulex** [comment]
目前只有一大堆我在邮箱里回复过的问答，今晚先了解一下 github wiki，明天开始整理吧。
谢谢你的热心。

**Comment by atjason** [comment]
@liulex 如果文档层级比较多，可考虑 https://www.gitbook.com/

**Comment by Dwwwwww** [comment]
@liulex Shift+上下左右缩小截图范围的时候貌似有bug。
截图范围一直缩小的话，可以变成负的...

**Comment by liulex** [comment]
@Dwwwwww v1.4 已修复。
