### ISSUE TITLE
Ctrl + S 功能冲突

### ISSUE THREAD

**Issue by ershiwo** [liulex/Snipaste-Feedback#10]
保存截图和扩大截图区域的快捷键冲突，可以考虑把扩大/缩小区域的功能合并掉改用 shift + w a s d。

**Comment by liulex** [comment]
扩大截图区域是 Ctrl + 方向键，并非是 WASD。
你按 CTRL + D，和单独按 D 是一样的。
**请记住 WASD 始终只是调整光标位置。**
