### ISSUE TITLE
提示“驱动器中没有磁盘”

### ISSUE THREAD

**Issue by ISSACgp** [liulex/Snipaste-Feedback#100]
磁盘D是一个没有插存储卡的读卡器，每次启动都会出现这样的提示。

![sp160828_031427](https://cloud.githubusercontent.com/assets/20962476/18029592/b50a74ee-6cce-11e6-82c3-225333a0e3e3.png)

拔掉读卡器或者点击对话框就好了，但那样真的很不方便。
设置中的默认保存路径都是C盘，桌面。
还没有在其他机器上做过验证。
win10，64位，snipaste版本1.6

另外希望增加用滚轮改变画笔大小的功能（三种粗细不是很够用），
数字键调节画笔透明度（1-0=10%-100%）。
贴图分组功能不是很常用，如果能和win10的多桌面功能同步，感觉会更方便。

感谢开发者！

**Comment by liulex** [comment]
Google 一下 “驱动器中没有磁盘”，即可找到很多解决方案哦，我无法测试，你自己试试吧。
如果不行，请告知我。
Snipaste 是便携版，并没有用到固定的路径，唯一用到的 Snipaste 程序目录之外的路径是系统的启动文件夹。

至于你提的建议，其实都是我有考虑过的，主要是交互和界面上不好设计。
比如用数字键调画笔透明度显然太霸道了一点……

**Comment by ISSACgp** [comment]
试了一下，但是没有进入bios。最后还是把读卡器拔掉解决了

那些建议主要是因为平时懒得打开PS 当然我也同意你的考虑
