### ISSUE TITLE
win7台式无法正常使用Snipaste功能

### ISSUE THREAD

**Issue by xjmwx4** [liulex/Snipaste-Feedback#101]
#### 软件使用情况截图

![使用截图](https://dl2.pushbulletusercontent.com/OgcxXJTESFzvVz20vzJlxGZlRXqrWSKW/2016.08.29-Snipaste.png)
以上为使用时软件显示情况（没有十字交叉情况，该情况为同时使用QQ截图与软件截图冲突时产生），无法正常截图，无法匹配边缘，开启软件截图功能就是这种情况，始终显示（检测图像如文件夹图像边缘大小/截图区域为）1×1区域

台式电脑配置：
![电脑配置](https://dl2.pushbulletusercontent.com/DjqbeiyNhO6hjEM2vsMUPxk7sLEO4Ig2/2016.08.29-Snipaste2.png)

分辨率：
![分辨率](https://dl2.pushbulletusercontent.com/3GaDj32J4RQS0mvXDo1D242C1kEhiqEZ/2016.08.29-Snipaste3.png)

其他反馈：家里笔记本Snipaste使用正常，公司台式电脑第一次启动软件时提示“丢失 api-ms-win-crt-runtime-l1-1-0.dll ”，后通过“微软 Visual C++ 2015 可再发行组件包”解决。启动成功后就是如上这种使用情况。电脑分辨率调到1280级别Snipaste也无法正常使用，情况没有改变。

### 运行环境

操作系统：Windows 7 64位
Snipaste 版本：  v1.6 (2016.08.10)版本（官网http://zh.snipaste.com/下载） 

### 改动过的默认设置

仅改动过快捷键，与问题情况无关

**Comment by liulex** [comment]
你好，看你的截图，应该是进入截图后 Alt 键被按下了？
你说的无法正常截图，是仅仅指无法自动选取区域，还是说也无法用鼠标拖选截图区域，或者是整个截图界面都失去响应？

**Comment by xjmwx4** [comment]
你好：
很抱歉描述不清，是前者，无法自动选取区域，含边缘匹配、用WASD键进行像素级边缘调整。鼠标拖选截图区域能够拖选出来，可以正常保存和批注等。



--

Name：徐 佳
Mobile Phone：18817393515
Address：上海·杨浦

人生，唯真性情尔。
既然选择了远方，便只顾风雨兼程。路是自己义无反顾走出来的！

在 2016年8月30日 上午10:15，liulex <notifications@github.com>写道：

**Comment by liulex** [comment]
如果只是选取区域问题，那么应该和 #61 是同样的问题。
可以加入我们的[内测群](https://telegram.me/joinchat/BGyWwEEW8CEjnhGb5sUDEw)，看看内测版是否解决了你的问题。

**Comment by xjmwx4** [comment]
好的，麻烦了，稍后加入看看。谢谢~~

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=7.12.61&pv=9.2&source=email_footer_2]
On Tue, Aug 30, 2016 at 10:39, liulex <notifications@github.com> wrote:
如果只是选取区域问题，那么应该和 #61 [https://github.com/liulex/Snipaste-Feedback/issues/61] 是同样的问题。
可以加入我们的 内测群 [https://telegram.me/joinchat/BGyWwEEW8CEjnhGb5sUDEw] ，看看内测版是否解决了你的问题。

**Comment by yankaiqian** [comment]
我是32位的win7，试了v1.6，也没有自动检测界面元素的功能，不知道需要提供哪些信息以便进一步排查。

**Comment by liulex** [comment]
@yankaiqian 谢谢，不用进一步的信息了，相关的几个用户都是同一种情况，和系统版本无关，问题已经解决。
