### ISSUE TITLE
软件有时会在临时目录中生成一个很大的iso文件

### ISSUE THREAD

**Issue by jr21066** [liulex/Snipaste-Feedback#102]
Win10 64位
当时在操作2345看图王.发现系统变慢.观察是硬盘的原因.检查后发现使用热键帖图时软件会在临时目录生成一个很大的iso文件.
对文件大小进行全盘搜索后.发现是硬盘上另一个iso文件.不知为何会被写到临时目录.
遗憾的是没找到再现方法.当时使用画图软件粘贴时,是没有内容的.

![sp160830_172128](https://cloud.githubusercontent.com/assets/21333425/18083931/e7113eea-6ed7-11e6-8151-9eeeef862656.png)

**Comment by liulex** [comment]
非常感谢你的反馈，这确实是一个严重 bug.

因为有些图像文件的文件名后缀是错误的，比如 jpg 图像被赋予了非图像格式的后缀名，或者根本没有后缀名，为了兼容这种情况，Snipaste 没有对文件的后缀名进行过滤。

另外，为了防止用户把文件贴出来之后，源文件被用户删除了，所以如果有打开贴图的“自动备份”，Snipaste 会在把文件贴出来之前就把源文件复制一份放到 history 目录下。如果发现该文件并不能转换成图像，再把文件的副本删除。

以上这两个处理，就导致了用户试图把文件贴出来的时候，这份文件都会先被复制到 history 目录下。

所以要重现你的问题很简单，Ctrl + C 复制一个大文件，然后按贴图快捷键，就会发现 Snipaste 正在把它放到 history 目录下（如果不是图像文件，Snipaste 稍后会自动删除副本）。

这其中确实有考虑不周到的地方，下一版本会这样处理：

检查文件名后缀是否为支持的图像格式：
* 如果是，则不管文件大小，都尝试把它贴出来
* 如果不是，则检查文件大小，小于 10 MB 的才会试图把它贴出

**Comment by jr21066** [comment]
是这个情况.按方法是可以重现.
期待新作.

另外我设置"`"键做为截屏热键了.在Win10系统里感觉很多软件都对这个键处理了.不能激活截图.
象浏览器这样的软件就不能激活,也没有热键冲突.我需要点一下桌面再按热键才可以截图.

**Comment by liulex** [comment]
@jr21066 应该跟快捷键是 "`" 无关，见 #84

**Comment by jr21066** [comment]
搞定了.程序兼容性里把管理员身份运行选中就好了.谢谢.

**Comment by liulex** [comment]
ok，那这个 issue 关闭了。
