### ISSUE TITLE
Windows Defender 报告 Qt5Core.dll 中存在 Trojan:Win32/Varpes.M!cl

### ISSUE THREAD

**Issue by Spirituaway** [liulex/Snipaste-Feedback#103]
### 问题描述

解压软件 64 位完整版压缩包后，Windows Defender 立即报告 Qt5Core.dll 中存在 Trojan:Win32/Varpes.M!cl：

<img width="592" alt="default" src="https://cloud.githubusercontent.com/assets/8605621/18094549/7ab42166-6f06-11e6-92b6-088486e4f9d3.PNG">

### 运行环境

操作系统：Windows 10 64位
Snipaste 版本： 1.6

**Comment by liulex** [comment]
同 #66

**Comment by woxinbuji** [comment]
The same problem!

**Comment by liulex** [comment]
报 dll 就算了，微软把 32位的 exe 也给报了……（更新病毒库定义之后不报了）
详情见[这个帖子](https://www.v2ex.com/t/300585#reply10)最后。

**Comment by woxinbuji** [comment]
Thank you!支持！

**Comment by Spirituaway** [comment]
抱歉，看漏了 @@
感谢说明！

**Comment by Spirituaway** [comment]
今天更新病毒库后64位版本已不再报毒 :)

**Comment by akaylh** [comment]
昨天能用，今天就不能用了。连exe都没了

**Comment by hcl** [comment]
更新病毒库之后Qt5Core.dll依然被Windows Defender杀掉。

**Comment by StarryVoid** [comment]
从来没报过毒，windows10 10240 10586 的WD，病毒库一直最新。
报毒的建议先验证sha1，作者可以保证下载源的是无毒的。
