### ISSUE TITLE
希望截图后贴图功能改改更快捷

### ISSUE THREAD

**Issue by Cader** [liulex/Snipaste-Feedback#104]
这个软件我们用得最多的是截图，然后马上贴图。
现在这个过程比较麻烦，F1截完还要去点图标（图标有点小），或者CTRL+W，来回按快捷键挺麻烦的
能否简化一下，我按完F1截完，再次按下F1（或鼠标中键或者其他单键）就贴图，
或者您能不能干脆把内置按键开放成可以设置的，我们自己来定义

**Comment by jr21066** [comment]
我设置的是·键截图。ALT+·贴图

**Comment by Cader** [comment]
@jr21066  我的意思是截图框选完，一键贴图，不需要点图标（图标有点小），或者按CTRL+W这种组合快捷键

**Comment by Cader** [comment]
#

**Comment by liulex** [comment]
@Cader #63 这里有提出和你一样的需求。
这个 feature 在下一版会作为一个选项加入。
