### ISSUE TITLE
希望贴图的鼠标缩放功能不要以左上角为圆心，而是以鼠标位置为圆心，键盘缩放时以中心为圆心

### ISSUE THREAD

**Issue by moonhuahua** [liulex/Snipaste-Feedback#105]

**Comment by liulex** [comment]
中建点击还原缩放的时候，你会发现这时候的缩放是以鼠标为中心的。

所以并不是我没有实现这个功能，只是**连续缩放**的时候，如果以鼠标为中心，窗口会跳动，这是 Windows 系统的缺陷，因为这时候不仅窗口尺寸变了，窗口位置也变了。

简答测试：随便找一个其他程序的窗口，然后拖动它的左边框进行缩放，你会发现窗口中总有些元素在跳动，即使是自带的文件管理器也不例外。

不过我也想到了解决办法，只是需要的代码量比较大，也不确定是否可行，所以短期内不会去尝试。

另，发 issue 请用点心，把模版发出来是什么意思？以后此类 issue 会直接关闭。

**Comment by moonhuahua** [comment]
不好意思，已经m删除模板了，没注意这个

同意你的看法，这个连谷歌的Picasa都没办法解决(当然个人感觉能以贴图中心为圆心来缩放更合理一点)

**Comment by s18695607903** [comment]
贴图缩放的时候不要锁定比例，即垂直和水平的固定比例。

**Comment by s18695607903** [comment]
![image](https://cloud.githubusercontent.com/assets/22074045/18345999/a5ad19cc-75f0-11e6-93cc-3a02ac8a429b.png)
这款软件就是可以手动垂直或者水平的尺寸大小，

**Comment by liulex** [comment]
@s18695607903 可以加入不锁定比例的选项，请提个新的 issue.
