### ISSUE TITLE
希望在截图和贴图的修改界面增加快捷键：w是直线，d是矩形，c是圆形，t是文字，a是箭头,e是橡皮擦，b是画笔，m是马赛克，j是记号笔

### ISSUE THREAD

**Issue by moonhuahua** [liulex/Snipaste-Feedback#106]
![image](https://cloud.githubusercontent.com/assets/15684037/18190081/632c05ca-70f2-11e6-8422-4385de9e37ae.png)

**Comment by liulex** [comment]
可以用 Ctrl + Tab 切换标注形状。
但我不觉得有必要为每一个形状分配一个快捷键，标注本来就是鼠标操作，增加快捷键只会得不偿失。
更何况， w 和 d 是控制光标移动的。

**Comment by moonhuahua** [comment]
好的，这个基本没什么影响，我自己也可以加快捷键上去，现在没太大这个快捷键的需求，有的话我自己加吧(矩形的d可以改为q，直线的w可以改为e)

**Comment by caimizhou** [comment]
1 标注形式中，我最常用的可能就是文字，其次是画笔。对我来说，如果能有快捷键的话，能大大加快标注的效率。或者不设置快捷键，而是空格后就默认进入到第一个标注，比如现在的矩形窗口，而不用再进行手工选择或者切换才能进行标注。       
2 Ctrl+Z是撤销的快捷键，能不能也有恢复的快捷键，比如Ctrl+Y或者Ctrl+Shift+Z什么的？
谢谢~~~

**Comment by moonhuahua** [comment]
@caimizhou 我也觉得用左手的快捷键是可以提高效率的，反正按键还多，我用ahk是可以达到这个目的，不过肯定不如软件集成的好啊
@liulex 我用ahk是可以很快就加这些快捷键而且不影响文字输入和其它功能的，不知加入软件是否很复杂，很复杂就算了

**Comment by liulex** [comment]
@caimizhou 
以后会加入快速进入编辑模式的快捷键。
Ctrl+Y 和 Ctrl+Shift+Z 一开始就已经加入。
@moonhuahua 
一个功能是否加入，不只是考虑它的实现复不复杂。

**Comment by zhangfuwen** [comment]
这个块捷键众口难调，能不能改成自定义的？我觉得用左手字母更方便些，因为右手在手鼠标。用Ctrl的话一只手按不了。

**Comment by moonhuahua** [comment]
@dnknn 我是自己写的脚本实现的快捷键功能，Snipaste本身没有。主要我也经常用，我常用软件很多，全部自己写脚本加速了的！

**Comment by xianghongai** [comment]
截图比较大，有快捷键方便很多，避免较长路径去选择工具。
