### ISSUE TITLE
win7 64位 1.6版本临时修复版Snipaste出现任何地方都无法自动检测窗口的新问题 麻烦解决一下奥！

### ISSUE THREAD

**Issue by anysafepan** [liulex/Snipaste-Feedback#108]
先点 Preview ☝
 
如果希望提交 BUG，请先：
* 确认在 Snipaste [最新版](http://zh.snipaste.com/download.html) 该 BUG 依然存在
* 浏览一遍 [故障排除](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4)，看是否已经有解决方案
* 浏览一遍 [新版预告](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%96%B0%E7%89%88%E9%A2%84%E5%91%8A)，看是否已经被解决
* 用关键词搜索已有的 issues，看是否已经有人提过

如果希望提交新功能请求，请先：
* 浏览一遍 [新版预告](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%96%B0%E7%89%88%E9%A2%84%E5%91%8A)，看是否已经被加入
* 浏览一遍 [基础操作](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C)，看是否已经 Snipaste 本身已经包含
* 用关键词搜索已有的 issues，看是否已经有人提过

**BUG 和新功能请求不要在同一个 issue 里描述，请分开发 issue**

**（以下是开发者建议的描述模版，请根据你的情况自行增删）**

### 问题描述/建议描述

（如果是跟界面相关的，请提供截图）
（如果希望增加某一功能，请描述你的使用场景，这很重要，有利于你得到其他用户的赞同，开发者也会据此判断该功能是否值得增加）

### 重现步骤

1. 说明该 BUG 是否 100% 可重现。如有条件，在另一台机器上试验一下。如果只是偶尔会遇到的 BUG，请尽可能想想 BUG 发生时的共性。
2. 客观地描述你的每一步操作及相应的界面变化。“截图后无法保存图片”是很好的标题，但正文应该更详细地描述，如“按截图快捷键开始截图，单击鼠标左键确定截图区域，点击保存按钮，文件保存窗口弹出，点击保存，但文件并没有保存到指选定的目录下“。
3. 贴图和截图有些行为是不同的，比如你希望提交的问题是如上所述的截图无法保存，那么在贴图窗口是否能正常保存图片？也可说明一下。

### 运行环境

操作系统：Windows X xx位
Snipaste 版本： x.x 
（如果跟多屏相关，请提供屏幕设置，如屏幕的相对位置，主屏、次屏的分辨率和 DPI）

### 改动过的默认设置

（仅列出与问题相关的设置项即可，或者提供选项窗口的截图）

- 取消勾选"xxxx"
- xxx数 设置为 x

**Comment by liulex** [comment]
同 #61 
如果你是指内测版也没有修复，请到内测群反馈。
