### ISSUE TITLE
(帮人代问）截图时“保持到文件” 和“复制到剪贴板”这两个按钮的位置能不能互换

### ISSUE THREAD

**Issue by sishentibu** [liulex/Snipaste-Feedback#109]
虽然我个人觉得位置没关系。但有人问了，我就暂且帮忙问下。

就是截图时，最右边的那个按钮，他想改成“保存”按钮。
如果目前的排布是L大比较顺手的排布的话，那只能是考虑按钮排布自定义，或内置几种排布方式了。不知是否有可行性？

**Comment by jr21066** [comment]
只是觉得按钮小.不用热键比较困难

**Comment by sishentibu** [comment]
我自己是慢动作操作，影响不是很大。。@jr21066

**Comment by liulex** [comment]
这只是习惯问题，多用几天，这个需求应该也就不存在了。
复制到剪贴板在最右，这不是因为我个人比较顺手，而是它是大多数用户最常使用的。
需要更快的操作，请使用 Ctrl + C (或者 Enter) 和 Ctrl + S……

**Comment by sishentibu** [comment]
@liulex 好的，谢谢回复
