### ISSUE TITLE
怎么取消某些热键呢

### ISSUE THREAD

**Issue by Tek-Eternal** [liulex/Snipaste-Feedback#11]
我想只用截图的热键，贴图等功能不用，在软件里貌似不能设置（按del也会把del当热键）。
最后只能在config.ini 里编辑配置文件清空热键。

**Comment by liulex** [comment]
按 Ctrl 或者 Backspace.
请查看：
https://snipaste.gitbooks.io/snipaste/content/zh/problems/windows.html
