### ISSUE TITLE
增加图片保存时的默认格式设置？

### ISSUE THREAD

**Issue by sishentibu** [liulex/Snipaste-Feedback#111]
今天经人提醒，保存 png 时，比保存 jpg 时要大很多。测试了几张颜色比较多的图片，也确实如此。
部分有上传图片需求的，估计会比较在意大小问题。
因此想问下，是否可以增加一个设置，设置默认的保存格式为 png/jpg/bmp ？或是图片格式改为与上次保存的图片的格式相同。

顺便请教下，使用 png 是因为保存效果比较好？

**Comment by liulex** [comment]
使用 png 是因为有透明通道，目前截图和贴图都是可以弄出透明区域的，所以默认 png 是有必要的。
png 相对 jpg 有很多优点，详情请自行搜索。
目前 png 图片比较大，是因为没有做压缩，使用了 Qt 默认的保存质量，以后会考虑给用户自己选择图片质量。
但很多图床其实会自动帮你压缩图片……

不过，下个版本开始会记忆用户上次保存时的图片格式。

**Comment by sishentibu** [comment]
感谢解答。
