### ISSUE TITLE
图片位置与隐藏

### ISSUE THREAD

**Issue by caimizhou** [liulex/Snipaste-Feedback#112]
图片位置无法拖到最上方
![default](https://cloud.githubusercontent.com/assets/21986568/18259584/26a5b30c-7418-11e6-961b-d7a97bbe58a6.png)
1 希望可以让图片可以拖到最上方
2 希望可以有一个功能，能让超出边界的图片还原到中心
3 己有了功能，让所有图片无法点击。可否多出一项，让指定图片无法点击？
4 在一个分组内，当截图数量过多的时候，我只想看下图中所示1图，而暂时隐藏其它图片。并且可以反向操作。（来源于stickies中一项功能，叫solo，按下solo时，只显示指定图片，再按下显示所有图片。）
![default](https://cloud.githubusercontent.com/assets/21986568/18259651/f758078e-7418-11e6-8c5b-f5840aa5a7cf.png)

**Comment by liulex** [comment]
你好，
1. 图片是可以拖到超过最上方的，如果你操作没问题，那么你可能遇到了一个 bug，你可以给我邮箱 <snipaste.app@gmail.com> 发送一下 IM 联系方式（如 QQ 或 Telegram），方便我确定你的问题。
2. 如果对图片进行某种操作，使得它在屏幕上不可见了（存在这种操作），那么 Snipaste 会自动将它重新放回屏幕内。如果图片只是部分超出屏幕，那么是没有必要对它的位置进行干预的。
3. 如果让单张图片无法点击，那么你该怎么操作，让它重新可以再被点击呢？所以不只是加多一项命令的问题，还有很多相关的要考虑。
4. 这个功能很不错，以后会考虑加入！

**Comment by StarryVoid** [comment]
1、可能发生BUG，可以联系楼上作者
2、可以复制一下图像，然后删掉贴图，再重新贴进来。
3、指定的图片无法点击，@liulex 个人认为可以设计在贴图右键菜单增加锁定功能，但是如果很麻烦的话还是投票决定吧
4、给你想法赞一个，不过貌似得以后才能见到了。
