### ISSUE TITLE
foxit pdf reader里面，按F1无法启动snipaster截图（8-10 1.6版本）

### ISSUE THREAD

**Issue by bilijinshi** [liulex/Snipaste-Feedback#113]
foxit pdf reader里面，按F1无法启动snipaster截图（8-10 1.6版本）

**Comment by jr21066** [comment]
以管理员身份运行看看

**Comment by liulex** [comment]
因为你的 foxit reader 是以管理员权限打开的，所以要么同样以管理员权限打开 Snipaste，要么取消以管理员权限打开 foxit reader.
解释见 #84
