### ISSUE TITLE
[BUG] 在windows资源管理器中打开右键菜单的情况下，ESC无法中止截图

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#114]
![image](https://cloud.githubusercontent.com/assets/2637718/18372892/56cfbe90-7672-11e6-9e09-bd22b6e10825.png)

如上图所示，**先在桌面，或者某个盘下面，点右键打开右键菜单**，    ----关键步骤
按快捷键开始截屏，Snipaste开始随鼠标移动自动识别窗口及窗口内元素，
此时按ESC，无法中止截图，只能通过鼠标右键点击来中止。
但如果在没有打开右键菜单的情况下，ESC是可以中止截图的。

操作系统：Win10 64位专业版
Snipaste版本：1.8-Alpha(2016.09.01)

**Comment by liulex** [comment]
已确认，感谢反馈。

**Comment by liulex** [comment]
已修复。

**Comment by toryln** [comment]
bug修复效率真高！
