### ISSUE TITLE
可以增加GIF动图的涂鸦？

### ISSUE THREAD

**Issue by thomasmolover** [liulex/Snipaste-Feedback#115]
彻底替换掉那狗带的扣扣截图。

**Comment by StarryVoid** [comment]
让我理解一下你的问题（假设GIF有100帧）
1、你是准备所有100帧都添加一些方框线条对么？
2、Snipaste只有贴图可以读取GIF图片文件，并且不是100%支持，在贴图里增加？
3、Snipaste软件本身功能是贴图，截图为核心，你想问的个人感觉属于图片编辑，不太符合。

**Comment by liulex** [comment]
@StarryVoid 感谢回复！
楼上说的差不多就是我的意思，你提的需求不符合 Snipaste 的定位，所以不会考虑。
