### ISSUE TITLE
选取 DrRacket 窗口中的内容时 Snipaste 无响应

### ISSUE THREAD

**Issue by Jack-Works** [liulex/Snipaste-Feedback#116]
### 重现步骤
1. 当 DrRacket 在前台显示时激活 Snipaste 截图

2. Snipaste 无响应

### 运行环境
操作系统：Windows 10 64位（1607）

Snipaste 版本： 1.6（2016.08.10）

DrRacket 版本：6.6

**Comment by liulex** [comment]
问题确认，感谢反馈！

**Comment by liulex** [comment]
我仔细调试了下，这是因为这个程序对 accHitTest() 这个接口的实现有问题，迟迟不返回结果，所以导致程序卡住。

没有很好的处理办法，只能把这个 exe 加入黑名单了，只检测它的窗口，不自动检测界面元素……

**Comment by Jack-Works** [comment]
能不能检测一下， 为 accHitTest() 设置一个等待超时的时间，如果超过了，就不检测界面元素？

**Comment by liulex** [comment]
它是类似死循环那种，一直不返回的，也没有其他方法能标识这种窗口。
如果是把检测函数放在另一个线程，超时强制结束，代价就太大了。

不过对于黑名单中的窗口，我刚刚用了另一个方法来检测其元素了，大部分界面元素也是可以检测出来的。

**Comment by liulex** [comment]
@Jack-Works 
1.10.2 已开放名单机制，不再在程序里内置列表。
你将需要手动将 drracket.exe 加进名单里，如：

```
[snip]
crashes=drracket.exe 
```

具体请参考 [高级设置](https://github.com/liulex/Snipaste-Feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE)。
