### ISSUE TITLE
无法完成截图

### ISSUE THREAD

**Issue by AndyFoolish** [liulex/Snipaste-Feedback#117]
官网完整包 (Windows)64位v1.6版本，
win7 64系统，
snipaste默认配置未改动，
F1截图，按住鼠标左键拖动选择截图区域，松开鼠标，工具栏闪一下消失，截图失败，
而让snipaste自动选取截图区域，工具栏存在，正常截图。
后在同一台电脑测试32位版本的snipaste，同样出现上述问题。
以上为双屏。
后单屏尝试，同样截图失败。

**Comment by liulex** [comment]
#76 
下个版本修复。
