### ISSUE TITLE
[BUG] win10 使用32位 Sinpaste "贴到屏幕" 异常退出

### ISSUE THREAD

**Issue by Liuzhj** [liulex/Snipaste-Feedback#119]
---
### 重现步骤

* 客观地描述你的每一步操作及相应的界面变化。例如，“截图后无法保存图片”是很好的标题，但正文应该更详细地描述每一步，如：
  1. 按截图快捷键开始截图
  2. 选择“矩形框”
  3. 鼠标左键和右键同时点击某一可选择内容，**一定要选择两次或以上（选择一次有时无法复现）**
  4. 选择点击 “贴到屏幕（Ctrl + W ）”
  5. 程序异常退出

*  此BUG 100%可以重现

### 运行环境

操作系统：Windows 10 64位
Snipaste 版本： 1.6 32 位

**Comment by liulex** [comment]
已修复。
新版将于近日更新，感谢反馈！
