### ISSUE TITLE
希望可以在截图处可以调字体大小

### ISSUE THREAD

**Issue by hai-season** [liulex/Snipaste-Feedback#12]
这个截图工具似乎只能在首选项那里调字体大小，可有时候我同时需要不同大小的字体，像qq那样的截图工具那样
![sp160802_101911](https://cloud.githubusercontent.com/assets/20784720/17314988/d8ad80c8-589a-11e6-9a7f-c301b303cd57.png)

**Comment by liulex** [comment]
请先查看帮助：
https://snipaste.gitbooks.io/snipaste/content/zh/basics/edit.html

Snipaste 除了限制了最小字体大小，可以让你更任意地调整字体大小。
