### ISSUE TITLE
附加功能：置顶任意窗口

### ISSUE THREAD

**Issue by langren1353** [liulex/Snipaste-Feedback#120]
能不能顺便在程序中加一个功能，F[x]置顶当前窗口，这样的话就不用再去下载一个其他软件了，特别是在处理notepad文档的时候

**Comment by moonhuahua** [comment]
其实贴图本身就置顶了的，（偶而用不置顶的情况可能是bug），我觉得你这个建议好，因为有好几个贴图的时候，有个快捷键（比如t），切换激活的贴图是否置顶，想来是很好的功能（默认还是置顶的好）

**Comment by langren1353** [comment]
O_O
我不是说的那个意思，我的意思并不是针对某个贴图，是针对所有程序，能不能再程序中集成一个快捷键，这个快捷键处理当前窗口的置顶情况-不需要指示器
虽然这个功能和本软件没多大关系，但是还是可能在使用中遇见这个问题，总想解决，却又解决不了

**Comment by moonhuahua** [comment]
!v::WinSet, AlwaysOnTop,Toggle,A			;切换激活窗口置顶与否
其中!v的意思是按住alt再按v，这个就可以达到你要的结果，但这样不如集成到Snipaste里面对某个激活的贴图用一个字母来控制，想来是很简单的

**Comment by liulex** [comment]
Snipaste 三个功能：贴图、截图、标注。
你提的需求和这三个都无关，所以是不会考虑的。

“这样的话就不用再去下载一个其他软件了”，Snipaste 并不是操作系统，不会去替你节省安装的软件数量……

我倒希望软件的功能越细分越好，比如把 Snipaste 的三个功能分为三个软件。没有分，是因为贴图功能需要另两个功能的紧密配合。

**Comment by yinhux** [comment]
@langren1353 
任意窗口置顶工具 v2.2 绿色免费版  这个小软件可以实现任意窗口置顶
