### ISSUE TITLE
希望可以改进下全屏状态下的界面元素判定

### ISSUE THREAD

**Issue by sdcclqs** [liulex/Snipaste-Feedback#121]
在视频播放状态下，全屏截图会默认消去侧边栏的范围，但对于前台的全屏程序来看这回导致截图效率的降低，只能手动重新选择范围，如下图。
![image](https://cloud.githubusercontent.com/assets/22212962/18543662/7fa651bc-7b63-11e6-8a58-1b82c84cda85.png)
无论网页版视频播放还是本地播放器的全屏播放都会这样，能否在界面元素判定这一功能上对全屏状态加以优化，谢谢了。

**Comment by sdcclqs** [comment]
所以能不能是提取当前窗口的元素而不是全屏后面的元素啊

**Comment by liulex** [comment]
@sdcclqs 因为有些窗口全屏是不覆盖任务栏的，之前为了照顾到这种情况，所以一刀切了。后来改进了检测的策略，但忘了之前那个临时的策略给移除掉，所以导致了你的情况。
下一个小更新即会解决此问题，感谢反馈。

**Comment by StarryVoid** [comment]
搞得我都不敢回答了。。

**Comment by sdcclqs** [comment]
好像。。。。这个问题更新之后仍然没有解决唉

**Comment by StarryVoid** [comment]
@sdcclqs 🌚🌚🌚

**Comment by septs** [comment]
@sdcclqs 关于下次更新发布
请关注 https://github.com/liulex/Snipaste-Feedback/milestone/2 的更新进度
以上

**Comment by liulex** [comment]
@sdcclqs 嗯……之前解决的是全屏窗口没有包含任务栏区域的问题，而现在看来你的问题是全屏窗口时检测到的元素是窗口背后的元素，这是另一个为了鼠标放在桌面空白处时不返回全屏做的 hack，在单屏情况下就误伤了其他非桌面的全屏窗口……

目前已经修复，请期待下次更新。
