### ISSUE TITLE
今日刚发布的1.7版本，我发现有个用的不太舒服的地方，就是刚进入截图就自动确定了截图区域

### ISSUE THREAD

**Issue by ZetaoYang** [liulex/Snipaste-Feedback#123]
当用鼠标点击Snipaste在任务栏上的图标截图时，程序会直接自动选择Snipaste任务栏区域的小矩形Logo。
另外，中秋快乐

**Comment by liulex** [comment]
不是一直都是这个行为吗？

**Comment by StarryVoid** [comment]
首先这个行为分两步
1、点击Logo，进入截图模式
2、你点击logo时的状态下，鼠标在小矩形logo上
3、自动检测窗口选择为小矩形logo

**Comment by ZetaoYang** [comment]
![](https://qanno.github.io/downloads/ScreenGif.gif)  
这是我录的gif动画，它不会像1.6版本那样出现十字让我重新选择截图区域。

**Comment by taroxd** [comment]
终于有人可以复现了吗

**Comment by liulex** [comment]
@ZetaoYang 这属于刚进入截图就自动确定了截图区域，然而我这边复现不了……

**Comment by ZetaoYang** [comment]
@liulex 但是1.6版本没有出现这个现象。

**Comment by liulex** [comment]
@ZetaoYang 你试试运行给其他系统准备的 Snipaste，32 位和 xp 的

**Comment by ZetaoYang** [comment]
@liulex 我用的是64bits,其他版本我试试

**Comment by ZetaoYang** [comment]
@liulex 32bits正常，xp正常

**Comment by liulex** [comment]
@ZetaoYang 这大概就说明不是我代码的问题……可能编译上出了什么错……
那你现在再重新打开 64 位的，还是 100% 出问题？

**Comment by taroxd** [comment]
@liulex Comment only for testing purpose.

**Comment by ZetaoYang** [comment]
@liulex 64bits还是有问题，虽然不是100%，但是复现的概率也很高

**Comment by ZetaoYang** [comment]
@liulex 32bits也有一定的概率出现这个问题，特此更正。

**Comment by ZetaoYang** [comment]
@liulex 这应该是程序上的问题

**Comment by ZetaoYang** [comment]
@liulex 经过长时间的测试，xp也会出现这样的问题。程序刚安装上时，不会出现这样的现象，但是用了一段时间后就出现了问题。

**Comment by liulex** [comment]
@ZetaoYang 了解，但是总有一个能 100% 复现的条件的……

**Comment by StarryVoid** [comment]
@liulex 搞不出来这个BUG，，我只碰见过1*1自动选区那个BUG
还是静观吧。希望最终能解决

**Comment by pm2kjiagm** [comment]
我这里目前也有发现这个情况，之前一个版本是没事的。

**Comment by StarryVoid** [comment]
作者已经成功复现出BUG。双击截图后，下次操作时自动选择区域。
by liulex

**Comment by ZetaoYang** [comment]
@小伙伴们 
作者已经在1.7.2版本中修复了这个问题。

**Comment by liulex** [comment]
感谢 @ZetaoYang 的协助，问题已经修复。

**Comment by pm2kjiagm** [comment]
此问题在最近一次更新之后再度出现了，还请作者排查一下，感谢。

**Comment by pm2kjiagm** [comment]
@liulex 目前我这里使用1.10.1是可以复现的，和之前那次是一样的症状。

**Comment by pm2kjiagm** [comment]
由于截图无法反映，录制了一段视频到Youtube：https://www.youtube.com/watch?v=KbQXwr4I5ZA
如图所示，当对左边的文件夹使用双击截图的时候，第二次使用快捷键就会发生这一症状。
奇怪的是，当双击截图本程序的主界面时，则不会发生这一症状。
以上请供参考。

**Comment by liulex** [comment]
@pm2kjiagm 感谢你这么用心 :+1: 
我多次重试之后也终于重现了，虽然不是 100% 重现，不过也找到原因并修复了，确实和上次的原因有点类似。
大概明天会发布新版。

**Comment by pm2kjiagm** [comment]
@liulex 好的，感谢。
