### ISSUE TITLE
希望能加入对Chrome的支持，谢谢

### ISSUE THREAD

**Issue by moonhuahua** [liulex/Snipaste-Feedback#124]
Chrome好像不是标准的Windows窗口吗，能否支持选取元素？谢谢
顺祝：中秋快乐！

**Comment by StarryVoid** [comment]
本人非作者
1、Chrome内部属于html元素，你需要插件支持。
2、Chrome的整个浏览器窗口可以识别啊，如果你没能识别，那么可以提交一下操作流程作为BUG反馈到作者。

**Comment by liulex** [comment]
[故障排除](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4) 里有说。
issue 模版不是白写的，里面第一条就有让读 故障排除 页面。

**Comment by funsgang** [comment]
> Chrome的好像不是标准的的Windows窗口吗，能否支持选取元素谢谢？
> 顺祝：中秋快乐！


	* 对于 Chrome 浏览器，请在地址栏中输入并打开 chrome://accessibility，勾选 Native accessibility API support 以及 Web accessibility
	* 
Chrome 每次关闭之后都会重置这些设置，如果希望每次打开 Chrome 时自动启用，请给 Chrome 的启动命令加上 --force-renderer-accessibility


【设置chrome启动命令方法】
 对于 Windows 系统，简单来说就是： 1. 在快捷方式上右键，选择属性。 1. 选择“快捷方式”标签。 1. 在“目标”一行的末尾，添加上启动参数。 1. 最终效果应该像这样： ……\chrome.exe" --force-renderer-accessibility

**Comment by funsgang** [comment]
> Chrome好像不是标准的Windows窗口吗，能否支持选取元素？谢谢
> 顺祝：中秋快乐！

截图时无法自动选取浏览器窗口的页面元素
	* 
对于 Chrome 浏览器，请在地址栏中输入并打开 chrome://accessibility，勾选 Native accessibility API support 以及 Web accessibility
	* 
Chrome 每次关闭之后都会重置这些设置，如果希望每次打开 Chrome 时自动启用，请给 Chrome 的启动命令加上 --force-renderer-accessibility


【设置chrome启动命令方法】
 对于 Windows 系统，简单来说就是： 1. 在快捷方式上右键，选择属性。 1. 选择“快捷方式”标签。 1. 在“目标”一行的末尾，添加上启动参数。 1. 最终效果应该像这样： ……\chrome.exe" --force-renderer-accessibility
