### ISSUE TITLE
贴出来的图片右键里面的快捷键，按快捷键没反应，这是怎么回事

### ISSUE THREAD

**Issue by yinhux** [liulex/Snipaste-Feedback#125]
@liulex 
贴出来的图片右键里面的快捷键，按快捷键没反应，这是怎么回事，就是贴出来的图右键选项里面的单键快捷键没反应  不知道是我设置哪里错了吗 还是怎么回事  我用的win10   

作者以后会更新拼接图片吗     就是截图后贴出来，然后对它进行右键，里面有选项可以选择特殊粘贴【里面包含粘贴到右侧、左侧、顶部、底部】成为一张新的贴图，因为由于在工作会有很多反馈，这样我可以把反馈都粘在一起，这样看比较方便，希望作者能增加这个小功能
![sp20160916_120729](https://cloud.githubusercontent.com/assets/21018274/18575509/0edfb74a-7c0b-11e6-8fa7-c1c83f8a40b4.jpg)

  
另外双击贴图缩小也希望作者能够增加，因为贴图多了一起隐藏不太方便，毕竟只想让某个图片缩小而已，只是这个图片挡住了，【因为我是做原画的，所以这个功能用的比较多】所以只希望这个贴图参考图可以缩小，其他的不便，要用的时候在还原，就像缩小到滚轮缩放的那样大小10%就可以了，就像setuna那个软件一样，  这个软件我最喜欢的功能是能贴出选中的文字，还有可以贴出gif动图，这个我非常喜欢，这是其他软件没有的功能 ，这是亮点

能增加是贴图变为灰度图像吗，由于绘画原因，有时候会用到这个功能，方便查看参考的黑白关系，感谢作者了

另外如果可以的话 希望能够增加滚屏截图功能

**Comment by liulex** [comment]
右键菜单的快捷键没反应，可能是有 BUG 吧，请将你的 IM 联系方式发送到 <snipaste.app@gmail.com>，我会联系你进行调试一下（不过最近没空……）。

另外几个需求，虽然你很认真很用心地描述，但我还是得说，除了灰度图像那个，其他都有人提过 issue 了…… :joy: 

你可以给灰度图像另开一个 issue，及时得知什么时候会加上。

**Comment by StarryVoid** [comment]
没找到新的功能，。。我的设置问题？

**Comment by yinhux** [comment]
@StarryVoid  对贴出来的图 进行右键    你就会看到快捷键
![sp20160917_104620](https://cloud.githubusercontent.com/assets/21018274/18605396/02bfddf0-7cc4-11e6-9277-5162227a97d5.jpg)

**Comment by liulex** [comment]
最后发现是 @yinhux 误解了菜单快捷键的用法……所以并非有 bug
