### ISSUE TITLE
新版加的十字线很好看.就是移动过程中有点抖动啊.

### ISSUE THREAD

**Issue by jr21066** [liulex/Snipaste-Feedback#126]
就是重绘比较慢时产生的那种感觉象虚影一样的闪烁感.
好比黑线移动时.先把背景全填充为透明.再画黑线.而不是只填充黑线原来的位置

能不能优化一下呢.

**Comment by StarryVoid** [comment]
本人非作者
你说的是不是在Office的LOGO出现时截图，在logo区域的鼠标指针飘忽的那种现象。
这种现象属于指针检测那，，作者暂时不太想优化这个，因为不太影响使用。

**Comment by jr21066** [comment]
我是在浏览器和桌面上试的
因为截图时背景已经不动了.所以估计还是重绘的原因

**Comment by StarryVoid** [comment]
还是等待作者回答吧，我没太理解。

**Comment by liulex** [comment]
绘制十字线确实会影响效率的。

但根据你的描述，并不是绘制效率的问题，是十字线并不是纯色的黑线，而是反色的（以使其在任何背景下都可见），所以底下的像素颜色不同的时候，十字线的颜色也会相应变化，造成了你所谓的“虚影、闪烁”。
