### ISSUE TITLE
保存截图的图片质量被压缩 

### ISSUE THREAD

**Issue by yinhux** [liulex/Snipaste-Feedback#128]
@liulex 
截图保存的图片质量被压缩了，这个作者可以设置为不压缩或者自己压缩吗，这个保存后图标质量会下降一些

另外 作者的这个检查更新 为什么是下载失败？
![sp20160917_105122](https://cloud.githubusercontent.com/assets/21018274/18605419/c190df36-7cc4-11e6-9794-a150260b178f.jpg)

**Comment by StarryVoid** [comment]
本人非作者
首先你准备是不压缩的么？bmp格式？
常见的图片格式都是压缩的吧。。

检查更新失败的话，问一下你的版本是多少？

**Comment by liulex** [comment]
@yinhux 检查更新失败，请重新下载官网最新的安装包，以后即可正常检查更新。（之前有一次放出的压缩包缺少了两个 dll 文件）

截图保存的质量，目前是 Qt 默认的设置，应该能满足大多数人在大多数情况的需求。
以后会增加自定义保存质量。

**Comment by yinhux** [comment]
@liulex 
恩恩 已经下载1.7.3解决了 谢谢  期待自定义保存质量   顺便问下作者 会增加裁剪功能吗

**Comment by liulex** [comment]
@yinhux 应该不会。二次截图就好了……
我希望把标注的功能局限在普通、常用的编辑，希望用它来取代专业的图片编辑工具是不现实的。
