### ISSUE TITLE
能否下载历史版本：1.7.2 在 Windows XP 上提示无法定位程序输入点 QueryFullProcessImageNameW 于动态链接库 kernel32.dll

### ISSUE THREAD

**Issue by qiukebin** [liulex/Snipaste-Feedback#129]
操作系统：Windows XP 32位（zh-hans_windows_xp_professional_with_service_pack_3_x86_cd_vl_x14-74070.iso）刚重装
Snipaste 版本： 1.6可以正常使用
Snipaste 版本： 1.7.2提示无法定位程序输入点于动态链接库kernel32.dll，修复过还是一直提示

**Comment by liulex** [comment]
你好，这个可以下载历史版本：
https://bitbucket.org/liule/snipaste/downloads
1.7.2 的 XP 版确实用了不同的编译方法，可能出问题了，1.7.1 应该就 ok 的。
我会尽快 fix 1.7.2.

**Comment by orzFly** [comment]
> Snipaste.exe - 无法找到入口
> 无法定位程序输入点 QueryFullProcessImageNameW 于动态链接库 KERNEL32.dll 上。 

完整的错误信息应该是这样的。

**Comment by liulex** [comment]
@orzFly 好的，我用回原来的编译方法吧。

**Comment by orzFly** [comment]
@qiukebin 我觉得 issue 标题更应该修改成 “1.7.2 在 Windows XP 上提示无法定位程序输入点 QueryFullProcessImageNameW 于动态链接库 kernel32.dll”，你现在的标题（能否下载历史版本）是一个为了解决你目前问题的方法，而并不是实际遇到的问题。

顺带一提，Windows 里的这种消息框可以直接点了之后按 Ctrl+C 复制（虽然会响一下），然后可以直接粘贴成文本。

**Comment by qiukebin** [comment]
@liulex @orzFly 谢谢

**Comment by liulex** [comment]
@qiukebin 不是编译器的问题，是 XP 没有那个函数……
我暂时让 XP 版不用那个函数吧。

**Comment by liulex** [comment]
@qiukebin 已经修复，重新下载 1.7.2 即可。
@orzFly  感谢协助！

**Comment by qiukebin** [comment]
@liulex 好的，辛苦了

**Comment by qiukebin** [comment]
![sp20160918_110654](https://cloud.githubusercontent.com/assets/16753157/18612595/d870f4e4-7d90-11e6-8347-3b5dcd7408e2.png)
![sp20160918_110805](https://cloud.githubusercontent.com/assets/16753157/18612594/d8709c38-7d90-11e6-919c-e892ac9e7ca4.png)
![image](https://cloud.githubusercontent.com/assets/16753157/18612605/2220c362-7d91-11e6-946e-315341253706.png)

@liulex XP下首次启动没有默认的快捷键，然后也设置不了，不知道是不是我这边个别情况

**Comment by liulex** [comment]
@qiukebin 嗯，问题确认……
不过今天我没时间，明天我调试一下吧

**Comment by qiukebin** [comment]
@liulex 这个作者自己安排好了哈，我只是反馈下遇到的问题哈
