### ISSUE TITLE
取色功能复制hex的下拉菜单不见了

### ISSUE THREAD

**Issue by armie53** [liulex/Snipaste-Feedback#13]
不知道怎么才能调用出复制hex得下拉菜单 还有显示颜色rgb hex 值的小框也不知道怎么调用出来

**Comment by hch0517** [comment]
怎么取色的，热键设置中，没有取色快捷键

**Comment by liulex** [comment]
你好，取色快捷键是固定的。**当你看得见放大镜的时候**（看不见时按 `Alt`），再按 `C `即是取色。
取色之后，按 `F2 `贴图即可贴出颜色卡片，在它的右键菜单你可以复制 HEX 颜色值。

**Comment by hch0517** [comment]
@liulex  会了，非常感谢！

**Comment by armie53** [comment]
@liulex 太感谢了 终于知道这个先后顺序了 谢谢~
