### ISSUE TITLE
希望箭头用鼠标缩放后，能记住当前的比例

### ISSUE THREAD

**Issue by moonhuahua** [liulex/Snipaste-Feedback#132]
希望箭头不是每次都是最小的，这样每次都要用鼠标滚轮来调整大小

**Comment by StarryVoid** [comment]
建议不错，估计作者更改的代码也不多。
等作者回复吧

**Comment by liulex** [comment]
已加上。

**Comment by baifengs** [comment]
是的，当时 我也发现了。追加评论。。。

**Comment by moonhuahua** [comment]
呵呵，能否再进一步，保存下这个鼠标大小的变量，不要每次开机都要调整，谢谢@liulex

**Comment by liulex** [comment]
@moonhuahua 
实际这是一个 bug，箭头及文字的缩放信息有保存在贴图上，没保存在截图上，1.8.8 修复。
