### ISSUE TITLE
WIN 10 企业版 无法运行 

### ISSUE THREAD

**Issue by wonsing** [liulex/Snipaste-Feedback#133]
![snipaste](https://cloud.githubusercontent.com/assets/22285916/18622714/a4f14404-7e65-11e6-8947-c42d89f11128.jpg)
win10 企业版无法运行？
操作系统：Windows 10 32位 企业版
Snipaste 版本： 1.7

**Comment by taroxd** [comment]
@wonsing 我在 Windows 10 1607 x64 企业版运行没有问题。应该不是企业版造成的。

**Comment by taroxd** [comment]
@wonsing 请确认一下你下载的是 32 位版本的 snipaste

**Comment by GregAMO** [comment]
@wonsing 先下载最新版看看好吗？
最近修复了很多bug

**Comment by StarryVoid** [comment]
@wonsing 火钳刘明🌚

**Comment by liulex** [comment]
@wonsing 请上 [官网](https://zh.snipaste.com) 下载
