### ISSUE TITLE
希望可以增加发送当前截图到word的功能，截图，贴word经常这样用

### ISSUE THREAD

**Issue by zhangjianwen159** [liulex/Snipaste-Feedback#134]
Click 'Preview' ☝
先点 'Preview' ☝

Read first:
[Problemshooting](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4) | [Getting Started](https://github.com/liulex/Snipaste-Feedback/wiki/Getting-Started)

* Please search the existing issues (open/closed) before you submit one.
* If you have found multiple bugs or have multiple feature requests, please submit separate issues for them.
* After the problem in your issue is resolved, please close the issue.

### Describe your problem

* Provide screenshot(s) if it is interface related.
* If you have a feature request, please describe your usage scenario in detail, which is important for other users to vote for you and for the developer to approve it.

### Steps to reproduce

* Describe the steps as detailed as possible, including what keys you press and how the interface changes. For example, "Image is not saved after snipping" may be a good title, but in here you should describe the steps of your operation, like:
  1. Press the snip hotkey to start snipping. 
  1. Left click to determine the snipping area.
  1. Press the 'Save' button.
  1. The File Save Dialog pops up and press 'OK'.
  1. There is no saved image in the specified directory.
* Some common behaviors in `Snip` and `Paste` may have different logic or implementations. For example, if the image cannot be saved after snipping, can images be saved from the pinned image windows? It would be great if such information could be provided.
* If the bug is not 100% reproducible, try your best to guess the common conditions of how it occurs.

### Environment

OS: Windows X xx-bit
Snipaste version: x.x

(If it is multi-screen related, please provide you screen settings, including the screens' relative positioning, the resolutions, the DPIs.)

### Possible related settings of Snipaste

(What related settings have you changed? Or you may just provide screenshot(s) of the Option Dialog.)

- Uncheck "xxxx"
- Set the number of xxx to x

---

请先浏览：
[故障排除](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4) | [基础操作](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C)

* 用关键词搜索已有的 issues，看是否已经有人提过。
* BUG 和新功能请求不要在同一个 issue 里描述，请分开发 issues，多个 BUG 或新功能也请分开来发。
* **issue 描述的问题得到解决后，请主动关闭 issue.**

**（以下是开发者建议的描述模版，请根据你的情况自行增删）**

### 问题描述/建议描述

* 如果是跟界面相关的，请提供截图。
* 如果希望增加某一功能，请详细描述你的使用场景，这很重要，它有助于你得到其他用户的赞同，开发者也会据此判断该功能是否值得增加。

### 重现步骤

* 客观地描述你的每一步操作及相应的界面变化。例如，“截图后无法保存图片”是很好的标题，但正文应该更详细地描述每一步，如：
  1. 按截图快捷键开始截图
  1. 单击鼠标左键确定截图区域
  1. 点击保存按钮
  1. 文件保存窗口弹出，点击保存
  1. 选定的目录并没有出现被保存的图片
* 贴图和截图有些行为的实现可能是不同的。比如你希望提交的问题是如上所述的截图无法保存，那么在贴图窗口是否能正常保存图片？也可说明一下。
* 如果该 BUG 并不是 100% 可重现，请尽可能想想 BUG 发生时的共性。

### 运行环境

操作系统：Windows X xx位
Snipaste 版本： x.x 
（如果跟多屏相关，请提供屏幕设置，如屏幕的相对位置，主屏、次屏的分辨率和 DPI）

### 可能相关的 Snipaste 设置

（改动了什么默认设置？或者提供选项窗口的截图即可）

- 取消勾选"xxxx"
- xxx数 设置为 x

**Comment by StarryVoid** [comment]
你可以尝试在截图后选择复制，然后在Word中粘贴。
issues太长了。。
