### ISSUE TITLE
截图时tab键的功能不起作用了

### ISSUE THREAD

**Issue by baifengs** [liulex/Snipaste-Feedback#135]
截图时tab键的功能不起作用了

**Comment by GregAMO** [comment]
先放上这个以防你不知道
>截屏时按下 Tab，可在选取窗口/选取元素之间切换
来自[1.7更新日志](https://github.com/liulex/Snipaste-Feedback/wiki/更新日志#v17)新增

然后你是说无法切换上述功能,还是无法使用你本来想用 Tab 键做的其他事?
ps:好像在__首选项 - 截图__勾选了__自动检测界面元素__才可以使用上述切换功能

**Comment by StarryVoid** [comment]
@baifengs 详细描述一下呗，可能bug？可能热键冲突？

**Comment by baifengs** [comment]
上下两个检测都开了。
现有新的发现，tab是可以用的，功能打开时，不是全屏像素选择截图，而是自动识别桌面和任务栏两个大的元素块，当时我是开一个叫世界之窗的浏览器，就类似的识别，以为是不能用了，其实是tab像素发截屏bug；关闭tab后，则是完成自动识别所有元素。

**Comment by StarryVoid** [comment]
看完后我整个人都是懵圈的。
1、Tab的功能就是开启/关闭窗口元素检测。
即，开启检测会识别到窗口后将选框圈在窗口上，你浏览器全屏了那就全屏窗口。关闭检测就直接圈在全屏上，不识别窗口
2、What are you doing？

**Comment by baifengs** [comment]
明白了，是我没有好好理解那两个自动检测问题。

**Comment by baifengs** [comment]
发现，还是不行啊。就是有bug。。自动检测有时候无效。

**Comment by StarryVoid** [comment]
@baifengs 能详细描述描述么。。。。。操作流程，，还是直接BUG？

**Comment by liulex** [comment]
@baifengs 
请参看 issue 模版来描述问题。
如认为有 bug，请描述你预期的行为是如何的，Snipaste 实际的行为又是如何。
