### ISSUE TITLE
截图后另存时不能用中文输入法

### ISSUE THREAD

**Issue by moonhuahua** [liulex/Snipaste-Feedback#138]
截图后另存时不能用中文输入法并且不能输入分号和‘等(可能还有其它符号)

**Comment by StarryVoid** [comment]
本人非作者
正常可以使用中文输入法，你看一下是不是输入法切换不了？
建议提交BUG

**Comment by moonhuahua** [comment]
@StarryVoid @septs 就是无法切换输入法(搜狗五笔)，而且英文状态下无法输入分号“；”

**Comment by septs** [comment]
请求报告环境信息
目前 Snipaste 版本
系统版本
输入法版本
输入法切换快捷键是否系统默认如果不是请说明

CC @liulex

**Comment by moonhuahua** [comment]
目前 Snipaste 版本：1.7.3
系统版本：win7X64旗舰版
输入法版本：搜狗五笔输入法2.1正式版(2.1.0.1293)
输入法切换快捷键：系统默认的Ctrl+space
另：可能是我自己搞的ahk引起的问题，因为空格也用不起。。。
不知这个“图像另存为”窗口的class是什么，我自己解决下
![Uploading 无标题.png…]()

**Comment by liulex** [comment]
1. 是否是自己的 ahk 引起的，关掉脚本再试验即可确定。
2. ahk 自带 Window Spy 功能，无法在截图的另存为窗口测试的话，在贴图的另存为窗口测试即可。

**Comment by liulex** [comment]
@moonhuahua 
1.8.4 已经不再屏蔽所有合成的按键，应可解决你的问题
