### ISSUE TITLE
软件更新首次运行时热键判断有问题

### ISSUE THREAD

**Issue by jr21066** [liulex/Snipaste-Feedback#139]
![sp20160921_185437](https://cloud.githubusercontent.com/assets/21333425/18708577/297d0400-802e-11e6-966a-413145747fc5.png)
![sp20160921_185455](https://cloud.githubusercontent.com/assets/21333425/18708578/29ac5584-802e-11e6-8d17-a12bd2389864.png)

已经修改了默认热键.但是还是会检查报告

**Comment by liulex** [comment]
好的，确实没处理好，谢谢反馈，下一版修复。

**Comment by liulex** [comment]
我试了一下，并没有出现你的情况……原来我之前已经处理过了。
你现在是每次启动 Snipaste 都有错误提示？

**Comment by liulex** [comment]
不过现在已经不会再两次注册快捷键了，所以不管怎样，你的问题应该是不会再出现了~
