### ISSUE TITLE
一直不明白贴图是什么意思

### ISSUE THREAD

**Issue by xiaogu** [liulex/Snipaste-Feedback#14]
一直不明白贴图是什么意思。
什么时候要贴图？为什么要贴图？
谢谢。

**Comment by Blank65ck** [comment]
[看一下这里](https://snipaste.gitbooks.io/snipaste/content/zh/) 然后自己试一下就好了嘛~

这还问，不是添麻烦呢嘛。。

**Comment by StarryVoid** [comment]
将图片贴在屏幕上，so 请问还想了解什么？
