### ISSUE TITLE
Snipaste怎么读？

### ISSUE THREAD

**Issue by StarryVoid** [liulex/Snipaste-Feedback#140]
Si Nei Pa Si Te  ？
Si Nei Pei Si Te  ？
Si Nai Pa Si Te  ？
Si Nai Pei Si Te  ？
🌝🌝🌝🌝🌝🌝🌝🌝🌝
🌚🌚🌚🌚🌚🌚🌚🌚🌚

**Comment by liulex** [comment]
['snɪpeɪst]

**Comment by StarryVoid** [comment]
@liulex 不会看音标的我读不出来。。
