### ISSUE TITLE
Windows 10 开始菜单交互问题

### ISSUE THREAD

**Issue by JokerQyou** [liulex/Snipaste-Feedback#141]
Windows 10 下，开始菜单在截图全屏遮罩的上一层，导致在截图时还是可以与开始菜单区域进行交互（包括主显示上的任务栏区域也可以交互）。需要点击一次之后才能截取开始菜单区域。

### Steps to reproduce

1. 按 Windows 键打开开始菜单（非全屏菜单）
2. 按快捷键进行截图

OS: Windows 10 Pro 64-bit 版本 1607（OS 内部版本 14393.105）
Snipaste version: 1.7.3

### Possible related settings of Snipaste

![image](https://cloud.githubusercontent.com/assets/1465267/18743061/e3c347f0-80e9-11e6-89e1-d57be7e88ae6.png)
![image](https://cloud.githubusercontent.com/assets/1465267/18743065/e66ff39a-80e9-11e6-93a9-c25ccbb35773.png)
![image](https://cloud.githubusercontent.com/assets/1465267/18743083/017a8740-80ea-11e6-884c-9e2453c81f47.png)

**Comment by liulex** [comment]
感谢高质量的反馈 :smiley:
这个问题以前已经修复，但最近在新版不小心又出现了，我日前已发现并修复，请等待下次版本更新。
