### ISSUE TITLE
是否可以添加：检测截图的界面元素区域

### ISSUE THREAD

**Issue by fangtaoli** [liulex/Snipaste-Feedback#142]
例如：截设置窗口的图，然后框上某条设置，再框上确定按钮，中间打上箭头表示操作步骤
所以想问问是否能实现截图后，检测截图的界面元素区域，用来框上或其他操作。

**Comment by liulex** [comment]
截图 **后** 是不可能的，截图 **时** 可以，选中 矩形 或 椭圆 或 记号笔/马赛克的矩形填充，在元素上按右键即可自动框上。
