### ISSUE TITLE
希望增加自动保存图片到文件的功能

### ISSUE THREAD

**Issue by lblian** [liulex/Snipaste-Feedback#143]
使用情景为需要大量截图并保存为文件的时候。
现在可以用Ctrl+S保存为文件，但是多了一步确认保存的操作，效率慢了很多。

如果可以自动保存为文件，不需要再确认就会方便很多。

希望保存的文件名可以自定义前缀，并且指定图片格式。

该功能并不急需，有其他软件替代，只是希望作者能加入到待添加功能中，等有时间了再把它实现。

**Comment by GregAMO** [comment]
@lblian 😡请看着软件里“内置快捷键列表”跟我念一遍：
Ctrl+Shift+S 保存图片到用户指定目录
==、
自定义名称  作者 说会有的样子……

**Comment by lblian** [comment]
@GregAMO 没有看到这个快捷键，谢谢提醒。
我希望的是不需要按快捷键，截好图后，双击截图区域则自动保存为文件。（设置功能开关，有需要的人自行开启）

**Comment by liulex** [comment]
@lblian 不同用户对默认的保存方式有不同需求，比如 #38，以后有空会做相关的选项。
