### ISSUE TITLE
在windows 2 IN 1 平板上工作不正常

### ISSUE THREAD

**Issue by atunverse** [liulex/Snipaste-Feedback#144]
设备是联想 miix 4，在使用的时候，会出现只能截取部分屏幕的问题，QQ截图也存在这个问题

**Comment by septs** [comment]
请求屏幕录像
根据文字内容描述无法判断

以上

**Comment by atunverse** [comment]
抱歉打扰了，可能是哪点出了毛病，今天我刚刚买了平板，因为之前台式机用的非常好用所以也装了这个软件，第一次启动出现了些问题，具体情况是截图的时候只有2/3的屏幕可以截取，还有1/3的地方是没有暗下来不能选择选择与截取，后来重启了一次又好了，没有再出现那种状况，我怀疑是第一次安装频繁切换横屏和竖屏的缘故，总之抱歉打扰了

**Comment by liulex** [comment]
@atunverse 当前最新版应该是可以自动适应屏幕配置，而不需重启系统或重启 Snipaste 的。
感觉和 #31 的情况类似，和系统的状态有很大关系，也可能是其他的某软件造成的，目前还未找到能 100% 触发的条件。

**Comment by atunverse** [comment]
恩恩，现在使用十分正常了，将来如果再遇到这种情况我再排查下可能是什么软件不兼容的问题，再来反馈，再次感谢如此好用的软件
