### ISSUE TITLE
在截图选定区域用“画笔”，“有向线段”，“椭圆”等工具涂鸦时，会超出选定的截图区域。

### ISSUE THREAD

**Issue by ZetaoYang** [liulex/Snipaste-Feedback#145]
在截图选定区域用“画笔”，“有向线段”，“椭圆”等工具涂鸦时，会超出选定的截图区域。  
![](https://qanno.github.io/downloads/sp20160926_224412.png)  
应该是有些工具作者没有做边界判断吧

**Comment by liulex** [comment]
@ZetaoYang 这是预定的行为，并非是 bug.

**Comment by GregAMO** [comment]
如果是截图状态，你仍然可以改边界，
如果是贴图状态，你还可以鼠标放上形状变成十字方向标，把形状拖拽回来
自由的 Snipaste~
==、
明明是 Feature 却被认为是 BUG 系列
想起那些非常认真地提示你
此屏幕上已没有空间的手机桌面
