### ISSUE TITLE
请教:自动框选元素,怎么实现的?

### ISSUE THREAD

**Issue by joshatt** [liulex/Snipaste-Feedback#147]
好东东啊, 尤其喜欢折线和箭头线二者兼得
还在学习中, 请教一下, 看到一些动画演示, 可以自动框选元素(或方框或椭圆).....这个怎么实现的? 试了几个都没反应啊

**Comment by GregAMO** [comment]
勾选`首选项 - 截图 - 自动检测界面元素`
之后截图时可以按 Tab 来切换检测界面元素还是检测窗口
来自[v1.7新增功能](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#%E6%96%B0%E5%A2%9E)

--
若是 chrome 请查看
故障排除 - [截图时无法自动选取 Chrome 浏览器窗口的页面元素](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4#%E6%88%AA%E5%9B%BE%E6%97%B6%E6%97%A0%E6%B3%95%E8%87%AA%E5%8A%A8%E9%80%89%E5%8F%96-chrome-%E6%B5%8F%E8%A7%88%E5%99%A8%E7%AA%97%E5%8F%A3%E7%9A%84%E9%A1%B5%E9%9D%A2%E5%85%83%E7%B4%A0)

**Comment by liulex** [comment]
@GregAMO 你误解他的意思啦。
@joshatt 你要的功能，是在截图时，选中矩形/椭圆/其他形状的矩形填充画笔 的状态下，**右键**点击界面元素，即可自动框选。
抱歉这一点确实还没写进文档，会尽快更新的。

**Comment by joshatt** [comment]
是右键啊,谢谢解答......这个功能犀利啊. 还有另一个犀利的, 常用的又区别于同类软件的功能: 折线和箭头线兼备
