### ISSUE TITLE
建议增加history目录路径自定义

### ISSUE THREAD

**Issue by moondigi** [liulex/Snipaste-Feedback#148]
这类绿色小软件我都是放在onedrive同步，缓存历史之类的会放在ramdisk，希望能增加路径定义的功能（绝对路径/相对路径）

**Comment by liulex** [comment]
请更新至 1.8.2，并根据 [这里](https://github.com/liulex/Snipaste-Feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE) 设置。
