### ISSUE TITLE
一点建议

### ISSUE THREAD

**Issue by chineselzh** [liulex/Snipaste-Feedback#15]
首先感谢大大带来的如此牛X的软件！感谢！
然后在使用过程中有个建议，希望考虑，谢谢：
既然有了`贴图`这么优秀的功能，那么个人觉得应该再加一个**添加编号**的功能，并且是自动增减那种智能的，如下图中的`1`和`2`这种，手动添加，自动递增或递减！
![](http://i4.piimg.com/567571/4c3fc326d7b70bb9.png)

**Comment by liulex** [comment]
这种标号，你希望怎样贴图到贴图？
我不是很理解你的意思，不知道有没有其他网友能理解到……

或许你可以更详细地描述一下你的使用场景。

**Comment by chineselzh** [comment]
我的理解是：本软件的`贴图`就是将各种不同的场景聚合到一起。这个功能必须点赞！
既然是这样，那么我们在做一些教程的时候，或者贴图聚合到一起后，聚合的总图片就希望能有一个编号一样的东西，比如第一步、第二步这样子，直接用图章的形式展现会比较好，就像下面这个软件的处理方式，请参考，谢谢！
如图：
![](http://i2.piimg.com/567571/bf364cb1e5826bc8.gif)

**Comment by liulex** [comment]
这就是一种自动编号的图章工具吧？
如果你是指要跨不同的贴图，但共用相同的数字序列（这个贴图用了`1`，另一个贴图再用就是`2`），我觉得是不合理的。如果用户只是要在一张贴图上加图章呢？当然不希望因为一些数字已经被其他贴图用过了而这张贴图不能再使用。

但不管是哪种情况，图章工具目前都是不会考虑的，普通用户用不上，直接添加文字更方便灵活。
你提出的这种属于某一个比较窄的专业用户群（比如做教程）才会用到的功能，Snipaste 希望它的功能对大多数用户都是常用的。

贴图有很多使用场景，你理解的也算其中一种。通常是设计师最需要这一功能，对程序员也很有帮助。而更一般的用法，是可以当做一种临时的备忘录，也能提高普通用户的工作效率。

**Comment by chineselzh** [comment]
好吧，谢谢！

**Comment by StarryVoid** [comment]
实际上，可以先画一个圆，然后写文字。
