### ISSUE TITLE
希望能增加双击Snipaste程序图标即默认全屏截屏且直接选择画笔功能

### ISSUE THREAD

**Issue by evermilan** [liulex/Snipaste-Feedback#150]
演讲者利用一台触摸屏电视进行演讲，将电脑桌面投影到触屏电视上面并且能通过触摸屏操作电脑，希望能实现在触屏上双击Snipaste程序图标后默认全屏截屏并且直接进入画笔模式，并所截屏内容进行写划批注。

**Comment by evermilan** [comment]
当前实现同样功能我需要三步来实现：1）触摸屏点击Snipaste程序图标启用截图功能；2）在触摸屏电视连接的电脑上按快捷键R截全屏并调出了画笔工具栏；3）触摸屏上点击画笔工具栏上的画笔图标进入批注模式。当我说的这个功能实现后那用触屏电视操作起来就非常方便了

**Comment by liulex** [comment]
感谢你对使用场景的详细描述，你提的建议也是可行的，但似乎太过小众了一些……

**Comment by orzFly** [comment]
@liulex 其实这个场景感觉还是很普遍的，就是把 Snipaste 当电子黑板/教鞭之类的用，比如上课的时候一边演示，一边直接在屏幕上标注…

**Comment by StarryVoid** [comment]
描述的这个功能，的确有一定的需求，可能添加后对触摸屏幕会有更好的支持？

**Comment by evermilan** [comment]
@StarryVoid @orzFly @liulex 对的，正是针对这种在电子白板上的使用场景，希望能够脱离鼠标键盘，完全使用触摸屏操作，一边演示，一边进行屏幕批注。

**Comment by GregAMO** [comment]
目前简化一点了：
- 点快捷方式（推荐!使用它的快捷键）开始截屏，并把选区设定为全屏，工具栏已在边角
- 选择画笔，毕竟 Snipaste 还有很多种笔和颜色

参考[命令行选项](https://github.com/liulex/Snipaste-Feedback/wiki/命令行选项)
\Snipaste\Snipaste.exe --snip-full     
 
![image](https://cloud.githubusercontent.com/assets/20766212/20524336/0bcd638a-b0f5-11e6-8057-41b2be658e7c.png)

**Comment by liulex** [comment]
@evermilan v1.11.0 已支持白板模式。
将 Snipaste.exe 拖到任务栏上，右键改变其属性，如上面 @GregAMO 附图所示，在`目标`后增加 `--snip-whiteboard`，以后点击该图标即可开启白板模式，应该比双击托盘图标更方便。因为单击托盘图标是开始普通截图，再增加双击动作不太合适。

**Comment by evermilan** [comment]
@liulex 多谢多谢，新年第一天发布，赞~

**Comment by qrqhuang** [comment]
@liulex 

电子画板真得是非常实用的功能。 

新版命令为： `Snipaste.exe whiteboard`

请问可以将白板模式注册为全局热键， 比如`f4` 吗？

**Comment by liulex** [comment]
@qrqhuang 专业版可以注册任意命令为全局热键。

**Comment by qrqhuang** [comment]
@liulex 

我也是刚看到专业版有此功能。
不知能否成为个人版的常驻功能？ 


倒不是支持的问题， 我个人很喜欢并且也支持了专业版~

**Comment by winter60** [comment]
老大，Snipaste.exe whiteboard 这个命令对于双屏用户，如何指定单屏或默认为鼠标所在屏呢？ @liulex
