### ISSUE TITLE
建议在贴图透明的基础上添加鼠标穿透的功能

### ISSUE THREAD

**Issue by WinxEI** [liulex/Snipaste-Feedback#152]
如图所示：
![image](https://cloud.githubusercontent.com/assets/22310332/18979977/3c5e167e-8702-11e6-8f36-18681fd335ca.png)
在我的某个贴图较大的情况下，我希望能够在透明度即不遮挡视线的情况下，能够对后面的窗口进行操作，例如图中所示的标题框的输入。

**Comment by GregAMO** [comment]
@WinxEI 请查看😓

**Comment by WinxEI** [comment]
是在下错了，我设置热键是F3，结果我按了半天F4不行，以为没这个
