### ISSUE TITLE
如何截图的同时并获取当前截图中可见窗口的文件及网页的标题和路径？

### ISSUE THREAD

**Issue by Italian0** [liulex/Snipaste-Feedback#153]
### 建议描述
在打开wps或word以及其他任何富文本编辑器的界面中可以一次粘贴截图和截图中存在的窗口的标题和路径的文本内容。

如下图所示
加载中。。。。
![image](https://cloud.githubusercontent.com/assets/12107743/18981612/81f621d0-8712-11e6-84c2-fe733c2cc740.png)

**Comment by StarryVoid** [comment]
你想要类似于Onenote的图片文本识别功能？
这只是个截图工具。。

**Comment by ysc3839** [comment]
他应该只是想顺便复制标题文本

**Comment by Italian0** [comment]
@ysc3839 @StarryVoid   类似于  #161  
不能自动化实现就只能手动，

1. 手动 截取  “截图20161005_160426.png”

2.  新建并打开一个doc  "截图20161005_160426.doc"

3. 粘贴  “截图20161005_160426.png” 到 "截图20161005_160426.doc"

4. 如果 “截图20161005_160426.png” 图片中有网页浏览器，
复制浏览器的标题和地址 
像下面这样：
--------------------
>(5 条消息) 首页 - 知乎  https://www.zhihu.com/
首页 - 廖雪峰的官方网站  http://www.liaoxuefeng.com/
读书 - 廖雪峰的官方网站  http://www.liaoxuefeng.com/category/0013738748248885ddf38d8cd1b4803aa74bcda32f853fd000
JavaScript教程 - 廖雪峰的官方网站  http://www.liaoxuefeng.com/wiki/001434446689867b27157e896e74d51a89c25cc8b43bdb3000
www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000  http://www.liaoxuefeng.com/wiki/0014316089557264a6b348958f449949df42a6d3a2e542c000
  http://www.liaoxuefeng.com/wiki/0013739516305929606dd18361248578c67b8067c8c017b000
  http://www.liaoxuefeng.com/discuss
  http://www.liaoxuefeng.com/webpage/donate

    然后粘贴到"截图20161005_160426.doc"

5.  如果 “截图20161005_160426.png” 图片中有文件浏览器，
复制网页浏览器标题和地址
像下面这样：
------------
> python  file:///D:\python
> python backup   file:///D:\python\backup
> python data   file:///D:\python\data

    然后粘贴到"截图20161005_160426.doc"

6. 手动关闭 "截图20161005_160426.doc".
如果手动的化，这个操作至需要约半分钟，
最好能按下prtsc就能一键自动完成。

**Comment by liulex** [comment]
这个功能不具有实用性或普遍性，即我不认为有多少用户有这种特定的需求，所以抱歉，不会加上去。
