### ISSUE TITLE
程序启动还是会检测默认的热键

### ISSUE THREAD

**Issue by jr21066** [liulex/Snipaste-Feedback#155]
![sp20160930_185817](https://cloud.githubusercontent.com/assets/21333425/18989902/36f36ea2-8741-11e6-9885-a07ef7b995c6.png)

上次的主题没来得及回复就关闭了.现在是最新版1.81的截图

![sp20160930_190904](https://cloud.githubusercontent.com/assets/21333425/18989929/5e63df3a-8741-11e6-9ecb-4dc188fe8011.png)

**Comment by ZetaoYang** [comment]
@jr21066 是现在无法注册快捷键吗？

**Comment by liulex** [comment]
1. 主题被关闭可以重新打开
2. 请检查 config.ini，估计是 F3 被设置到最下面两个了，界面上显示快捷键为空，是因为它们是注册失败，而不是被用户主动消除，所以配置文件里还是原来的快捷键
3. 下一版会在注册失败时也清空配置文件中的快捷键
