### ISSUE TITLE
期待允许关了 “ESC关闭”和“Ctrl+单击关闭” & 对焦点所在的贴图高亮外框

### ISSUE THREAD

**Issue by GregAMO** [liulex/Snipaste-Feedback#158]
期待允许关了“ESC关闭”和“Ctrl+单击关闭”
===
因为ESC在贴图“编辑状态”是“完成”，而在贴图“非编辑状态”是关闭，有时候多按了一下，
有时候你以为焦点在这个贴图，实际上在那一个，然后按了ESC，然后就跪了……
高亮外框也是出于同样的想法。

===
Ctrl+单击在其他软件常常是多选（可怕的误触率）
（以及总觉得以后加强拼图功能的时候会用到呢。）

===
这样我的习惯是只用双击缩略图&全部隐藏&Shift+ESC销毁。
不会手残误触了。

**Comment by liulex** [comment]
- [ ] 自定义贴图的鼠标动作
- [x] 高亮当前贴图窗口
