### ISSUE TITLE
在macbook air的windows 10 上ctrl键识别错误

### ISSUE THREAD

**Issue by xinbada007** [liulex/Snipaste-Feedback#164]
是这样的。之前用大约1.6版本的截图时，ctrl-c是没问题的，可以复制截图。

升级到1.7.x的某个版本，及其之后的版本，就不认ctrl了，后来我发现snipaste把macbook air的command键识别成为了ctrl键。这个是比较费解的，因为其他的系统程序（比如复制粘贴）还是认ctrl键的。command键在系统中是作为windows键处理的，也就是点一下command键跳出开始菜单。

希望可以修复这个bug。

**Comment by liulex** [comment]
同样是 MacBook，我这没有问题……
事实上 1.6 之后也没有修改与此相关的代码，只是修复了一个 Ctrl + Shift + S 有时无法响应的 bug.
所以还请确认一下是否 1.6 能正常检测 Ctrl + C，而当前最新版不行？
这里拉到最下面可以下载到 1.6 版：https://bitbucket.org/liule/snipaste/downloads

**Comment by xinbada007** [comment]
你好。不好意思回复晚了，这几天赶论文熬了几个通宵了。

是这样的，最新的1.8.x和次新的1.7.x，确实无法正常检测Ctrl+C。就是经过我的不精确统计，大概正常检测到的几率不到1%，有时候偶尔一下可以用了，很奇怪，过后又不行了。但是按Command+C却是一直可以用。

然后刚刚下载了1.6版本，在版本信息里看到的是：Version 1.6 (2016.08.10)，然后打开、退出、退出、打开的来回反复确认了Ctrl+C是可用的，相对的Command+C就只识别成C（在软件里面只按C是复制颜色，所以我按Command+C在1.6版本里面就等同于按C复制颜色）。

**Comment by xinbada007** [comment]
我的具体配置：Macbook Air 2013款，Windows 10 周年更新版系统，截图快捷键改成了 Alt+A（就是不是默认的F1截图，用的Alt+A）。

**Comment by liulex** [comment]
@xinbada007 
你应该是用了键盘映射软件吧（比如 ahk）？因为 1.7 以后禁用了在截图时的合成按键，以解决与取词软件的冲突。
下一个更新会解除对所有合成按键的禁用，仅禁用取词软件用到的。

**Comment by xinbada007** [comment]
@liulex 嗷嗷嗷嗷，你提及到的取词软件软件确实提醒到我了。我有一个goldendict，用的 ctrl+c+space 实现取词并自动翻译（也就是说我只要按这三键，自动把单词复制到取词窗口，然后取词窗口自动跳出且弹出解释，很方便吧）。我刚把goldendict关了之后，果然ctrl+c在snipaste里面就能够用了。

**Comment by liulex** [comment]
@xinbada007 
我试了下 GoldenDict，它的处理方式和其他取词软件有点不同。
其他取词软件是鼠标松开的时候自动发送 <kbd>Ctrl+C</kbd>，所以我需要屏蔽掉。
GoldenDict 是把 <kbd>Ctrl+C</kbd> 注册了，并且再手动发送一次 <kbd>Ctrl+C</kbd>……

我加了个[隐藏设置](https://github.com/liulex/Snipaste-Feedback/wiki/隐藏选项)，明天新版发布后你在 config.ini 的 [snip] 下面加一行
do_not_omit_synthesized_c=true
就可以了。

当然，如果你同时用到 GoldenDict 以及其他软件的划译功能，那就只有放弃 <kbd>Ctrl+C</kbd>，用 <kbd>Enter</kbd> 来复制到剪贴板了……
