### ISSUE TITLE
添加文字，中文状态下无法直接输入符号

### ISSUE THREAD

**Issue by GregAMO** [liulex/Snipaste-Feedback#165]
现象：「中文」状态下无法「直接」输入符号
---
即：「英文」和「大写锁定」状态下可以输入符号；
「中文」状态下，按字母键出现候选框后，再按符号键，可以输入符号；

但是，以上三种状态下，软键盘都不能输入任何符号，包括**鼠标点击屏幕上软键盘按钮**。
>「符号」指的是除了26字母和10个数字以外的任何符号。包括数字键上方那些。

环境
---
- 手心输入法 或者 谷歌拼音输入法（2.7经典版和3.0测试版） 在Win7 
- 谷歌拼音输入法 在 WinXP

>由于年久失修，谷歌输入法两个版本均来自[新浪科技此页面](http://down.tech.sina.com.cn/page/42066.html)

**Comment by liulex** [comment]
跟系统版本有关，Win 10 + 手心 没事，+ 谷歌 软键盘 有问题。
然而很难修复了，应该属于 Qt 的 bug..

**Comment by GregAMO** [comment]
Win7x64位 + 手心 可以尝试开启 
「设置 - 皮肤 - 显示设置之中的单行模式」
来恢复完全正常使用
写一下万一有人遇到相似情况。
