### ISSUE TITLE
【需求】希望增加二次编辑功能

### ISSUE THREAD

**Issue by chs513** [liulex/Snipaste-Feedback#167]
类似于Evernote，添加到图片上的文字等可以对其进行二次编辑。

**Comment by septs** [comment]
see #16

**Comment by GregAMO** [comment]
咦，印象笔记（圈点）？这应该是和 #79 这个问题一样吧，
(选中任一之前画好的某个元素即可修改的功能，如FSC)

**Comment by liulex** [comment]
> 如何重新编辑已经结束的图案
> * **编辑状态下**，按 <kbd>撤销</kbd> 直到你需要编辑的图案已经消失，再按 <kbd>重做</kbd>
 > * 将来会支持直接的二次编辑

来自 [基础操作](https://github.com/liulex/Snipaste-Feedback/wiki/基础操作#如何重新编辑已经结束的图案)

**Comment by chs513** [comment]
@liulex 非常感谢! 希望二次编辑功能不需要等太久~~
