### ISSUE TITLE
missing api-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by jiaxiang-liu** [liulex/Snipaste-Feedback#17]
Missing this dll, snipaste can't launch. 

Tried 32-bit/64-bit, same error poped up

**Comment by liulex** [comment]
Please install [Visual C++ Redistributable for VS 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145).

See FAQ (in Chinease):
https://snipaste.gitbooks.io/snipaste/content/zh/problems/windows.html
