### ISSUE TITLE
将 Snipaste 放进 Program Files 文件夹后，赋予 Snipaste 管理员权限，无法开机自启动

### ISSUE THREAD

**Issue by Shensven** [liulex/Snipaste-Feedback#172]
### 运行环境

操作系统：Windows 10 64bit 14393.321
Snipaste 版本： 1.8.5（2016.10.13） 
### 可能相关的 Snipaste 设置
- 已勾选"开机启动"

我把Snipaste解压后放到了C盘的ProgramFiles文件夹里，并在Snipaste.exe的属性里给予管理员权限，Snipaste.exe的首选项里也勾选上了"开机启动"，当我重启电话后，Snipaste.exe却没有自启动。

![sp20161015_152723](https://cloud.githubusercontent.com/assets/16205980/19408322/8c399c86-92ec-11e6-95d9-8525ec362de9.png)
![sp20161015_153017](https://cloud.githubusercontent.com/assets/16205980/19408324/8f06db54-92ec-11e6-898c-96619955855b.png)

**Comment by septs** [comment]
您是给快捷方式设置的权限

**Comment by liulex** [comment]
见  [故障排除](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4)：

> 开机启动失效
> * 是否在 Snipaste.exe 右键属性里勾选了“以管理员身份运行此程序”？
>  * 在 UAC 开启的情况下，管理员身份的程序是无法通过启动文件夹中的快捷方式实现开机启动的
>  * 解决办法
>    * 取消勾选“以管理员身份运行此程序”
>     * 或者，用添加计划任务的方式实现开机启动（请自行搜索解决）

**Comment by GregAMO** [comment]
如果你不放在C盘（系统盘）可以正常启动？
以及这类便携软件为何要放在系统盘……

**Comment by liulex** [comment]
简单来说，如果手动启动的时候，会弹出 UAC 确认窗口的，那么启动它就是需要你再点一下。
通过启动文件夹实现开机启动的时候，没法让用户点那一下，所以会启动失败。

如果坚持以管理员身份启动，那么就需要以服务的方式或者添加计划任务的方式来开机启动。
这个过程也可以由程序来完成，但我认为 Snipaste 以管理员身份启动的必要性不大，所以暂时不会去实现以管理员身份的开机启动。

**Comment by Shensven** [comment]
@septs 给快捷方式设置权限后，ProgramFiles里的snipaste.exe会自动同步设置

**Comment by ysc3839** [comment]
@liulex 服务的话有Session 0隔离，启动后看不到GUI界面的。

**Comment by liulex** [comment]
@ysc3839 谢谢建议，目前已经使用计划任务的方式实现了。
