### ISSUE TITLE
在Eclipse中截图，开自动检测界面元素，会很卡

### ISSUE THREAD

**Issue by Hero-here** [liulex/Snipaste-Feedback#174]
记得之前的版本，没有这个问题，望知悉

**Comment by Campanula** [comment]
我这里无法重现，是单独对eclipse出现的现象吗？现在Snipaste的最新版还有这个现象吗？

**Comment by septs** [comment]
请提供本地环境信息
eclipse版本
eclipse JVM参数是否默认
系统版本
内存大小

**Comment by Hero-here** [comment]
辛苦了

> 我的Eclipse版本
Version: Neon.1a Release (4.6.1)
Build id: 20161007-1200
---
>jdk版本
java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)
---
>系统版本
Microsoft Windows
版本1607（OS内部版本14393.321）
---
>内存大小
8GB

**Comment by liulex** [comment]
嘛，其实元素检测这个更多是好玩，就我自己的使用经验来说，真正需要用到的情况很少。
如果卡得影响大多数时候的使用，建议在选项窗口关掉，需要时通过 Tab 键切换即可。
因为卡不卡，其实是取决于被检测的窗口的程序实现。

如果说之前的版本没有问题，那大概就需要你测试一下是哪个版本了。。

**Comment by Hero-here** [comment]
并不是在界面元素很多的工具栏或者菜单栏，而是在编辑区卡... ...![](http://img.t.sinajs.cn/t4/appstyle/expression/ext/normal/34/xiaoku_thumb.gif)
