### ISSUE TITLE
贴图界面能否加入Ctrl+x关闭，Ctrl+d销毁，另请问截图时AHK_Class是什么，感谢！

### ISSUE THREAD

**Issue by moonhuahua** [liulex/Snipaste-Feedback#175]
现在这两个右键菜单里面的功能比较常用，加个快捷键应该体验更好：：
![image](https://cloud.githubusercontent.com/assets/15684037/19414925/30302f46-9390-11e6-88c0-aaeaf0406eda.png)

另：：
请问截图时Ahk_Class是什么，可否在截图时用ahk自己加入热键，感谢！

**Comment by liulex** [comment]
抱歉：
1. 有快捷键，请自行查阅内置快捷键或者文档。
2. 截图时的 ahk_class ，以及 ahk 能否实现到你的要求，没必要由我告诉你。你总是在说 ahk，但似乎你并没有掌握 ahk。新版已经尽力兼容 ahk，至于 ahk 如何使用，不应该在这里提问。
