### ISSUE TITLE
1.8.7版本保存输出路径C:/Users/Administrator/Desktop时要加/才行

### ISSUE THREAD

**Issue by xintiandi** [liulex/Snipaste-Feedback#176]
1.8.7版本保存输出路径C:/Users/Administrator/Desktop时要加/才行
C:/Users/Administrator/Desktop/，否则ctrl+shift+s后，保存的路径为C:/Users/Administrator 这个目录中，而不是桌面，之前1.8.5版本不存在这个问题。

**Comment by liulex** [comment]
问题确认，会尽快修复的。
