### ISSUE TITLE
4K屏（高分屏）下截图卡顿，反应迟滞，望解决。

### ISSUE THREAD

**Issue by perfumekiller** [liulex/Snipaste-Feedback#177]
我的电脑是4k高分屏，电脑性能很高，但截图时反应迟钝。我将电脑分辨率降低为1080p之后，问题消失。
希望予以解决，谢谢。

**Comment by liulex** [comment]
高分屏确实有问题，但我目前只有最高 2880*1800 的屏幕，而这个分辨率还不能 100% 重现从而调试。
所以因为设备的原因，短期内是无法修复了。

**Comment by jr21066** [comment]
软件选项里的"自动检测窗口"关闭后会快很多的.

**Comment by luantu** [comment]
我在win10 64bit下，关闭自动检测窗口只有也一样会卡。。

**Comment by liulex** [comment]
@perfumekiller @luantu 
下一版有大幅改善截图效率，可发封邮件到 <snipaste.app@gmail.com>，我给你们发测试版看看。
