### ISSUE TITLE
截屏窗口有时未遮盖任务栏

### ISSUE THREAD

**Issue by ZetaoYang** [liulex/Snipaste-Feedback#178]
我目前使用的是 1.8.8 版本，在截屏时，当截屏的下边界与任务栏相切时，截屏下边界的那个工具条会放置在任务栏下面，导致无法用鼠标进行涂鸦。问题根源：工具条无法自动根据截屏情况自动选择放置的位置。也就是说，目前版本工具条的位置摆放是固定的。还望作者辛苦，修复这一设计缺陷。

**Comment by liulex** [comment]
你可以移动一下截屏区域，比如移动到任务栏以下，看看是否我没有考虑工具条位置的自动调整？
当然，目前的自动调整还可以改进，但问题是，不管怎样调整策略，总是会有一些情况，工具条是一定会挡住截图区域的。比如，选择全屏为截图区域的时候。

所以，如果觉得挡住了，不妨先点图钉的图标把截图贴到屏幕上，然后再编辑，这也是贴图的用法之一。

**Comment by ZetaoYang** [comment]
可不可以，当截屏的下边界与任务栏相切时，将工具条“浮”在任务栏之上。

**Comment by ZetaoYang** [comment]
当截图区域置于任务栏之下时，再将工具条置于截图区域的上边界。

**Comment by ZetaoYang** [comment]
比如，当选择全屏为截图区域的时候，可以将工具条“浮”在截图区域的右上角。而且，一般截全屏的时候，大家应该都会用“prt sc sysrq”这个键吧。

**Comment by ZetaoYang** [comment]
再提一个建议：在 “首选项” 设置中，‘常规’，‘截图’，‘贴图’，‘输出’，‘热键’，‘关于’这六个选项卡设置中窗口长度都不一样，建议添加一个滚动条，并固定窗口的长度。这样更正规点（ps.仅个人观点）。

**Comment by liulex** [comment]
什么叫”浮“？
我说的全屏，只是便于理解的一种情况，并不是只有全屏才会出现无法调整的情况。

这里不是论坛，有其他建议请另开一个 issue.

**Comment by ZetaoYang** [comment]
我上面说的“浮”是指将工具条置于截图区域的上面（效果就像悬浮在截图区域的表面），或者任务栏的上面（效果就像悬浮在任务栏的表面）

**Comment by ZetaoYang** [comment]
示意图：
![image](https://cloud.githubusercontent.com/assets/10769951/19417911/479c0ec4-93eb-11e6-8c7c-2d2885645a86.png)

**Comment by Campanula** [comment]
你是说会遇到任务栏“覆盖”工具条导致无法操作吗？我这里试了下没这个问题

**Comment by Campanula** [comment]
@ZetaoYang
_(:з」∠)_，看有没有人重现吧，这真是个bug

**Comment by liulex** [comment]
抱歉还是无法理解你的”浮“和现在的工具条的摆放有什么区别。
至于右下角还是右上角更优，看法因人而异，我是认为左下角，因为平时它就是右下角的，既然两个位置都是会挡到的，为什么要去改变它的位置。

**Comment by liulex** [comment]
…………
所以争了半天，其实是个 bug ……
我还以为 @ZetaoYang 意思是工具条挡住了部分截图区域。

**Comment by GregAMO** [comment]
我感觉你说的两个提议都是已经实现了的……
不管是工具条浮在任务栏以上，还是全屏时候盖在截图的一角。
***
下边界与任务栏相切
![image](https://cloud.githubusercontent.com/assets/20766212/19417979/08d29634-93ed-11e6-9062-cb004f3174f2.png)

***
全屏截图时
![image](https://cloud.githubusercontent.com/assets/20766212/19417982/11de103c-93ed-11e6-9cd4-403126c4fcc1.png)

**Comment by liulex** [comment]
@ZetaoYang 

能否就以下几种情况截几个图，截图包括整个截图区域以及工具条即可（不要手机拍照，Snipaste 截图模式时可以用其他截图工具对 Snipaste 进行截图）：

1. 当截屏的下边界与任务栏相切时
2. 截屏区域下边界等于屏幕底边

我需要知道截屏窗口、工具条、任务栏这三者的层叠关系。

**Comment by ZetaoYang** [comment]
@liulex 很抱歉，问题我现在也无法重现

**Comment by liulex** [comment]
@ZetaoYang 那能否回忆一下，出现那种情况的时候，任务栏是不是亮的（即没有被 Snipaste 的遮罩盖住）？

**Comment by ZetaoYang** [comment]
@liulex 任务栏是亮的，依然可以用鼠标移动来切换程序，并且还可以预览程序窗口。

**Comment by liulex** [comment]
@ZetaoYang 好的，那难怪了.. 我留意一下这个 bug
