### ISSUE TITLE
两个改进建议

### ISSUE THREAD

**Issue by ZetaoYang** [liulex/Snipaste-Feedback#179]
1.在“首选项”设置中，这六个‘常规’，‘截图‘，’贴图’，‘输出’，‘热键’，‘关于’，选项卡的窗口显示长度不一致，有的太长，有的太短。建议添加滚动条，并固定窗口显示的长度。比如，
‘贴图’：  
![image](https://cloud.githubusercontent.com/assets/10769951/19417987/475628bc-93ed-11e6-8bc3-f38df2ed90f3.png)  
和 ‘输出’
![image](https://cloud.githubusercontent.com/assets/10769951/19417991/5000238c-93ed-11e6-9dac-563de6e306e1.png)
的窗口长度差异也太大了吧

2.对于图床功能，作者可以参考这个开源项目 [Greenshot](https://github.com/greenshot/greenshot)  
![image](https://cloud.githubusercontent.com/assets/10769951/19417981/0ac00e40-93ed-11e6-8607-6751640f6f76.png)

**Comment by liulex** [comment]
1. 其实我个人蛮喜欢切换标签之后窗口长度随内容自动缩放的 \_(:з」∠)\_。不过你说的也在理，以后再看看怎么改比较好。
2. 图床功能相关的讨论请到 #60 . 谢谢你提供的参考，以后大概也会以插件的形式进行支持。

P.S. 我贴图选项都做那么长了，如此彰显其重要地位了，你们还不爱用它 \_(:з」∠)\_

**Comment by Hero-here** [comment]
表示非常喜欢贴图功能

**Comment by Chengxi9** [comment]
贴图选项那么长了，如此彰显其重要地位了，这个不错，我喜欢

**Comment by StarryVoid** [comment]
@Chengxi9

**Comment by StarryVoid** [comment]
@StarryVoid 上面的信息是错的。
贴图一直在用。
