### ISSUE TITLE
写文字的时候，不能调整字体大小，这个不太好

### ISSUE THREAD

**Issue by Arethusa2015** [liulex/Snipaste-Feedback#18]

**Comment by liulex** [comment]
请不要习惯性地以为文字大小只能通过字体大小选框才能更改，请尝试拖动文字框。
关于标注功能的说明：
https://snipaste.gitbooks.io/snipaste/content/zh/basics/edit.html

**Comment by Arethusa2015** [comment]
@liulex 好的，我没注意看文档说明。
