### ISSUE TITLE
希望能够改进一项功能——快速截图并保存上一次截图区域

### ISSUE THREAD

**Issue by Chengxi9** [liulex/Snipaste-Feedback#180]
1.8.8要实现这一功能需要按3次快捷键
1、截图
2、R键
3、Ctrl+Shift+S
希望能改进为2次快捷键如：
1、截图上一次区域Ctrl+Shift+R(自定义)
2、快速保存
或者改为按一次就行
1、截图上一次区域并保存Ctrl+Shift+R(自定义)

PS：感谢作者开发这个好的软件

**Comment by liulex** [comment]
其实，对于一个并非常用的功能，没有必要专门加个一键直达的快捷键，所以 Snipaste 没有默认加入一键截取上次区域、一键全屏截图、一键截图并自动贴图等此类功能。
要加的话，其实没完没了的…… \_(:з」∠)\_

不过我也明白，这些功能对一部分人来说会是常用功能。
以后再看看怎么加比较好……

**Comment by Chengxi9** [comment]
可不可以把基础的功能做成自定义的组合？此类功能大都是能够按照目前的功能组合在一起的，如果可以的话，可以设置一个自定义的快捷键，对于这个快捷键，依次完成自定义的组合不久可以了吗？不知道这样会不会一劳永逸的解决一键直达的需求

**Comment by liulex** [comment]
归到 #38 吧
