### ISSUE TITLE
截图时对子窗口的枚举能优化一下吗

### ISSUE THREAD

**Issue by jr21066** [liulex/Snipaste-Feedback#184]
因为截图时窗口实际是已经冻结的一张图.
程序可以一次枚举所有窗口的.这样在截图移动鼠标时就不会一卡一卡的.

图中这个选项对性能影响很大.
![sp20161020_133207](https://cloud.githubusercontent.com/assets/21333425/19547343/e5572730-96c9-11e6-977f-97530a96d287.jpg)

**Comment by liulex** [comment]
如果实现可以如你所说那么简单，那我是为什么还要写出复杂的实现？
在你机器上卡，关掉就好了。
