### ISSUE TITLE
建议增加键盘和鼠标的混合操作

### ISSUE THREAD

**Issue by jr21066** [liulex/Snipaste-Feedback#185]
比如双击截图区域是保存到剪辑板.
Shift+Ctrl+S是快速保存

能不能也同时支持按住Shift双击截图区域为快速保存呢.

另外有个地方显示有点问题.不影响功能.
如果图中windows的路径是正斜杠
![_20161020_134454](https://cloud.githubusercontent.com/assets/21333425/19547654/1ea91456-96cc-11e6-9fb3-744bca3fb67b.png)

**Comment by liulex** [comment]
可以 Shift + 保存按钮。
双击截图区域是保存到剪贴板，加上 shift 就变成快速保存的话，逻辑上说不通，所以不会默认支持这个动作。

以后加入脚本/插件系统可以满足你的需求。
