### ISSUE TITLE
1.8.8版本中发现文本旋转非常卡

### ISSUE THREAD

**Issue by jr21066** [liulex/Snipaste-Feedback#186]
WINDOWS10 64位.关闭UAC
测试了1.8.8的64位和32位.都存在.
虚拟机8.1里测试正常

就是截图后.点文字.输入几个文字.按Ctrl键对文字进行旋转.动一下就卡住了.
后来在Snipaste的属性里,兼容性.选中以管理员身份运行就好了.

可我系统已经关闭UAC.也是普通管理员登录的.
早期的版本没有这个问题.不过中途我重装过同版本的系统.应该不影响吧.

**Comment by liulex** [comment]
感谢你的测试，但经你描述，还是更像你的系统问题。
最近并没有更改这部分代码。
