### ISSUE TITLE
建议增加Shift - C复制十六进制颜色的功能

### ISSUE THREAD

**Issue by IceWeet** [liulex/Snipaste-Feedback#187]
工作中不同工具需要的颜色码不一样，例如Wiindows默认设置使用的是RGB，Unity则只能用十六进制，因此需要经常在这两者之间切换，通过设置切换比较麻烦，因此建议能通过两组快捷方式分别复制不同格式的颜色码。

**Comment by liulex** [comment]
建议很合理，下版本会加入。
