### ISSUE TITLE
建议：添加功能 "复制所有贴图中的纯文本”  shift多选贴图进行复制销毁

### ISSUE THREAD

**Issue by mfmain** [liulex/Snipaste-Feedback#189]
对程序猿来说，这个功能还是很有用的

**Comment by GregAMO** [comment]
批量处理 聚集地 -> #54 
单纯对图片的批量处理在路上了，
无视图片，一次性提取所有文本，这个还是问作者

**Comment by liulex** [comment]
好奇问一下，使用场景？

**Comment by StarryVoid** [comment]
好奇问一下，使用场景？

**Comment by wuyuehua** [comment]
目前对“将文本贴图”功能很依赖，就像便利贴一样方便。
可一旦窗口中文本贴图过多便需要整理，一条条整理显得麻烦。
以上为使用场景。
