### ISSUE TITLE
微调截图区域时，放大预览处蓝色边框会阻碍边框对齐

### ISSUE THREAD

**Issue by Jack-Works** [liulex/Snipaste-Feedback#190]
当测量某一块屏幕区域的长宽时，需要在四条边上对齐
但是放大处会有蓝色的选中区域的边框（很厚）阻碍精确调整
能否在放大预览处把边框做细？
谢谢

**Comment by liulex** [comment]
放大镜中的宽度自然是要跟实际的宽度保持一致的。
根据你的情况，请调整这两个选项。
![sp20161023_111006](https://cloud.githubusercontent.com/assets/2010459/19623883/53ae276c-9911-11e6-8a13-d1bb1174c410.png)

**Comment by Jack-Works** [comment]
感谢，成功解决
