### ISSUE TITLE
bug 按ctrl+shift+F3 出错卡死

### ISSUE THREAD

**Issue by baifengs** [liulex/Snipaste-Feedback#191]
这个重复性也不是100%。
截图，f3贴图，调出选项，按ctrl+shift+F3 ，多按几次，不同按顺序，或选项与贴图的顺序。结果卡死，出系统出错对话框。
这里上会以不了图片，或我不会用国。

**Comment by liulex** [comment]
意思是切换贴图分组导致崩溃吧？

**Comment by baifengs** [comment]
我知道ctrl+f3是切换分组的，我就是试一下三个组合键的效果，结果就出错了。

**Comment by liulex** [comment]
我意思是你设置中 Ctrl+Shift+F3 是作为什么的快捷键？

**Comment by baifengs** [comment]
这个快捷键没有设置什么东西，就是乱按的。说白了就是看看这个软件的稳定性怎么样。也是突然想起来的按的。

**Comment by liulex** [comment]
没有设置什么东西，按下就不会有任何效果。
你的乱按，就只是在触发 ctrl+f3 和 shift+f3，导致的崩溃，应该就是切换贴图组的原因，新版应该已经修复。

**Comment by baifengs** [comment]
嗯，目前好像没有了。有新的bug了，请看#199项。
