### ISSUE TITLE
希望可以增加按住空格键拖动选区功能 / Wishing a feature of "moving selection area by holding spacebar while drawing it or resizing it" just like what we do in PhotoShop.

### ISSUE THREAD

**Issue by mtcw** [liulex/Snipaste-Feedback#192]
![image](http://ww4.sinaimg.cn/large/c2e8fbcdgw1f93e5f2gczj201w01zjr7.jpg)我也来i个su(咦?
---
Wishing a feature of "moving selection area by holding spacebar while drawing it or resizing it", just like what we do in PhotoShop.
## 希望可以像PhotoShop的选区工具一样可以按住空格键移动选框
觉得PhotoShop的这个设定非常好, 希望Snipaste可以吸收下, 这个功能使用起来是这样的, 咳咳:
**当你选取一片区域的时候:**
首先按下鼠标左键;
然后拖动鼠标;
**在松开鼠标左键之前按下空格键可以移动整个选取范围, 整个选取框随鼠标一起移动;
弹起空格键后可以继续调整选取范围大小, 直至松开鼠标左键.**
重新调整选区大小的时候也可以就更好啦(<ゝω·)☆~

![image](http://ww4.sinaimg.cn/large/c2e8fbcdgw1f93dfbcv7wg208w06oab0.gif)
这个功能的便捷之处在于当你对选区左上角坐标不满意时不需要取消选区或者做移动选区之后再去瞄准选区右下角或者交叉调整左上角右下角之类繁琐的操作.

第一次用github不知道有没有哪里不对///A///一如既往的感谢 @liulex

**Comment by liulex** [comment]
不错的建议，实现好了~

**Comment by mtcw** [comment]
好快!!

**Comment by StarryVoid** [comment]
@mtcw 好主意，赞，不过想到然后用的人不多

**Comment by mtcw** [comment]
@StarryVoid 没关系! 木已成舟了! 实现这个功能他只花了几分钟时间! 膜拜OTL
