### ISSUE TITLE
[需求]对于图片保存的自动命名功能

### ISSUE THREAD

**Issue by hhplay** [liulex/Snipaste-Feedback#195]
① 首选项中无法更改默认的图片保存格式, 默认是PNG, 无法设置为默认JPG或者BMP.

② windows开启显示文件格式名的时候, 保存文件会自动命名为  sp* * * * * * * . PNG
如果我直接键盘敲入新的文件名, 虽然替换掉了包含".PNG"的整个名字, 但是保存仍会自动保存为.PNG格式, 这点很好.
但是有一个情况会导致无法保存.就是"小数点+数字"结尾.
例: sp* * * * * *.PNG,  直接键入新图片名 " 大菠萝-10.26"  ,这个".26"就会干扰到保存, 
如果是"小数点+汉字" 或者"小数点+英文字母", 则不会出现问题.

一点小小的细节, 希望可以有帮助.

**Comment by GregAMO** [comment]
① #98 看这个聚合帖，你说的功能实现已经很近很近了，可能就在下一个版本（既然加了`next`标签）
包括自定义命名格式
②你说的是 `Ctrl + S`那个保存窗口? 是 Windows 资源管理器的，不归 Snipaste 管吧

**Comment by liulex** [comment]
@hhplay
功能 1 下版本即会有，如同 @GregAMO 所说，已经有很多 issue 提到过了。
问题 2 如果存在，确实是可以修的，但我测试了 Win 10 和 XP，都不存在什么问题，键入“10.123” 可以被顺利保存成 10.123.png 呢……

**Comment by hhplay** [comment]
重新验证了一下.
OS是WIN7 X64, 

动作是
" Ctrl+alt+A" ,
然后点击"保存图标", 
在弹出的窗口中自动保存名字是蓝色全选的" sp* * * * * * * . PNG", 
直接键盘键入以" 小数点+数字"结尾的名字并点击"保存"按钮
没反应, 退回到截屏的半明半暗选择窗口.

文件夹 选项中  "隐藏已知类型文件的扩展名"  勾选不勾选都无法保存.

**Comment by liulex** [comment]
@hhplay 
抱歉，Win 10 及 Win 7 按照你的步骤皆无法重现，图片可以被正常保存并自动退出截屏。
应该是其他系统设置/软件冲突的问题。
