### ISSUE TITLE
在一些窗口界面无法截图

### ISSUE THREAD

**Issue by baymaxbowen** [liulex/Snipaste-Feedback#196]
在英雄联盟的官方盒子TGP界面下无法通过快捷键进行截图，只能点状态栏中的小图标才可以进行截图

**Comment by GregAMO** [comment]
[故障排除 · 有时候快捷键不响应](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4#%E6%9C%89%E6%97%B6%E5%80%99%E5%BF%AB%E6%8D%B7%E9%94%AE%E4%B8%8D%E5%93%8D%E5%BA%94)

**Comment by mtcw** [comment]
有些dx程序的键盘输入获取方法会造成全局热键失效, 例如那个叫Mabinogi的古董游戏, 具体的不知道=x=
