### ISSUE TITLE
【bug】有多个分组的某些情况无法截图成图和贴图

### ISSUE THREAD

**Issue by baifengs** [liulex/Snipaste-Feedback#199]
在多个组时，每个组有贴图时，其中一个组贴图清空后，再贴图时，听到截图声音，但不能贴图，且贴图级内容是空的，切换到别的组也不成功，得退出程序才行。

**Comment by baifengs** [comment]
双击关闭清空贴图。

**Comment by liulex** [comment]
"贴图级"?
无法理解/重现你的问题……

**Comment by baifengs** [comment]
贴图及。。。。
好像你的1.9.2修复了吧。

**Comment by liulex** [comment]
已定位该 bug，下版本修复。
