### ISSUE TITLE
复制图像无法粘贴到Skype中

### ISSUE THREAD

**Issue by spengjie** [liulex/Snipaste-Feedback#20]
感谢作者的分享，非常棒！

一个小问题：
现状：截图后或者复制图像后无法将图片粘贴到Skype的聊天框中。必须先粘贴到其他地方再复制粘贴到Skype中。这个应该与Skype的实现有关，因为我用Windows的画图复制后也不能直接粘贴。但是QQ的截图是可以做到这点的。
期望：可以粘贴。

**Comment by liulex** [comment]
好的，等我闲下来之后安装个 Skype 试试。
或者知道原因的朋友也可以告诉我。:-)

**Comment by Nicholasny** [comment]
**測試環境:** 
操作系統 Windows 10 Professional x64 版本:1607 (OS 組建 14393.105)
Snipaste Version 1.2(2016.07.29)
Skype:  7.26.0.101
**期望： 可以粘貼.**

**Comment by liulex** [comment]
@spengjie @Nicholasny 
我搜索了一下，这是因为 Skype 只支持读取 Windows Bitmap 格式的图片：
https://greenshot.atlassian.net/browse/BUG-1073
https://github.com/ShareX/ShareX/issues/1239
下一版本会加入选项，使得复制到剪贴板的图片格式是 Windows Bitmap 格式的，从而可以粘贴到 Skype 中，但同时会丢失图片的透明度通道。

**Comment by spengjie** [comment]
@liulex 谢谢，响应真快呀！
