### ISSUE TITLE
选择任务管理器时按F1无反应

### ISSUE THREAD

**Issue by uicake** [liulex/Snipaste-Feedback#200]
选择任务管理器时按F1无反应

1.打开任务管理器
2.（已选定任务管理器）按F1无反应（没弹出截图界面）
3.随便点一下“非任务管理器区域”（如桌面），再按F1，就正常能截图
4.再点一下任务管理器，按F1，无反应

 BUG 是 100% 可重现

### 运行环境

操作系统：Windows 10 64位
Snipaste 版本： 1.9.1

**Comment by GregAMO** [comment]
[故障排除 · 有时候快捷键不响应](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4)
Wiki 常常是很有帮助的 :)

**Comment by uicake** [comment]
这，我有看过wifi，不过是ctrl+f直接搜索“任务管理器”，所以就没看到这条了ORZ
