### ISSUE TITLE
【BUG】托盘图标右键菜单中，点击『隐藏所有贴图』，实际效果是显示所有贴图。

### ISSUE THREAD

**Issue by xuchkang171** [liulex/Snipaste-Feedback#202]
### 问题描述/建议描述
- 托盘图标右键菜单中，点击『隐藏所有贴图』，实际效果是显示所有贴图。
- 通过热键（Shift+F3）隐藏/显示所有贴图时，正常。

### 重现步骤
1. 刚通过『检查更新』从 1.9.0（或者 1.9.1，记不清了。）升级到 1.9.2。
2. 根据更新日志建议循环切换了 3 个贴图组后即回到默认分组。
3. 托盘菜单中选择第三个贴图组。
4. 托盘菜单中点击『显示所有贴图』。正确显示。
5. 托盘菜单中点击『隐藏所有贴图』，实际效果是显示所有贴图（贴图闪烁）；若通过热键（Shift+F3）隐藏/显示所有贴图，皆正常。

重复以上四、五步，该 BUG 100% 重现。

### 运行环境

操作系统：Windows 7 64 位

Snipaste 版本： 1.9.2

显示相关：
- 主屏：DELL U2414H 1920*1080
- 次屏：DELL U2414H 1920*1080（横向、扩展）

### 可能相关的 Snipaste 设置

![](http://i.imgur.com/Vpvq5AU.png)
![](http://i.imgur.com/Wr4ueyP.png)

**Comment by liulex** [comment]
非常感谢你的详细描述以及截图。
是增强版的托盘菜单”显示/隐藏所有贴图“绑定错了动作，实际执行的是“贴图”动作，下一版修正。
