### ISSUE TITLE
[需求]截图时可否第一次点击是截图的起点，第二次点击是截图的终点

### ISSUE THREAD

**Issue by nottellyou** [liulex/Snipaste-Feedback#205]
截图时可否第一次点击是截图的起点，第二次点击是截图的终点。

这种情况可以用于鼠标不是非常灵敏的场景，特别是鼠标垫有问题的情况。

谢谢

**Comment by liulex** [comment]
不可以。
且不论 Snipaste 是否应该为你考虑鼠标问题，截图开始时的单击已经被指定了动作，所以你提出的方案不可行。
