### ISSUE TITLE
建议贴图增加鼠标穿透功能

### ISSUE THREAD

**Issue by IceWeet** [liulex/Snipaste-Feedback#206]
我经常会贴一些较大的参考图，只是放在那作为参考，并不频繁操作贴图，但由于贴图遮挡面积较大，非常影响电脑的正常使用。

建议增加选项允许鼠标穿透。可以像网易云音乐锁定桌面歌词那样，鼠标穿透之后，在参考图某个角上附带一个不穿透的按钮，方便设置。

**Comment by GregAMO** [comment]
首选项 -  热键 - 切换鼠标穿透

对于大图还有切换到缩略图 调整大小 透明度等等方式
==、

**Comment by IceWeet** [comment]
@GregAMO 多谢，刚刚自己也发现有鼠标穿透功能了。不过这个建议也还是有一些价值的，现在的鼠标穿透对于需要频繁切换是否穿透的情况不太方便。建议可以这样：

**Comment by GregAMO** [comment]
1. 频繁切换，可以换个顺手点的快捷键
2. 因为是鼠标穿透，还可以这么依赖鼠标操作哈？
3. 我自己看大图参考的方式：一直快捷键切换[显示/隐藏 贴图]

**Comment by liulex** [comment]
@IceWeet 
没有加入单个贴图的鼠标穿透控制，就是因为还没想到合理的对其单独解除穿透的方式。
你提到的是一种方案，但多出一个按钮，总归还是会干扰的。

目前我想到的是多加一个全局快捷键，其作用是对当前鼠标下的贴图进行鼠标穿透/解除鼠标穿透。
也期待有更好的方案提出。

**Comment by ZetaoYang** [comment]
我觉得 「鼠标穿透」 后可以 将贴图 「透明化/淡化」。

**Comment by BianChengNan** [comment]
可以设置一个快捷键来对选中（或者标记）的贴图进行**切换穿透** 操作

如何选中或者标记呢？
对于非穿透的贴图可以直接点击，对于多个可以按住ctrl进行点击，
对于全部可以增加快捷ctrl+A（只是举例）
对于不能直接点击的贴图（已经是穿透效果的了）可以通过一个特殊的快捷键（比如f6）或者鼠标中键
进行标记，同理按住ctrl表示多选

然后对于标记的贴图统一操作，放大缩小，不透明度，穿透等等
