### ISSUE TITLE
希望增加选项-取色时复制hex/rgb/..

### ISSUE THREAD

**Issue by BluYous** [liulex/Snipaste-Feedback#21]
comment是什么
不管了，这应该懂我的意思吧，有时候不喜欢取色后贴出来又复制其他格式，太麻烦了，不如直接在设置里添加一个选项
另外，希望设置里可以恢复默认设置
最后，感谢snipaste

**Comment by BluYous** [comment]
另外，希望贴图的时候可以读取到鼠标位置，在鼠标位置贴图

**Comment by liulex** [comment]
新版（v1.5）已经可选显示及复制的颜色值为 Hex，请静候发布。
至于在鼠标位置贴图，想法是不错，但是与程序目前的选项有一些交叉，需要考虑一下，有空再加。
