### ISSUE TITLE
和autohotkey有冲突，使autohotkey的模拟按键无效

### ISSUE THREAD

**Issue by MoonlightSinger** [liulex/Snipaste-Feedback#210]
使用的AutoHotKey 版本 v1.1.22.09
使用的snipaste版本 1.8.8
该情况会偶尔出现
导致 AutoHotKey模拟的
Send ^c
的按键动作无效，导致不能让AutoHotKey取到剪贴板的内容
不知道为什么，其他的模拟动作又是正常的
退出snipaste后恢复正常

**Comment by liulex** [comment]
你说的没错，Snipaste 有对模拟的 <kbd>C</kbd> 键进行屏蔽，以解决与取词软件的冲突。
但只在截图的时候才屏蔽，其他时候应该是没有问题的，如有问题应该是 bug，我再调调看。

当然，你可以关闭这项功能，请打开 [隐藏选项](https://github.com/liulex/Snipaste-Feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE) `do_not_omit_synthesized_c`.
