### ISSUE TITLE
添加了矩形、椭圆、折线、文本等，不能再调整截图区域的大小，而且添加的文字、矩形完成后不能再编辑，希望能具有类似faststone capture的编辑功能。

### ISSUE THREAD

**Issue by gy0715** [liulex/Snipaste-Feedback#211]
### 问题描述/建议描述

截图时，添加了矩形、椭圆、折线、文本等，不能再调整截图区域的大小，而且添加的文字、矩形完成后不能再编辑，希望能具有类似faststone capture的编辑功能。

### 运行环境

操作系统：Windows 10 64位
Snipaste 版本： 1.9.2
（如果跟多屏相关，请提供屏幕设置，如屏幕的相对位置，主屏、次屏的分辨率和 DPI）

### 可能相关的 Snipaste 设置

（改动了什么默认设置？或者提供选项窗口的截图即可）

未修改任何参数设置。

**Comment by GregAMO** [comment]
1.  再点一下工具条上（矩形 文本……）按钮，  
退出这个添加的状态就可以再调整区域大小了

**Comment by gy0715** [comment]
谢谢指导，调整区域可以了，但是稍显麻烦了些。
添加的文字、矩形完成后可以再编辑吗？

**Comment by liulex** [comment]
不在编辑状态即可随意调整区域，还能怎么更方便呢？
你的问题在 [基础操作](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C) 都可找到答案。

**Comment by gy0715** [comment]
1.需要多点击下才能调整，不是麻烦一些吗
QQ截图都能实现的功能，希望不要舍弃。
2.将来会支持直接的二次编辑
期待着二次编辑功能，而且连QQ截图都能二次编辑文本了，只是矩形、箭头还不能二次编辑

**Comment by liulex** [comment]
编辑时不允许用户调整区域，主要是怕用户误操作，因为 Snipaste 调整区域的行为是点击区域外任意一点就可以。我试了下 QQ 截图，编辑的时候可以在边界处调整区域，是我 out 了……我对它的认知还停留在编辑后无论如何都不能重新调整区域的那个版本……

二次编辑以后会对所有形状一次性支持。

**Comment by liulex** [comment]
编辑时允许调整区域已实现，下版本支持。

**Comment by lxshui** [comment]
看到作者认真的回答问题我决定将这个截图工具作为主要工具使用了，作者加油，随便问问。。。这个软件开源吗。。。？

**Comment by StarryVoid** [comment]
@lxshui 不开源，不开源🌚

**Comment by Jason4774** [comment]
这个同学提的建议很实用，发现拖动贴图的时候工具栏要乱跑，虽然没什么影响，但是能工具栏能一直保持在贴图的右下角就更好了。

**Comment by GregAMO** [comment]
@Jason4774  并没有乱跑吧。工具栏默认位置就是下边缘。
如果下边缘到了屏幕边缘而上边缘没到，那么工具栏会自动到上边缘。
此外没感觉有什么规则，具体描述下「乱跑」？

**Comment by Jason4774** [comment]
马上发，请看我开的new issue

**Comment by GregAMO** [comment]
> - [x] 添加元素时调整截图区域范围 1.10.0 已支持
> - [ ] 二次编辑以后会对所有形状一次性支持 #79

**Comment by LonelyTear** [comment]
本来正要提问, 发现已经有人提了这个问题, 矩形、椭圆、折线 不能二次编辑极需解决更新, 没有误操作是不可能的, 一旦失焦, 就再也回不了头了, 参考一下Snagit32.exe的功能, 尽快实现下吧 , 有了这个二次编辑那就完美无敌了.
