### ISSUE TITLE
acrobat reader中复制文本会报错“复制到剪贴板时发生错误。出现内部错误”， 退出Snipaste才会正常。

### ISSUE THREAD

**Issue by gy0715** [liulex/Snipaste-Feedback#212]
### 问题描述/建议描述
acrobat reader中复制文本会报错“复制到剪贴板时发生错误。出现内部错误”， 退出Snipaste才会正常。
打开faststone capture也有相同问题，但是hypersnap不会有此问题，希望能加入参数不要监控的太厉害
![image](https://cloud.githubusercontent.com/assets/23148767/19930785/f0b677c2-a144-11e6-9b30-24aa2543f4c5.png)

### 运行环境

操作系统：Windows 10 64位
Snipaste 版本： 1.9.2 
acrobat reader版本：11.0.0

### 可能相关的 Snipaste 设置

未修改配置

**Comment by liulex** [comment]
Snipaste 没有任何监控剪贴板的行为，只是在用户主动请求的时候，读取剪贴板/写入剪贴板。

**Comment by gy0715** [comment]
因为异常原因很明确，开启Snipaste后复制文本才会报错，退出再复制就正常，两者关联性很强。

**Comment by liulex** [comment]
试试升级一下 arobat reader 版本？
我刚安装了最新的版本，没遇到什么问题：
Installed Acrobat: C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe
    Version: 15.20.20039.203716
    Creation Date: 2016/10/01
    Creation Time: 7:36:16

**Comment by gy0715** [comment]
试过了acrobat reader 11.0.0和acrobat reader DC v15.007.20033.2203都有这个问题（可能需要反复多次Ctrl+c），升级到acrobat reader DC 15.20.20039.203716后正常。
也顺便验证了acrobat reader和foxit reader有差距，同样的pdf文档在foxit reader上复制不报错，且acrobat reader复制后粘贴的文本远多于选择复制的文本数量，已改用foxit reader。
