### ISSUE TITLE
能否加入开启/关闭捕获光标的快捷键/快捷方式

### ISSUE THREAD

**Issue by Yoctillion** [liulex/Snipaste-Feedback#213]
有时候会因为一些原因临时开启/关闭捕获光标并在结束后还原回之前的状态，这个时候可能需要打开关闭首选项界面 2 次，有些麻烦。

**Comment by GregAMO** [comment]
@Yoctillion 按左上角的 ` 键来切换…
内置快捷键列表有吧…
