### ISSUE TITLE
几点建议反馈。

### ISSUE THREAD

**Issue by Jason4774** [liulex/Snipaste-Feedback#215]
1.发现拖动贴图的时候工具栏要乱跑，虽然没什么影响，但是能工具栏能一直保持在贴图的右下角就更好了
2.截图时箭头这些还是能穿过截图区域，虽然超过的还是不会被截图进去，但是还是觉得应该超过就显示禁止的图标，或者无效。
3.文字字号的调节，能有qq那种字号大小的调节就好了。
4.能添加滚动截图的功能吗？或者浏览器全屏，全页面截图那种功能。
不知道好不好实现，反正只是好心的几点建议而已。谢谢。

**Comment by Jason4774** [comment]
![image](https://cloud.githubusercontent.com/assets/19594338/20057191/39de9892-a525-11e6-9384-8df21fc8d183.png)
这张图片上有两个问题，
1.我贴图后然后右键，编辑，然后拖动图片的时候，这个时候工具栏会乱跑。
2.我禁用了qq的截图快捷键，然后改Snipaste的截图快捷键为qq的那种，然后在贴图上面按下ctrl+alt+a的时候，因为按下了alt，这个时候就会多出取色的那种提示，然后我截图，就会多截到那个取色的提示。

**Comment by GregAMO** [comment]
2 这是 Feature啊……
- 目前只要不是「选定工具栏上的按钮」状态下，就可以继续改变截图区域。
所以标注（最常见的是文字）出界了可以重新把它们框进来。
- 即将到来的版本，「选定工具栏上的按钮」状态下，也可以拖动边界也可以改变截图区域。

3 #208 也提到了……好奇，「拖拽」的方式不会更直观精确吗？
还是说想要分类，比如部分文字是同一层级，系统统一字号？
4 See #19 ……

**Comment by Jason4774** [comment]
谢谢，其实截长图这个faststone我觉得有时候截出来都是花的，最好能像那种可以直接全页面截图，不用滚动。

**Comment by GregAMO** [comment]
对于 2 楼描述：
1 试了试，感觉你真的遇到了 Bug 
2 就……先放过 Alt？还有你不选中 那个贴图 应该就不会出现 Alt 的取色框了
3 长截图：
对于网页截图，**浏览器扩展** 是最好的，只要 **不超过极限长度** 都是几秒结束

（FS 感觉已经很老牌了都会花么，Picpick 表现如何？我如果想截取超长网页会用它，不过确实会慢）
其实软件也是各种做适配 + 一张张截取下来
然后拼接而已，所以超长网页不会崩溃，但是会花，会慢。）

**Comment by Jason4774** [comment]
FS比如你截图qq好友列表，那种就会花。
网页截长图我有那种浏览器里面截全页面的，不会花，你有什么扩展截全页面吗？
其实不用FS是因为截图后不能直接编辑，不然就直接用FS了。

**Comment by liulex** [comment]
@Jason4774 
图中的工具条位置确实有误，预定的行为是贴图开始被拖动后，工具条会自动消失，直到鼠标按键松开。
如能重现，烦请提供重现步骤。

**Comment by Jason4774** [comment]
贴图后然后右键，编辑，然后拖动图片的时候，这个时候工具栏会乱跑。

**Comment by liulex** [comment]
@Jason4774 
。。。这个步骤的话，是不会有问题的。
是否使用了什么模拟按键软件？应该是其他软件的影响。

另，在贴图上按空格键即可切换工具条。

**Comment by Jason4774** [comment]
![1](https://cloud.githubusercontent.com/assets/19594338/20059316/a24bdaf6-a530-11e6-8b47-e5abc9ed860b.gif)

**Comment by liulex** [comment]
@Jason4774 
。。。请按照 [故障排除](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4) 最后一条进行设置。

**Comment by Jason4774** [comment]
不好意思，之前优化设置的时候确实只保留了两项，实在不好意思，没看那个，非常感谢你

**Comment by liulex** [comment]
好的。至于其他几点， @GregAMO 已有相关回应。
问题解决，关闭。

**Comment by Jason4774** [comment]
![image](https://cloud.githubusercontent.com/assets/19594338/20059843/20845338-a533-11e6-9ffd-0e413f2cc4be.png)
请问这个按键提示是怎么出来的？

**Comment by GregAMO** [comment]
@Jason4774 [KeyCastOW – keycast on windows](https://brookhong.github.io/2014/04/28/keycast-on-windows.html)

**Comment by Jason4774** [comment]
thanks

**Comment by Jason4774** [comment]
![image](https://cloud.githubusercontent.com/assets/19594338/20083122/7d906410-a595-11e6-9271-b9ff6ddc6602.png)
知道这个是什么软件吗？右边蓝色的按键提示。
@GregAMO

**Comment by xiwc** [comment]
## 分享本人上学时编写的一个类QQ轻量级绿色截图工具(size:160kb)

这里下载: [QQPrintScreen.zip](https://github.com/liulex/Snipaste-Feedback/files/678133/QQPrintScreen.zip)
或者51CTO下载: http://down.51cto.com/data/268364

![image](https://cloud.githubusercontent.com/assets/8816203/21558313/caf4d046-ce72-11e6-9177-6b6a59d472e3.png)

![image](https://cloud.githubusercontent.com/assets/8816203/21558302/90e9e99a-ce72-11e6-8fb2-ad2c6aee98a2.png)
