### ISSUE TITLE
feature: 增加网页滚动截图、增加gif截图、增加文字的二次编辑功能

### ISSUE THREAD

**Issue by lxshui** [liulex/Snipaste-Feedback#216]
要是有这些功能就完美啦！作者加油

**Comment by GregAMO** [comment]
网页截图 See #19 
Gif 截图 这啥？？请补充描述
二次编辑 See #211 作者说「二次编辑以后会对所有形状一次性支持。」
善用搜索，Snipaste 是贴图软件，谢谢
