### ISSUE TITLE
希望能够增加画笔的透明度选项

### ISSUE THREAD

**Issue by lfk0** [liulex/Snipaste-Feedback#217]
在临时涂鸦的时候希望有一个透明度的选项，可以允许以自定义透明度在截图上面做标注
谢谢！

**Comment by GregAMO** [comment]
![image](https://cloud.githubusercontent.com/assets/20766212/20082129/e63465fe-a58e-11e6-9d0c-167b71fdd767.png)
已存在这个功能，修改图示 Alpha 通道的数值即可
