### ISSUE TITLE
滚动截屏的支持

### ISSUE THREAD

**Issue by ksco** [liulex/Snipaste-Feedback#22]
比如在 Windows 的 Explorer 里面可以滚动截取文件(夹)列表。

感觉有难度，但偶尔会有这种需求。

> :smile: 感谢作者的付出，用过的最好用的截图软件，早日出 Mac 版。

**Comment by liulex** [comment]
重复 issue: #19

**Comment by CNsoldier** [comment]
重复问题：#19，支持添加滚动截屏

**Comment by sli11111** [comment]
连长图都截不了，我每次都得打开qq截图
