### ISSUE TITLE
支持 WSL 和 WSA

### ISSUE THREAD

**Issue by ivysrono** [liulex/Snipaste-Feedback#2249]
### 功能描述

现在已经可以完美在WSA上运行微信QQ等聊天工具，碰到的最大障碍就是截图无法直接贴入，不知能否支持。

**Comment by Lemmingh** [comment]
[^1]: 在 Android 中，除了文本 (text)，数据无法直接放进 Clipboard，需要通过 [content provider](<https://developer.android.com/guide/topics/providers/content-providers>) `Uri`，而 content provider 是 Android app 中的概念。

这恐怕已经超出了 Snipaste 的范畴。

Snipaste 向 [Windows Clipboard](<https://docs.microsoft.com/en-us/windows/win32/dataxchg/clipboard>) 中写入数据。

Windows Clipboard 到 [Android Clipboard](<https://developer.android.com/guide/topics/text/copy-paste>) 的同步是 **WSA 自己的问题**。 [^1]

鉴于现在 WSA 的 Clipboard 同步仍然不太稳定，而且里面有很多难点，我建议你慢慢等消息：

* <https://docs.microsoft.com/en-us/windows/android/wsa/release-notes>

* <https://blogs.windows.com/windows-insider/posts/>
