### ISSUE TITLE
Snipaste启动及更新问题

### ISSUE THREAD

**Issue by heyggu** [liulex/Snipaste-Feedback#226]
**问题描述/建议描述**

1.程序不能自启动，每次设置开机启动后，手动打开后，开机启动设置又被取消；

2.手动启动后，显示“错误：无法写入config.ini.所有设置将使用默认设置”；

3.程序不能自动更新。

以上几个问题困扰我好久了，每次程序启动和更新我都是手动解决了。

![snipaste20161116_154601](https://cloud.githubusercontent.com/assets/10350698/20338790/12fab26a-ac14-11e6-80c1-e36df53f5757.png)
![snipaste20161116_154140](https://cloud.githubusercontent.com/assets/10350698/20338801/1b8c6108-ac14-11e6-8d85-5e7e6650a95e.png)

**运行环境**

操作系统：Windows 10 64位
Snipaste 版本： 1.9.2

**可能相关的 Snipaste 设置**

未修改任何参数设置。

**Comment by GregAMO** [comment]
咦…可以看GitHub wiki 的故障排除啊，你找到写 config.ini 的那一条
主要就是Snipaste 没获得那个路径的读写权限…

**Comment by heyggu** [comment]
感谢指点 ,是我疏忽了.
