### ISSUE TITLE
滚轮与拖动边缘缩放逻辑不一致

### ISSUE THREAD

**Issue by WindSpiritSR** [liulex/Snipaste-Feedback#2264]
### 联系方式

simon343riley@gmail.com

### 发生了什么？

1. 截取一张小图，例如 100px x 100px
2. 使用滚轮放大，最大允许 1000%
3. 拖动边缘放大时，缩放无限制
4. 再次使用滚轮缩放，跳回最大 1000% 缩放比例

### 运行平台

Windows 桌面

### 软件版本

2.7.3-Beta (2022.02.09)

**Comment by liulex** [comment]
这个是特意这么设定的，滚轮为快捷缩放，如有需要可以用边缘缩放突破滚轮缩放的大小限制。
