### ISSUE TITLE
画笔工具栏在画图时遮挡截图部分

### ISSUE THREAD

**Issue by thomasmolover** [liulex/Snipaste-Feedback#228]
截图后的绘图工具栏在截图区域右下角，在截取的屏幕图下边贴近屏幕下沿时，如需要绘图的位置在图形右下，其工具栏并不会自动避让，使得截图右下部分不能绘图。

**Comment by GregAMO** [comment]
解决：贴图以后移动位置，离开屏幕下边缘。
事实上推荐贴图再编辑，这样软件会视为成功的截图
并自动保存各种操作，尽量防止意外丢失。

解释：总要放一个位置，一般默认下边缘。
如果下边缘贴边而上边缘没贴边，会跑到上边缘。

**Comment by liulex** [comment]
@thomasmolover 
感谢注意到了这个细节，[下一版](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97)已经改善了，请静待发布。

也正如 @GregAMO 所说，有些情况是无论如何都会挡住的，这时可以先贴图再编辑。

**Comment by thomasmolover** [comment]
从某个角度来看，逻辑其实并不冲突。
正在绘图时，光标就是个画笔，不应画到“调色板”上，而确认落笔完毕，画完了，光标变成常规指针，就可以在工具栏选取工具。
当然，这样判断也失去了直接点选的便捷性。
鱼与熊掌嘛。。。。
