### ISSUE TITLE
[Feature Request] 关于绘制直线/折线的操作

### ISSUE THREAD

**Issue by taroxd** [liulex/Snipaste-Feedback#229]
1. 希望不要合并绘制直线和绘制折线的操作。
首先直线是比折线更常用的一个操作，如果有专门绘制直线的方式的话，只需要一次拖拽或者两次左键点击即可画出一条直线。
而现在的操作需要两次左键和一次右键，既不自然，也增加了操作的复杂性。
其次，用折线画直线的图标也不直观。
说实话，哪怕把画折线的功能简化成画直线，我都觉得比现在这样操作要舒服。
P.S. 我用到现在还没有画过一次非直线的折线，但是直线倒是画过很多次了。

2. 希望按住 Shift 时可以画出水平/竖直的直线/折线。

**Comment by liulex** [comment]
首先，我承认直线比折线更常用。

但是，折线功能要不要有？要，因为我就需要，而且应该也不只我需要。

* 既然直线和折线都需要，那是否两个都保留？

  我觉得不应该，毕竟直线可以画折线，折线也可以画直线，两个都放上去很多余。

* 那么，保留哪个的画法？

 诚然，折线的画法，操作要多一些。

 直线的画法，就是现在记号笔的画法，一次鼠标点击即可。

  但是，用直线来画折线，有多麻烦，还是很容易想象的吧。一是要手动对准，二是当需要调整其中某个点，以及整体移动，会非常不方便。

  这是远比用折线画折线麻烦的。

以上是我只保留折线的原因。

至于各个形状的 Shift 功能，会陆续添加的。

**Comment by liulex** [comment]
不过或许可以试试把两种画法合并一下，鼠标按下后有移动，就进入画直线模式……

**Comment by liulex** [comment]
实现了一下，似乎效果还不错 :smile:
![](https://cloud.githubusercontent.com/assets/2010459/20390483/1019655e-ad0a-11e6-9ba3-7e9bd69ff682.gif)

**Comment by taroxd** [comment]
本意是说直线和折线分开，也不至于只保留一个……

不过这实现方式听上去还不错
