### ISSUE TITLE
建议：在指定进程中禁用快捷键

### ISSUE THREAD

**Issue by uicake** [liulex/Snipaste-Feedback#230]
打一些游戏时，在紧要关头按F1发大招准备横扫千军的时候，突然跳出个截图，完美阻碍了发招机会，至于······
所以啊，给snipaste添加个功能，在指定进程中，snipaste的一堆快捷键都被禁用掉。

**Comment by taroxd** [comment]
@uicake 建议使用和其他软件都不冲突的快捷键？

**Comment by uicake** [comment]
@taroxd 不同的游戏有不同的快捷键，且一般游戏都自带截图功能，或我直接用steam的截图功能，改快捷键还会影响平常的使用，所以得添这个功能（SAOutils就是这么干的）。
    其实本来我有设想再写个增加类似专业游戏截图软件的功能，但我构思的我自己觉得不是很普遍地适合方方面面的人，就删掉了。若有人能构思得很合理的话，也可以提出来，以帮助改进。
    顺便吧，再写一遍：
    在指定进程中只启用一个用于截图的快捷键，在该快捷键启动的截图界面的工具栏里增添一个“可即时更改该快捷键的工具（功能）”，因为有些全屏游戏中切到桌面（然后到任务栏里找到snipaste图标，再右键打开“首选项”，再找到快捷键来更改）很麻烦，甚至有些游戏（如上古卷轴5）切到桌面就会出现一些奇奇怪怪的问题导致游戏无法正常进行（两个鼠标烦死你）。

**Comment by GregAMO** [comment]
@uicake 参见 #171 手动暂停热键
和#160 程序黑名单 
都有相关讨论哒

**Comment by uicake** [comment]
所以现在还是没有这个功能咯......关于重复问题，由于关键词不一样，我也没办法，在发之前我有搜过各种关键词。。。除非作者提供一个《未实现的功能计划表》。。。

**Comment by liulex** [comment]
@uicake 感谢详细的描述。
因为检测进程名称会涉及权限问题，不好统一处理，所以 指定进程自动禁用 大概不会做。
以后会提供禁用所有快捷键的快捷键，至于只禁用除截图外的快捷键的话，不会做，你可以自己再创建一个快捷方式来调用截图。

现在的 issue 确实比较乱，你的建议《未实现的功能计划表》不错，我有时间再整理一下吧。

**Comment by septs** [comment]
@uicake 现阶段可参见 https://github.com/liulex/Snipaste-Feedback/milestones

**Comment by xhzwxhz** [comment]
很多编辑器和IDE都有F1，F2，F3的快捷键，有时候F3寻找下一个，一通猛按没反应，才发现原来是snipaste的锅。只能关掉，用的时候再开。

**Comment by candywzt** [comment]
可以加一个全屏状态下禁用快捷键的开关
