### ISSUE TITLE
建议加入的功能，作者可参考nullice

### ISSUE THREAD

**Issue by Blue-Jing** [liulex/Snipaste-Feedback#231]
nullice不知冰语的
[Loxclip · 液切 ](http://nullice.com/loxclip-2)
值得借鉴！！！！

**Comment by septs** [comment]
请明确指明需求细节

**Comment by GregAMO** [comment]
试了试液切，估计可以合并到这个问题 #78 ，其中提到：
> 图片粘贴为文件会加入
