### ISSUE TITLE
在开启 Snipaste 的情况下接入第二个显示器，截图时只能截第一个显示器内容

### ISSUE THREAD

**Issue by oopp1800** [liulex/Snipaste-Feedback#233]
如题，
因为我的电脑的问题..开机监测不到第二个显示器，每次都要重新设置
但是 Snipaste 是设置自动启动的
所以会导致截图时不能截第二个显示器...

希望作者能解决这个问题
（如果能解决我电脑的问题就更好了2333

**Comment by xintiandi** [comment]
我之前也遇到了这样的问题，
有些问题是偶然也不好反馈，我出现过截图远程桌面窗口后，截图声音一直播放不停止的情况，按f1截图时，第一次有时会出现自动取消的情况，又要重新去按f1，因为没有规律，就没有反馈。

**Comment by liulex** [comment]
@oopp1800 我会测试看看能否处理屏幕有变化的情况。
@xintiandi 不正常的行为都可以报 bug，不能完全重现也可以先报着，其他有相同经历的用户看到 issue 会提供额外的信息，我也会从代码的角度看看能否找出原因。

截图自动取消的情况应该是有其他程序的窗口被激活了，如果这种事经常发生的话，你可以到 `首选项` - `截图` - `行为` - 取消勾选"截图时如有其他程序窗口被激活，自动退出截图"。

**Comment by xufun** [comment]
我也遇到类似问题。我用的是 Windows 7 x64 系统。

在我的机器上，该问题的稳定重现方法为：在第二显示器接入情况下（扩展屏），退出Snipaste，然后直接拔掉显示器HDMI接口，再启动Snipaste，接入显示器（此时显示器会自动进入扩展屏模式）。在这种状态下使用Snipaste无法截取第二显示器的内容；此外，如果将贴图放在第二显示器上，在贴图上点击右键，菜单会呈现在主显示器边缘。如果此后先按Windows+P选择“断开投影仪”之后，再Windows+P选择扩展屏，该问题可以消失。

**Comment by liulex** [comment]
@xufun 感谢提供详细描述。
我按照你说的试了下，即拔掉扩展屏，启动 Snipaste，然后接上扩展屏，我这边 Snipaste 可以正常截取第二屏幕……（Windows 10 x64）

不知 @oopp1800 @xintiandi 你们的操作系统是？

**Comment by oopp1800** [comment]
@liulex 
我的操作系统同样是 Windows 10 x64 的，现在没在电脑旁，晚上回去再测试下能否稳定重现~

**Comment by oopp1800** [comment]
今天尝试了多次都是可以正常截取的...不知道是不是偶然的问题...

**Comment by xufun** [comment]
我刚刚在另一台 Windows 7 x64 电脑上也试了能完全复现。看来可能是 win 7 的 bug……看看还有没有其他人反馈吧，现在反正可以通过多按两次Windows+P来解决……

**Comment by liulex** [comment]
方便留个联系方式吗（发送到 <snipaste.app@gmail.com>）？我找你测试下……

**Comment by liulex** [comment]
感谢 @xufun 协助测试，问题已修复。

**Comment by xintiandi** [comment]
@liulex 之前我也是在win7 64位下出现的。现在换电脑了。用的win10 x64，因为之前的vga显示器还没有来得及换成hdmi，现在没有接扩展屏，暂时没有测试到。

**Comment by JosanSun** [comment]
我也是这样的情况。
----
场景重现
首先，我打开snipaste。然后，同时接入新的显示器，然后截图的话，只能截图第一个显示器。

解决方案
---
将snipaste退出，然后重新启动就能正常截图。

**Comment by HKMV** [comment]
21年 mac版本依旧有这个问题 版本2.6.5-Beta(2021.08.04)

**Comment by chenlangping** [comment]
> 21年 mac版本依旧有这个问题 版本2.6.5-Beta(2021.08.04)

相同的问题，M1版本的mbp13  每次都需要关掉Snipaste，再重新启动才可以

**Comment by HKMV** [comment]
> > 21年 mac版本依旧有这个问题 版本2.6.5-Beta(2021.08.04)
> 
> 相同的问题，M1版本的mbp13 每次都需要关掉Snipaste，再重新启动才可以

怎没想到16年issue的问题,到现在2021年竟然还会存在.

**Comment by HKMV** [comment]
> > 21年 mac版本依旧有这个问题 版本2.6.5-Beta(2021.08.04)
> 
> 相同的问题，M1版本的mbp13 每次都需要关掉Snipaste，再重新启动才可以

最新测试版更新提示已经修复

**Comment by jiangsang** [comment]
Win10，该问题仍旧存在，版本：2.7.1-beta，电脑休眠再打开的，无法截取显示器的屏幕，重启Snipaste解决

**Comment by HealUP** [comment]
> @xufun 感谢提供详细描述。 我按照你说的试了下，即拔掉扩展屏，启动 Snipaste，然后接上扩展屏，我这边 Snipaste 可以正常截取第二屏幕……（Windows 10 x64）
> 
> 不知 @oopp1800 @xintiandi 你们的操作系统是？

perfect!

**Comment by sino1641** [comment]
2025年，仍存在该问题。
win11 24h2，笔记本+HDMI双屏，每次热插拔之后都需要重启snipaste才能根据鼠标位置截取对应的屏幕。

**Comment by liulex** [comment]
@sino1641 这个问题本质是 Qt 的 bug，并且与 **特定外接屏幕型号** 或 **特定 HDMI 线材** 有关。另外，虽然不同用户表现出来的问题类似，但实际可能是几个不同的根因。
我使用 HDMI 线+笔记本外接屏无法复现，所以我能做的只有尽量同步 Qt 官方相关的 bug fix，但问题依旧没有根本解决。

**Comment by liulex** [comment]
如果有用户觉得这个问题烦不胜烦，希望彻底解决，可以尝试更换 HDMI 线或者更换另一个不同型号的显示器，看问题是否解决。

如果测试后发现是仅跟 HDMI 线有关，请再找一台电脑测试，确认的确是线材问题；
同理，如果测试后发现仅跟显示器型号有关，也请将显示器接入到另一台电脑，确认还能复现；
如果是跟线材和显示器型号都有关，也请用另一台电脑再测试下。

最后，将测试结果贴在这里，等待其他用户印证。

只要提供了可复现的条件，我可以保证该问题能被解决。

**Comment by rain-0** [comment]
<img width="1425" height="815" alt="Image" src="https://github.com/user-attachments/assets/9815fa99-8317-4401-951b-cd717217d6a7" />当屏幕排列是左右的，可以正常识别到2号屏，当屏幕排列是上下时，则无法正常在2号屏截图

<img width="1344" height="500" alt="Image" src="https://github.com/user-attachments/assets/76dabbab-8397-47a2-9948-2e6d39f26fe0" />

**Comment by liulex** [comment]
Snipaste 2.11 已经修复了。
