### ISSUE TITLE
在无法检测到窗口元素的截图中，矩形模糊等行为选中了整个背景

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#235]
bug重现步骤：
1、在桌面空白地方某块区域截图
2、选中 马赛克/模糊
3、在截图中点击右键
4、结果模糊的结果不是截图区域，而是扩展到了整个桌面背景
5、选择矩形，橢圆进行右键点击，效果类似，同样选择了桌面背景

**Comment by liulex** [comment]
好的，元素大于截屏区域的时候将不自动标注元素。
