### ISSUE TITLE
可不可以让命令行参数支持直接保存截图到指定文件夹并指定截图文件名

### ISSUE THREAD

**Issue by saccohuo** [liulex/Snipaste-Feedback#236]
今天刚看到新版本支持了一些命令行参数，很感谢作者的付出。

虽然知道以后命令行参数可以增加，但是不知道有没有考虑这种操作方式。

使用命令行参数指定文件夹和文件名（字符串形式），在截图之后自动按照参数保存。这样可以与其他软件更好地配合。

应用场景：其他软件提供命令行参数，调用 Snipaste，截图并保存到指定文件夹。

**Comment by liulex** [comment]
这种参数是有考虑的，但应该只限于无界面自动根据参数截图吧？
毕竟如果调出了截图界面，将截图保存在哪里就由此时的用户决定了。

**Comment by saccohuo** [comment]
我觉得可以像ShareX那样有一个截图完成的按钮，这样在截图完成时可以按照命令行中给出的workflow进行操作，不过这样的话逻辑似乎要重新捋一下了
