### ISSUE TITLE
[请求新功能]添加阴影半透明背景

### ISSUE THREAD

**Issue by copriwolf** [liulex/Snipaste-Feedback#237]
# 请求新功能
希望为每个截图背后提供一个可选的半透明阴影背景，如`mac`的系统自带截图以及Win上的`WinSnap`软件。

## 为什么
因为这个功能比较实用，特别是添加在md文件或者是ppt讲稿的时候，有背景阴影能够比较好的区分图片与文字，同时起了强调和美观优雅的作用。

## 如何做
应该是加一层透明度不为100的线条，然后保存在png图片，具体原理因为不清楚也不能说明

## 效果
如图所示。
![](https://ws2.sinaimg.cn/large/5eb485dagw1fa13mpb90uj20r90lcn25.jpg)

## 最后
我很喜欢你们的软件，很强大很好，这是完美中的一个小完善，谢谢你们开发了这么好的软件，加油~

**Comment by GregAMO** [comment]
作者在 #197 提到：
> 以后交给插件系统，包括添加外围阴影。

**Comment by liulex** [comment]
@copriwolf 感谢你的详细描述。
这个功能是一开始就打算做的，但因为不同用户会需要不同的阴影样式，需要给一些选项，所以交给以后的插件系统比较合适哈。

**Comment by copriwolf** [comment]
请问什么时候能够实现呢？因为今天看到Snipaste有新版本上，但是看日志是常规更新

**Comment by liulex** [comment]
如果在贴图上加一个“带阴影保存”是很快的，但你们似乎都是想截图的时候就自动加阴影，这个要涉及的选项和交互就麻烦很多了……

**Comment by GregAMO** [comment]
@liulex 看了两边的图例，感觉是：
输出的时候带边框
包括输出为文件和输出到剪贴板

**Comment by copriwolf** [comment]
@liulex 
Winsnap64的实现原理是先截图，然后最后到了编辑模式的时候再选择是否加阴影的。不妨先做一个简单的实现哈哈哈~加油
![](https://ws2.sinaimg.cn/large/5eb485dagw1fa39n41ztvj21bt0m9wiu.jpg)
