### ISSUE TITLE
工具栏放置问题并没有彻底解决

### ISSUE THREAD

**Issue by thomasmolover** [liulex/Snipaste-Feedback#238]
工具栏还是固定在右下角，如果截图范围贴近屏幕下端就不能以右下角工具栏区域开始绘图

即使截图范围并不靠近屏幕右侧，工具栏仍在截图区域内。建议工具栏放置在截图范围外部。

建议一个逻辑系统，设计两个工具栏放置点，例如左下、右下。如果点击了工具栏上工具开始绘图模式，工具栏就开启“躲避”模式，鼠标靠近就跳到另一个放置点，直至点击esc或鼠标右键绘图完成，工具栏就退出躲避模式

**Comment by liulex** [comment]
给个动图看看？
目前是会躲避的，只有在你的截图区域既贴近屏幕上边缘又贴近下边缘，躲无可躲了，工具条才会出现在区域之内。
至于把工具条放在截图区域的左边或右边，抱歉，不考虑这样做。

**Comment by thomasmolover** [comment]
http://p1.bpimg.com/1949/2faed202192e1537.gif

上传了一下

**Comment by liulex** [comment]
。。请让我看到整个截图区域好吗，以及能看出截图区域在屏幕中的位置。

**Comment by thomasmolover** [comment]
http://p1.bpimg.com/1949/0cdfa06e0b749cfb.gif

这是全屏的
啊！好大

**Comment by liulex** [comment]
正如我所说的，你这种情况是属于向上向下都躲无可躲的情况……
但实际上这种情况是比较极端的，日常截图很少会遭遇，所以我一开始就不打算处理，毕竟真遇到这种情况的时候，先把截图区域贴出来，再编辑就 ok 了。

不过，你提出的方案似乎也有可行性，我刚刚实现了一下，但实际出来体验不太好：
（只有工具条出现在了绘图区域内，才有躲避行为）
结束躲避的条件，如果是右键绘图完成，那么在完成之前，用户无法通过当工具条调整当前标注的画笔，这是不方便的。
所以开始躲避的时机应该是鼠标左键按下，结束躲避的时机应该是鼠标左键松开。
这就带来了一个问题，就是用户在标注的时候，工具条可能会频繁地消失和出现……
除此之外，鼠标松开的时候，标注的图案有可能完全躲在了工具条后面而无法再调整……
还有其他的一些特殊情况……

总之，这种“智能躲避”的逻辑并不是想象的那么简单的，体验也没有想象中的那么好，我觉得加上是没有必要的。当遇到了被挡住的情况，先贴出来，一了百了……

**Comment by thomasmolover** [comment]
绘图的时候，可以设置快捷键，有的 issue 提出直线正交什么的，其实可以一起考虑，毕竟绘图功能开启时，是不需要其他一些快捷键的功能的，这就给一键多用提供了可行性。例如，wasd，截图时操作截图区域，但在绘图模式时可以释放，设置a为锚定工具栏，就是按着a就不会躲避，还可以用这个机制设置快捷键选择工具栏功能。

**Comment by GregAMO** [comment]
逐条回复吧，基本上对照「内置快捷键列表」
> 绘图的时候，可以设置快捷键

参照「列表」，事实上 Snipaste 并没有一个独立的“绘图状态”
只有截屏、贴图，这两个独立状态。而按空格键打开工具栏是一个通用快捷键。

> 有的 issue 提出直线正交什么的……

不知你说的是不是#204 已经在[1.10.0](https://github.com/liulex/Snipaste-Feedback/wiki/更新日志)实现：全部标注形状支持 `Shift` 功能

> ……这就给一键多用提供了可行性。

软件内的一键多用很容易混乱……目前除了 `ESC` 这个通用退出键，没有复用的按键。

> 例如，wasd，截图时操作截图区域，但在绘图模式时可以释放……

参见「列表」，wasd 目前是一个通用快捷键。
***
总的来说，你似乎希望 Snipaste 有一个独立的“绘图状态”，
而目前 Snipaste 的工具栏被设计为一个随时取用的小工具，融合在截屏贴图两大使用状态里。

另外是似乎喜欢确定截图区域以后，立刻开始标注图片，是因为当作演示画笔了吗？
强烈推荐按中键转化为贴图以后标注图片。
**Snipaste 是一款贴图软件**
贴图会被 Snipaste 完整地记录下来，不容易被其他突发性事件破坏辛苦的标注成果。
贴图更容易掌控，包括缩放大小、移动位置、与其他贴图无缝拼合。
