### ISSUE TITLE
自定义贴图透明通道显示效果

### ISSUE THREAD

**Issue by fzmo** [liulex/Snipaste-Feedback#239]
如题，当我复制一张 png 格式的透明图片，然后快捷键贴图，图片就会出现在屏幕中间且无法进行操作。并且关闭软件并且重新打开，贴图依旧会在。

p.s.两次按贴图快捷键贴图才会消失；
p.s.并没有开点击穿透 

..p.s... 希望可以添加转换的透明效果
以上

**Comment by GregAMO** [comment]
你的描述之中只有：
> 无法进行操作

这一项似乎是 Bug，其他都是正常的。
> 两次按贴图快捷键贴图才会消失

可能和 「首选项 - 贴图 - 行为 - 贴图闪烁时，按下贴图键隐藏所有贴图」有关？
> 转换的透明效果 

调整整个贴图的透明度吗？
如果是，请查看内置快捷键列表 - 只对贴图有效

**Comment by liulex** [comment]
@fzmo 
这不是 bug，图片透明的部分，自然是无法点击的。
所以贴出全透明的图片，整张图片都无法点击。但是边缘的阴影部分是可以点击的（包括点出右键菜单），如果你有开贴图的窗口阴影的话。
如果没有开窗口阴影……那你只能关闭 Snipaste 然后从 history 文件夹中找到那张图片删掉再重开 Snipaste 才能把它从屏幕中去掉了，或者通过关闭贴图组也行。

至于替换透明效果，会考虑加这个选项的。在那之前，图片是怎样的，贴出来就是怎样，这是可以预期的，所以并不是 bug。
