### ISSUE TITLE
对SmartGit部分区域选择时崩溃

### ISSUE THREAD

**Issue by G-monitor** [liulex/Snipaste-Feedback#24]
Snipaste 64位 1.4(2016.08.01)
SmartGit 7.1.4 #6127, installed: #6119 （应该是指最新版本6127，当前使用版本6119
系统版本：Windows 10 专业版 1607
OS 版本： 14393.10

自动对齐主窗体右下角Output区域时崩溃
尝试多次每次都会崩溃（如图区域）
![image](https://cloud.githubusercontent.com/assets/11240579/17410962/a1aa5b2c-5aa8-11e6-9b56-d2f7593c2ed3.png)

**Comment by liulex** [comment]
非常感谢协助调试，导致崩溃的 bug 已修复。
