### ISSUE TITLE
程序以管理员身份启动，无法响应命令行调用

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#240]
首选项中勾选以管理员身份开机启动，发现其无法响应命令行调用。
后面调试确定，关掉程序，右键点击程序以管理员身份运行，也同样无法响应命令行。
而鼠标左键双击启动的Snipaste，则可以响应命令行调用。
附测试用的命令行：
E:\Software\Snipaste\Snipaste.exe --snip-full
E:\Software\Snipaste\Snipaste.exe --paste-files "C:\Snipaste贴图\test.png"

OS版本为：win10 x64 pro 1607
Snipaste版本为：1.10.1

**Comment by liulex** [comment]
感谢反馈。
确实如此，似乎需要命令行也同样以管理员身份运行才行，我试试是否有办法解决……
