### ISSUE TITLE
[new feature]增加按比例控制截图范围的功能

### ISSUE THREAD

**Issue by steven-ren** [liulex/Snipaste-Feedback#241]
snipaste是我用过的最好用的截图与贴图工具。

功能需求描述：
有时候需要截取两个图片长宽同样比例的图片，但是，两个图片的长宽的长度是不一样的，这时，使用snipaste只能保证截图两个图是一样大小的。如果两个图片的比例不一样，在放入其他文档中编辑的时候，会很不方便。

使用方法：
使用shift + 鼠标在角的拖拽，改变图片比例。

目的：
增加图片的可编辑性。

**Comment by GregAMO** [comment]
@steven-ren 和#198 相似，那边是需要使用给定比例，作者已经打上feature 标签啦
感谢你的详细描述和建议使用方法
