### ISSUE TITLE
开机启动点击检查更新后，界面无响应

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#242]
![image](https://cloud.githubusercontent.com/assets/2637718/20611998/c4fe0962-b2ef-11e6-824d-2913554da75e.png)

bug只发生在开机自动启动的 Snipaste，且 **不** 勾选以管理员身份启动。
若勾选了以管理员身份启动，则不会发生此bug。

bug重现步骤：
1、开机后Snipatse自动启动，稍等片刻即右键点击托盘图标 检查更新...
2、但过了许久也不会弹出 没有可用的更新 的提示框
3、右键点击托盘图标 首选项，可打开首选项界面，但无法点击其内任一按钮，也无法关闭界面
4、但右键点击托盘图标 截图，却 **可以** 进入截图状态
5、右键点击托盘图标 退出，程序退出。
6、重新鼠标双击，或右键以管理员启动程序，上述bug不再出现，仅发生在开机自动启动的程序实例。

附动态图：
[http://p1.bqimg.com/1949/6ff4343d29cc7e65.gif](http://p1.bqimg.com/1949/6ff4343d29cc7e65.gif)

OS版本：win10 x64 pro 1607
Snipaste版本：1.10.1

**Comment by liulex** [comment]
非常感谢，很精准的描述 :thumbsup:

**Comment by toryln** [comment]
忘记说了，开机启动的Snipaste，在首选项中更新页，点击检查更新按钮，也一样会导致界面无响应。
应该是同一个问题，作者修复时可以顺便验证一下

**Comment by liulex** [comment]
嗯，原因找到了……
“无可用更新”那个对话框实际是弹出来了，但被最小化了，而它又没有任务栏图标，所以屏幕上就找不到了……
它又是个模态对话框，所以不关掉它，其他界面就无法点击。
但实际上我并没有让它最小化，像是个 Qt 的 bug.
而它又只在开机启动的那个实例里会自动最小化，所以我无法单步调试看问题出在哪里……
虽然找不到根源，不过 workaround 还是试出来了，下版本修复。
