### ISSUE TITLE
Win10无法设置开机启动，也无法以管理员模式运行

### ISSUE THREAD

**Issue by csxo** [liulex/Snipaste-Feedback#2420]
### 问题描述

现象：
Win10无法设置开机启动，也无法以管理员模式运行。

症状：
点击开机启动按钮时，右下角任务栏箭头会闪一下，但是设置没有生效。

[截图](https://user-images.githubusercontent.com/12461602/206828983-9e2e7e1a-238f-4268-a67c-699cdd6f63ea.png)

日志：
Failed to create a shortcut in the startup directory: C:\Users\***\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup\Snipaste.lnk

版本：
2.8.2 Beta（2022.12.02）

### 运行平台

Windows 桌面

### 软件版本

2.8.2 Beta（2022.12.02）

**Comment by Geeyun-JY3** [comment]
先试试：docs.snipaste.com/zh-cn/troubleshooting?id=开机启动失效
