### ISSUE TITLE
[BUG] 设定自动启动时多实例运行

### ISSUE THREAD

**Issue by thomasmolover** [liulex/Snipaste-Feedback#243]
因各种原因，一个设置在启动快捷方式运行，一个在注册表启动项，启动后就有两个进程

此bug有时有有时没有

**Comment by liulex** [comment]
Snipaste 判断多实例是跟软件版本以及路径有关系的，所以如果你启动的两个 Snipaste 不是同一个 exe，是可以同时存在的。

建议不要自行增加注册表的启动项。

**Comment by toryln** [comment]
根据我的测试，Snipaste多实例对路径判断是大小写敏感的
比如在 .bat 中的如下两个命令：
**D:\Snipaste\Snipaste.exe** --paste-files D:\111.png
**d:\snipaste\snipaste.exe** --paste-files D:\111.png
将会导致两个Snipaste.exe实例运行，楼主可以看看是否跟这个有关
@liulex 作者也可以考虑是否要去除大小写敏感，对不了解的用户调用命令行兴许会少一些烦恼

**Comment by liulex** [comment]
目前确实是大小写敏感，因为是直接用的第三方模块，我也是在 @toryln 昨天提 bug 的时候才发现这个问题。
我已在下一版本去掉了版本号的比较，路径也将是大小写无关的。
