### ISSUE TITLE
贴图移动及贴图组操作的一些建议

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#244]
Snipaste 确实是截图贴图及标注图片的完美软件，感谢作者的辛勤付出！
结合最近的使用感受，有几点建议想提出自己的看法，希望作者可以考虑下。

1.  希望贴图也可以响应 AWSD按键 + 鼠标左键按住的操作。
在截图过程中，awsd 可以像素级别移动鼠标，按住左键可以移动截图区域，调整大小。
但在贴图的操作中，awsd只能移动鼠标，按住左键时则不响应，细微移动贴图要通过方向键，调整缩放大小无法以像素级别调整。
平时工作中经常将一些参考图标截图后按中键贴到屏幕，然后调整贴图位置到自己的软件上查看效果，细微调节需要切换到方向键，截图贴图习惯不一致，操作起来不连贯，不是很方便。

2. 按住Shift移动贴图吸附到其他界面时，希望靠近时马上吸附，而不是放掉Shift键后吸附。
QQ截图时的 按住Alt吸附直线 也是即吸附即可见的行为，Snipaste当前则不是很容易能吸附成功。

3. 鼠标滚轮放大缩小贴图时，能否以鼠标指针当前位置来定位？
对于一些较大的贴图，鼠标一滚动缩小了，就无法再继续滚动了，原因是贴图缩写后鼠标指针不在贴图范围内了。印象中作者貌似提过有些顾虑，但这个行为确实有点不爽，还希望可以再多多考虑下 ^.^

4. 经作者之前的提点，最近使用贴图组比较多，确实比较方便，但发现Snipaste目前对贴图组的快捷键较少，希望作者可以添加以下几个快捷键以提升工作时的高逼格，自定义或内置均可：
- 增加一个 关闭当前贴图组所有贴图 的快捷键
- 增加一个 销毁当前贴图组所有贴图 的快捷键
- 增加一个 将当前选中贴图移动到下一个贴图组 的快捷键
- 增加一个 将当前选中贴图移动到上一个贴图组 的快捷键
工作中会以多个贴图组来分类并管理，迫切需要上面几个快捷键，有了的话操作起来会快捷如飞啊，当然要快捷键就不要弹出提示确认框了^.^

诚恳建议，希望作者考虑~~

**Comment by liulex** [comment]
非常感谢你的建议 : )

1. 这个是之前实现上遇到了一些困难，所以就没做。刚刚已经实现好了，下版本会有。
2. 这个其实有做，但实现上还有一些问题，吸附之后如果用户再移动开，又会马上被吸附回去……所有暂时不会放出来。
3. 这个是 Windows 系统的限制导致体验不好，所以也没放出来。具体解释见 #105
4. 这些操作会首先以命令行参数的形式支持，至于绑定到快捷键，就需要以后的专业版来做了（将任意命令行与全局快捷键进行绑定）。

**Comment by toryln** [comment]
不错，期待专业版早日到来！

**Comment by toryln** [comment]
提个疑问，以命令行方式调用Snipaste，按我的经验实现原理应该是分成了几步：
- 开启了一个新的Snipaste实例B
- 新起的Snipaste实例B检测到当前已经有Snipaste实例A运行了，则向A发送命令行参数消息
- A收到B的消息，响应其命令行调用

实际上Snipaste是这样操作的吗？这样是否会有性能问题呢？还请作者多多指教 ^.^

**Comment by ysc3839** [comment]
我认为不会有性能问题

**Comment by liulex** [comment]
@toryln @ysc3839 
你的理解很准确，确实是那三步，具体可参见 [SingleApplication](https://github.com/itay-grudev/SingleApplication)

至于性能问题，你指的是进程启动以及通讯导致的延迟吧？
其实第二个进程并不会像第一个进程那样进行窗口初始化或者读取配置，它一启动就检测自己是否是第一个实例，如果不是，发送完消息后就退出了，所以启动是很快的。
通讯则确实会有延迟，不过这些过程加起来一般也就几十毫秒，影响不大。

当然，以后通过快捷键调用就不会存在这个问题，因为以上两个过程都省掉了。

**Comment by toryln** [comment]
嗯，感谢指教，解了我心中的疑惑。

**Comment by toryln** [comment]
Snipaste对我的工作帮助挺大的，才发现首页有捐赠链接，已捐赠支持，聊表心意。
希望专业版的开发早日提上日程，期待能成为首批专业版用户。哈哈 ^.^

**Comment by liulex** [comment]
@toryln 非常感谢 :+1:
