### ISSUE TITLE
请问, 有开源计划或者合作开发计划么?

### ISSUE THREAD

**Issue by fo2w** [liulex/Snipaste-Feedback#245]
有多平台的开发经验, 希望能贡献自己的力量

**Comment by liulex** [comment]
谢谢你希望提供帮助。
目前不打算全部开源，准备是将 Snipaste 分割成一些小的模块进行开源，如此也能增加它们被重用的机会。
不过最近没有时间去整理代码，有空整理好之后就会放出来的。

**Comment by fo2w** [comment]
感谢回复
最近有一个小工具想重写截图模块，独立出去成一个单独的小程序
需要跨win, osx, linux
很想借鉴一些其中的功能，同时完成跨平台的其他事情
请问现在有合适的合作开发构想么，或者代码授权也行~

**Comment by liulex** [comment]
你好，暂时不需要合作开发。
但截图功能其实也就在 Windows 上比较完善，macOS 和 Linux 都还有好些问题没解决。
如果你是在某个具体功能的实现上遇到了困难，我很乐意帮你解答。

**Comment by lxshui** [comment]
同问何时开源呢大神？？？或者部分开源，就是开源Snipaste.exe文件代码，其他引用库就不用了。
有这个想法是因为我本身也是个程序爱好者，因为自己一些奇葩需求没有得到实现，
比如
1.启动即开始截图（带命令行启动前提得先运行程序本身）
2.截图完退出等等
故而想自己改改程序的启动和退出

**Comment by septs** [comment]
@lxshui 请关注后续的 插件系统 吧

**Comment by lxshui** [comment]
@septs 请问大概何时有插件系统呢

**Comment by septs** [comment]
@liulex 具体细节未知
更多请看 https://github.com/liulex/Snipaste-Feedback/issues/282#issuecomment-268238525

**Comment by JimEverest** [comment]
https://github.com/JimEverest/fastshot
Fastshot is an open-source Python-based screenshot tool for Windows, inspired by Snipaste. It provides a versatile and user-friendly interface for capturing and annotating screenshots, making it ideal for research, reading papers, writing code, and various comparison and demonstration scenarios.

Features
Always on Top: Screenshots stay on top, allowing easy comparison.
Smooth Zoom and Drag: Effortlessly zoom and drag screenshots.
Annotation Tools: Hand-drawing and text mode for annotations.
Clipboard Export: Easily export screenshots to the clipboard.
OCR Integration: Extract text from images using the built-in OCR plugin.
