### ISSUE TITLE
图片镜像反转后,生成的图片右侧偶尔会出现黑边

### ISSUE THREAD

**Issue by VoliBearCat** [liulex/Snipaste-Feedback#248]
图片镜像反转后,生成的图片右侧偶尔会出现黑边
![0hv_i2 h czhp f0xn2h3y](https://cloud.githubusercontent.com/assets/11676384/20657621/4c88fc82-b572-11e6-9dc5-4a2fd4cd5291.jpg)
![9 tkf0s hv88fq82i zfv5h](https://cloud.githubusercontent.com/assets/11676384/20657622/4c90bf3a-b572-11e6-89f2-ef16767e9b2f.png)

**Comment by liulex** [comment]
感谢反馈，测试了下，似乎是跟图片的尺寸有关系……
