### ISSUE TITLE
请问是否可以在截图时将截图区域设置为上几次的区域？

### ISSUE THREAD

**Issue by Chengxi9** [liulex/Snipaste-Feedback#249]
目前截图时按R可将截图区域设置为上一次的区域。也就是只能返回一层。如果能按照逆序返回多次截图的区域会不会更实用。比如按两次R，则返回上上次截图的区域。如果需要设置返回的上限可以是截图的最大历史纪录。希望能增加这个功能

**Comment by liulex** [comment]
好的。

**Comment by baifengs** [comment]
11的更新用了一下，为什么不能循环使用呢。

**Comment by liulex** [comment]
@baifengs 看更新日志，<kbd>Shift</kbd> + <kbd>R</kbd>
