### ISSUE TITLE
BUG：使用鼠标对任意区域进行截图后，松开鼠标左键，截图消失，无法对截图进行编辑。

### ISSUE THREAD

**Issue by steven-ren** [liulex/Snipaste-Feedback#25]
windows 7 enterprise
step1: 使用 "F1"
step2: 使用鼠标左键进行区域选择
step3: 截图消失，也无法使用F2进行贴图。

如果不进行任意区域截图，而是使用程序自带的自动检测界面元素区域，就可对截图进行修改。

**Comment by oxygen16** [comment]
也是这问题，不过自带检测截图后再调整也还是这样

**Comment by liulex** [comment]
请禁用掉词典软件的取词功能。具体解释见：
https://snipaste.gitbooks.io/snipaste/content/zh/problems/windows.html

**Comment by steven-ren** [comment]
说是“禁用掉词典软件的取词功能”是不准确的，经过我的尝试，应该是禁用词典软件的# **划词功能**。

**Comment by liulex** [comment]
我不用那些功能，以为是一个意思……就是时刻检测鼠标拖动的功能。
感谢反馈！
