### ISSUE TITLE
[Feature] 快速/一键截图功能 - 跳过编辑步骤，直接放进剪贴板

### ISSUE THREAD

**Issue by lawrenceching** [liulex/Snipaste-Feedback#252]
### 功能
一键截图，F1截图后直接放到剪贴板。

### 需求
该功能是为了解决在大量截图但不需要编辑的场景。

例如 Dev 或 QA 做测试时，我们需要截取 8~10 张图片作为测试证据），贴到 JIRA 或者文档里。按照现在的模式，我需要 F1 -> 选中区域 -> Ctrl+C，3 步来完成操作。如果我们跳过编辑阶段，那么我每一次都可以剩一步。节约了1/3的时间。

又例如，在出现 Production Issue 时，我们需要跟公司里的各个开发团队以及业务等其他部门在IM上交流。需要非常频繁地截图但是对美观一点要求都没有。但是每次都要 Ctrl+C 实在太繁琐。

### 难度
功能代码都有了，只需要开多一条处理路径。实现难度应该比较小，同时也不会对原有的代码产生太多影响。（希望我没想错）

### 更进一步
Snipaste 是个非常赞的截图工具。功能之全面实在超乎我想象。如果能更进一步提高使用效率，那就更加完美了。

1. 压缩截图时间
大多数适用场景下，我只需要一个图。我不需要微调选择区域不需要标注，也不在乎没不美观。所以我认为截图后的编辑步骤是可以省略的。而在只需要一个图的情况下，大概有一半的情况是我只需要一个窗口截图。如果可以点击F1后，鼠标点击窗口就可以完成截图（2步）；甚至，按下 F1 后，直接截取鼠标悬停的窗口（1步），我就可以完成截图。现在的情况是，我还必须慢慢微调鼠标使之选中窗口（我知道这个可以关闭），效率很低。

Mac 自带的快捷键截图功能在这方面做得非常好，建议参考一下。

2. 强大自定义功能

自古以来被称为神器的工具类应用都是因为极其高效+强大的用户自定义体系。对 Snipaste 来说，可能可以这样：
a) 自定义快捷键打开各种模式的截图（区域、全屏、窗口、延时、滚动）
b) 自定义快捷键输出到剪贴板，文件，HTML，邮件等。
c) 插件
d) 自定义截图流程：如果我可以 F1 截图 -> 添加时间戳 -> 添加公司水印 -> 保存到剪贴板 -> 以 yyyy-MM-dd.png 格式保存到本地。生活简直完美。

如果能做到，那就真的可以成为截图神器了。衷心祝愿越办越好。

---
Ps: 
那个检测窗口元素的功能高级是高级，但是建议默认关闭，一是很少情况下需要这个功能；二是在不同的UI实现上，效果不可预知；三是在界面复杂的情况下实在乱。

在迅雷上，检测窗口元素就只能检测岛迅雷的窗口和某一部分的莫名其妙的白色区域。这种不可控对非IT用户来说，就是功能做得烂...

Pss:
求个单文件 Portable 版

Psss:
Mac版加油！

Thanks and best wish.

**Comment by GregAMO** [comment]
逐条回复：
1 快速截取窗口到剪贴板，你需要：
在首选项 - 截图 - 行为 里关掉自动检测界面元素
鼠标停在你要的窗口，按F1，然后对着窗口双击（见 [基础操作](https://github.com/liulex/Snipaste-Feedback/wiki/基础操作)）

2 
a 见 [命令行选项](https://github.com/liulex/Snipaste-Feedback/wiki/命令行选项)
   其中“滚动”目前还没这个功能。
命令行调用绑定快捷键也需要利用「快捷方式的快捷键」等方式设定。

b 剪贴板 和 文件 目前有快速保存方式，后面两个，贴一下拖拽一下就好了吧

c 见 #250 ：希望引入对 User Script 的支持

d 自定义命名格式有，水印可以使用另一张半透明贴图叠加？时间戳指的是？

Ps 好吧，参见第一条说的设置，还有如果你看了 内置快捷键列表 截图时候 可以按 Tab 切换的
Pss 因为Snipaste 有一些依赖的QT 文件是不需要每次升级的，散开来也是为了加快更新。
目前也是便携式的，整个文件夹带走就好。

**Comment by liulex** [comment]
很赞的描述 :+1: 

关于截图后直接 xxx/自动 xxx，这一类需求会首先以 [命令行选项](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%91%BD%E4%BB%A4%E8%A1%8C%E9%80%89%E9%A1%B9) 的方式进行支持。
当然，这需要把截屏选项和贴图选项结合起来才行，**目前尚未支持**。

```
比如执行：

snipaste.exe --snip-full --paste

即直接截取全屏并贴到屏幕上，甚至都不需要出现截屏界面。

再如：

snipaste.exe --snip 50 100 500 500 --save "C:/screenshots/"

则自动截取指定区域并保存到指定文件夹，也不需要出现截屏界面，想必可以满足你节省时间或批量截图的需求。

或者

snipaste.exe --snip-active-window

则自动选取中当前活动的窗口。
```

至于窗口元素检测的功能默认开启，是因为很多用户都不会改动默认选项，如果不开启，他们甚至不会知道有这个功能……
我知道这个功能其实只在很少的情况下才有用，但如果关掉了，还真不习惯……

至于你说的微调鼠标以选中窗口而非元素，@GregAMO 提过了，使用 <kbd>Tab</kbd> 可以在两种模式之间临时切换。如果你截取窗口比较多，那就默认关掉元素检测，需要的时候用 <kbt>Tab</kbd>.

插件/脚本系统以后会有的。

其他一些问题，参照 @GregAMO 的回答……

感谢你的建议 :smile:

**Comment by lawrenceching** [comment]
@GregAMO 谢谢您的回复。
@liulex 也很谢谢你的建议。
很抱歉没有仔细阅读完文档。

其实的我的建议核心主要有两点。
1. 快！
Snipaste 对各种解决场景都有解决方案，但是不够快。我需要快！快！快！
用户的需求（痛点）除了功能强大之外，其实还有速度。像我这种，日常工作中少则40、50张图，多则100、200张，真是能少按一次少按一次。很多非常精简的截图软件就在操作效率这块做得很好，一次到位。

2. 高度自定义
这个好处不必细说了。例如：
*水印可以使用另一张半透明贴图叠加? 时间戳指?*：自动附加公司LOGO，员工号，截图时间。如果公司信息保密程度高，可以附加隐藏的员工信息。这样图片泄露后可以追溯责任（就像之前阿里的内部信截图曝光后，曝光员工也被开除了）。

同时这些操作明明是可以自动化，明明可以一键完成所有操作，却不得不分开，这就是痛点吧。



现在的Snipaste可以满足低频低强度但是高要求的截图。但是对于高频截图的场景，还有待加强。面对企业用户的话，也还能做得更好。

Anyway，有命令行模式，身为程序员的我其实可以做很多事了。但毕竟对普通用户不友好。

---

坐等专业版。

**Comment by liulex** [comment]
@lawrenceching 
你总结的没错，目前确实还有很多没做的以及可以改进的地方，不过都在计划之中了，缺的只是时间……

**Comment by xintiandi** [comment]
我之前也提到过第一点的快速截图，如果我们希望连续截图，而不推出，一直到按某个键才退出。

**Comment by septs** [comment]
#38

**Comment by akimolll** [comment]
同求这个功能，一键截取整个屏幕（不是手动框选），然后自动保存到目标目录，全程无感。相信做图文教程的人需要这个功能快速截取过程图片，然后去图片保存的文件夹筛选这些图像。而不是每次都手动框选截图，效率低下，工作也会被打断。
