### ISSUE TITLE
复制文字bug

### ISSUE THREAD

**Issue by geek000** [liulex/Snipaste-Feedback#257]
截图后在图片上点击输入文字  然后我剪切板如果有一段文字 假如40个字  此时粘贴 会有一段文字在截图外，不自动换行 并且好像这个输入文字有最大长度- - 具体就是我40个字只显示了20个字 包括超过截图区域的 ，如果此时调整这个文字框的位置 还会在屏幕留下残影

**Comment by liulex** [comment]
不自动换行是故意如此设计的，但是并没有设置最大长度。
如果是文字丢失以及屏幕残影，能否录个动图或视频我看一下？

**Comment by geek000** [comment]
​
看到没 文字后面应该还有字的 没了
其次 文字后面那段残影就如图啦 只要鼠标拖动那个文字框就会出现这情况

2016-12-03 21:43 GMT+08:00 Le Liu <notifications@github.com>:

**Comment by liulex** [comment]
@geek000 没有看到你的附图…

**Comment by geek000** [comment]
![bug](https://cloud.githubusercontent.com/assets/10459206/20960218/53cc9efc-bc9a-11e6-9f63-e2c8690bb933.png)

不好意思 我直接gmail回复的上次 我也不知道啥原因  现在有了吧 = =

**Comment by geek000** [comment]
@liulex

**Comment by septs** [comment]
请回报下显卡全称型号及当前安装驱动版本
如果驱动可更新请尝试更新后再度尝试复现该问题

**Comment by liulex** [comment]
@septs 应该跟显卡没关系
@geek000 残影是因为文字超出文字框了。能否仿照我下面的过程录个动图，我看看是哪个环节出错了。
![12341](https://cloud.githubusercontent.com/assets/2010459/20960772/f4b60ee6-bc9c-11e6-876d-246f92a916ef.gif)

**Comment by geek000** [comment]
@liulex 
![copy text bug](https://cloud.githubusercontent.com/assets/10459206/20967080/7234471e-bcb8-11e6-907c-30859827df0f.gif)

**Comment by liulex** [comment]
@geek000 
不通过粘贴，而是正常打字一直打，会超出文字框吗？
换个字体是否情况依旧？
屏幕 DPI 缩放是？

**Comment by geek000** [comment]
@liulex 
1.粘贴不存在这个问题
2.换了四五个字体 一样必现
3.手动输入英文和 1 一样 不会出现  但是复制粘贴的 必现
4.无缩放 100%

你那边是复现不了吗？

**Comment by liulex** [comment]
@geek000 嗯，我复现不了，似乎也没有其他用户遇到……
我看见你文字框中的文字是偏下的，正常应该是居中的。手打输入的也是偏下的吗？

**Comment by septs** [comment]
@geek000 仍然建议更新显卡驱动后再度尝试

**Comment by septs** [comment]
收回上句 基本确定原因

**Comment by liulex** [comment]
问题已确定并修复。
原因是由 Chrome 浏览器复制得到的富文本包含某些特定格式，Snipaste 没有处理好。
而因为我用的是 Firefox，所以始终无法重现，感谢 @septs 找到问题所在。

**Comment by geek000** [comment]
@liulex @septs 强大 果然如此，我用ff试了下 文字全了 也没有重影了

**Comment by dlsdgj** [comment]
@geek000 这是什么程序?
![snipaste20161209_125317](https://cloud.githubusercontent.com/assets/20112812/21038176/81a29fe6-be0e-11e6-9be7-0ea753a254ed.png)

**Comment by geek000** [comment]
@dlsdgj diigo chrome插件 做笔记用
