### ISSUE TITLE
粘贴后的图不能旋转？

### ISSUE THREAD

**Issue by thomasmolover** [liulex/Snipaste-Feedback#258]
绘图对象可以旋转，而主体贴图不行，这是原设定功能？

**Comment by liulex** [comment]
https://docs.snipaste.com/zh-cn/getting-started#旋转贴图

**Comment by firestarman-james** [comment]
建议将来进一步提供任意角度的自由旋转功能，甚至透视等功能（类似于photoshop的自由变换）。
辛苦啦，谢谢~ @liulex
