### ISSUE TITLE
贴图替换文件为gif后显示为纯透明贴图

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#260]
先贴出一张图，然后拖动gif到贴图，或在贴图右键点 替换为文件，选择一个gif动态图
（该gif要求之前未被Snipaste贴出过），该贴图将会无法显示新的gif动态图，
只显示成一个与目标gif大小一致的纯透明贴图

**Comment by liulex** [comment]
感谢反馈，已修复。
