### ISSUE TITLE
此程序在win8.1下运行失败缺失“api-ms-win-crt-xxx-l1-1-0.dll”导致程序无法运行

### ISSUE THREAD

**Issue by YaoXuanZhi** [liulex/Snipaste-Feedback#262]
Snipaste的作者你好，我想在win8.1的平板电脑上运行Snipaste下载了x32 非xp版本到电脑上，运行时，弹出了这个错误。
![image](https://cloud.githubusercontent.com/assets/14124918/20859016/f6cb8d58-b98d-11e6-9501-e8ef0bea1f81.png)
，后来我到网上将需要补全的.dll全部下载来，放置在Snipaste的目录后，就发现了这个问题
![image](https://cloud.githubusercontent.com/assets/14124918/20859030/4b45637c-b98e-11e6-8555-c2a89d31e7a9.png)，
目前依然无法在win 8.1 x86系统下运行，请问有木有办法解决这个问题呢？

**Comment by septs** [comment]
see https://github.com/liulex/Snipaste-Feedback/wiki/故障排除

**Comment by ysc3839** [comment]
不要去网上下载dll，可能会出现问题。你应该安装运行库。

**Comment by YaoXuanZhi** [comment]
哦，不好意思，没有留意到故障排除这个板块呢，导致问题重复提交了，在此深感抱歉。冏rz
总之，多谢作者大大的耐心解答啦，这样一来，之前xp下无法正常运行的问题也一并解决啦o(*￣︶￣*)o

**Comment by YaoXuanZhi** [comment]
另外，也多些@ysc3839的善意提示啦，之前遇到类似的问题都是手动一个个dll补充上去的，没想到这次这个方法不灵了，所以懵逼了呢o(╯□╰)o。多谢你的提醒啦O(∩_∩)O~~
