### ISSUE TITLE
【需求】希望作者大大可以增加一个gif录像的功能

### ISSUE THREAD

**Issue by YaoXuanZhi** [liulex/Snipaste-Feedback#263]
多谢大大的帮忙，总算可以在win8.1正常使用Snipaste啦，在这里我又要打扰大大啦。
目前我希望Snipaste可以支持git录屏，平时会写一些教程类的文章，所以经常用到gif来演示操作过程；现在我知道有一款开源的跨平台的截图工具，licecap，它可以同时在Windows和Mac下运行，现在正在用来录屏，我觉得将它的录屏功能和Snipaste结合起来将会非常棒；另外貌似网上也有一款免费软件也是基于licecap来实现的，增加了编辑Gif图像的功能，我觉得这个功能也可以考虑一下，这样就可以有效地减少gif的图像大小了O(∩_∩)O~~，希望作者大大可以接纳我的建议，在此也期望Snipaste越来越强大O(∩_∩)O哈哈~

**Comment by septs** [comment]
see #65

**Comment by YaoXuanZhi** [comment]
好的，看来我多次一举啦，多谢耐心解答啦
