### ISSUE TITLE
[建议]希望能在配置项中增加一个启动软件即开始截图的选项

### ISSUE THREAD

**Issue by lxshui** [liulex/Snipaste-Feedback#264]
就像win7系统自带的截图软件那样，启动截图软件即开始截图，无需再一次点击截图。有些用户可能不需要这样的功能，故而希望能在配置中配置是否需要启动即开始截图。
作者加油！

**Comment by Chengxi9** [comment]
这个不是一般开机就启动么

**Comment by GregAMO** [comment]
Snipaste 后台占用很低，同时有展示贴图 记住标注 记住截图历史等功能
推荐后台常驻。尤其是 一些记住历史功能，退出再重启 历史就不在记录了。

**Comment by lxshui** [comment]
呃。。。我都是做了开机启动优化，而且也不是每次开机总会使用截图功能，而且有些强迫症 [#笑哭] ，不用的软件就不想让它留着。。。。所以我没有马上用到的软件我都不会提前开启。所以也就有了用就打开用完就关闭的想法。本来还想跟你说增加配置项“截图完则退出软件，打开软件即开始截图”的....拜托作者加这个配置啦[#卖萌]。

**Comment by lxshui** [comment]
@GregAMO  另外关于历史截图之类功能关掉软件就没有了，想来是把历史数据保存在内存中了。c++我不清楚，但是c#有个内存流是可以直接把内存对象保存到硬盘上的，当然也可以再次读取，如果想关闭软件而历史不丢失，作者可以试试这个内存流。

**Comment by septs** [comment]
@lxshui 
关于第一个问题：
Snipaste 的设计期望是贴图而不是截图
关于第二个问题：
至于历史截图的状态关闭时自动保存这是一个新需求

@liulex

**Comment by liulex** [comment]
抱歉，不会增加此配置项，Snipaste 并不是纯截图软件。
不过，你的需求在日后或许可以通过[命令行选项](https://githuab.com/liulex/Snipaste-Feedback/wiki/%E5%91%BD%E4%BB%A4%E8%A1%8C%E9%80%89%E9%A1%B9)来满足。

历史截图记录是保存到文件（history/snip/*.sp1）而非内存里的。
