### ISSUE TITLE
Android Studio复制代码贴图功能

### ISSUE THREAD

**Issue by LuoDiKaiHua** [liulex/Snipaste-Feedback#266]
在AS下现在复制代码之后没办法进行贴图了... 求修复
Snopaste版本: 1.10.4 和 之前的一个版本都不行
Android Studio版本: v2.2.0.0
系统版本: win10 专业版64bit / win7 旗舰版64bit

**Comment by liulex** [comment]
没法进行贴图是指？

**Comment by LuoDiKaiHua** [comment]
之前复制了一段代码之后可以用富文本的样式进行贴图来着, 上个版本发现不行了

**Comment by LuoDiKaiHua** [comment]
似乎是没有读取到在AndroidStudio中复制的东西, 如果剪贴板上没任何东西就没反应, 否则就是之前在其地方复制的东西进行了贴图

**Comment by liulex** [comment]
那就是你没复制成功吧？
剪贴板没任何东西当然就不会贴出来啊。

**Comment by LuoDiKaiHua** [comment]
我在其他地方能粘贴出来哦

**Comment by liulex** [comment]
那你再试试旧版：https://bitbucket.org/liule/snipaste/downloads

**Comment by LuoDiKaiHua** [comment]
1.10.2可以, 之后的版本不行了

**Comment by liulex** [comment]
好的，那我下载个试试。。

**Comment by liulex** [comment]
已修复，请等待下版本更新。
