### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by wocala** [liulex/Snipaste-Feedback#267]
当前版本：1.10.3
最新版本：1.10.4
系统 win10 version 1607 (OS build 14393.105)
记录：

正在下载...
正在重定向...
正在重定向...
下载完毕.
正在将已下载文件写入到 C:/Users/#####/Dropbox/软件/Snipaste-1.10.1-x64/7f0ede6c-b380-4ce2-a8de-699711a19b66.zip
错误: Failed to open archive file: -1000

**Comment by septs** [comment]
网络原因 请检查网络状况

以及再次尝试更新是否可行 如有问题请尝试通过代理更新 或从 官方下载更新
（代理设置在 Snipaste Preferences 的 Update 页）
