### ISSUE TITLE
Snipaste1.10.4版本在IDEA Intellij(2016.3)和Android Studio(2.2.3)下贴图失败

### ISSUE THREAD

**Issue by L-sizhong** [liulex/Snipaste-Feedback#268]
收到Snipaste更新推送通知，点击升级至1.10.4版本，发现在IDEA Intellij（版本号：2016.3）和Android Studio（版本号：2.2.3）下选中代码，复制，均无法贴图。

在UltraEdit下复制文字，能贴图。
在UltraEdit下复制文字，贴图不包含UltraEdit渲染的格式，只是普通的文本。

**Comment by liulex** [comment]
感谢反馈，该 bug  #266 已经修复，请等待下版本更新。
