### ISSUE TITLE
1.10.4版本无法于贴图之上截图

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#269]
先贴出几张图，然后按快捷键截图，当鼠标移动到贴图上面时，
放大镜不会继续跟随鼠标移动，鼠标指针在 z 轴上会低于贴图，
点击鼠标左键开始截图，结果会响应到贴图的移动操作上面去。

下载了1.10.3版本测试，截图会优先于贴图的鼠标响应，只有1.10.4版本会有此bug

ps: 此bug暂时找不到必现的条件，但发生的概率也不算低，但只要出现了bug，只要不退出Snipaste，
该Snipaste进程就会一直有此bug，现在又遇到一次，将gif放上来备忘下
![bug](https://cloud.githubusercontent.com/assets/2637718/21033490/8b40e4fe-bdeb-11e6-830a-771b0b25a44d.gif)

**Comment by toryln** [comment]
奇怪，刚才一直有问题，现在又正常了

**Comment by liulex** [comment]
我今天也遇到过一次，当时正在调试，以为是编译出错了，就直接重新编译运行了，也确实好了……
现在看来这个 bug 是存在的，只是这个条件不好捉摸。

**Comment by toryln** [comment]
我下载了 1.10.3 和 1.10.2 来测试几次，没有改任何配置，都正常，
然后再次下载 1.10.4 也没改任何配置，测试了两次都有问题，
然后就提交bug了，结果提完再来看看，1.10.4 也没问题了，到现在也没再次出现，我还以为我错觉了...

**Comment by liulex** [comment]
大致上可以确定是 1.10.4 为解决 #233 而导致的 bug.
但仍然只是推测，还是需要找到能引起 bug 的一个确定条件，才能检验是否已经修复……

**Comment by liulex** [comment]
找到重现条件了，比较诡异……
就是 Snipaste 启动过程中如果有任何按键被按下，就会出现这种情况。。
比如按住（或者连续点按） <kbd>→</kbd> 然后双击 Snipaste.exe 启动，这时候截图就会发现问题。
