### ISSUE TITLE
以窗口截屏时，为什么外围有一圈窗口外的图像？

### ISSUE THREAD

**Issue by shanxik** [liulex/Snipaste-Feedback#27]
以窗口截屏时，为什么外围有一圈窗口外的图像？例如对选择文件对话框、Notepad（记事本）截图都有这问题（图片试了两次，都挂不上来）

**Comment by liulex** [comment]
你好，具体原因这里有解释：
https://snipaste.gitbooks.io/snipaste/content/zh/problems/windows.html

**Comment by liulex** [comment]
1.6 版已经修复此问题
