### ISSUE TITLE
1.10.4 无法随系统启动

### ISSUE THREAD

**Issue by moonhome** [liulex/Snipaste-Feedback#270]
虽已设置开机启动，但每次均需要手动启动软件，且取色器 不要复制# 选项每次都需要重新勾选一下

Windows7 64位 旗舰版

**Comment by septs** [comment]
see https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4
