### ISSUE TITLE
开机第一次通过快捷键唤出截屏特别慢，且容易卡死。

### ISSUE THREAD

**Issue by liyu34** [liulex/Snipaste-Feedback#272]
Win10 64位，开机第一次需要截图时通过自定义的快捷键（alt+s）唤出截图特别慢，能卡住30s左右，期间任务栏图标点击无响应。
另外无法截取全屏状态下的游戏，按下快捷键之后游戏画面全黑。

**Comment by ysc3839** [comment]
游戏无法截图是正常的

**Comment by liulex** [comment]
@liyu34 从描述来看，似乎是开机启动后你的网络连接有问题，导致 Snipaste 检查更新卡住了，我设置的网络连接超时就是 30s.
但实际上网络连接是在另一个线程，不应该会卡住截图界面的。不过你可以试试暂时先把启动后检查更新给关掉，然后重启系统试试，看问题是否还存在。如果问题消失了，那应该就是这个原因了，我再检查下代码。

**Comment by liyu34** [comment]
恩，我把自动检测更新关闭之后第一次使用就不会卡住了，最近学校的网络奇差。。。谢谢！

**Comment by liulex** [comment]
@liyu34 我模拟了一下无法连接更新服务器的几种情况，似乎并不会造成截图卡住。
不知能否再提供提供一些信息，比如：
1. 手动检查更新的时候，开始截图，截图是否会卡？
2. 打开自动检测更新的开关，延时设为 0 秒，手动启动 Snipaste，开始截图，是否会卡？
（假设依然无法连接到更新服务器）

**Comment by septs** [comment]
@liyu34 请报告下您当前使用的Snipaste版本

**Comment by liyu34** [comment]
很抱歉回复晚了，这两天比较忙。我的Snipaste是1.10.5(2016.12.10)版本的64位。
手动检测更新的时候确实会卡，卡到检测完毕。
打开自动检测更新的开关并把延时设为0秒之后，手动开启，开始截图，不会卡，这时候手动检查更新开始截图也不会卡。

**Comment by liulex** [comment]
https://bugreports.qt.io/browse/QTBUG-10106
这里提到可能是检测系统代理的导致的阻塞，并且跟系统及系统设置相关，你可以试试在 Snipaste 代理设置中选择不使用代理或者手动指定代理。

**Comment by liyu34** [comment]
@liulex 我把代理设置为不使用代理之后还是会发生这个问题，而且我还发现了另一个似乎是bug的问题，就是我经常出现左侧win键呼不出开始菜单（win10）的情况，但是右侧的win键可以正常的呼出，左侧的win键配其他键的快捷键没受影响（win+x可以正常使用）。刚刚我尝试截图，等了很久没有响应，用QQ的截图截图完成之后才弹出（一闪而过，我用快捷键召唤截图了一次，左键点击了一次任务栏图标），然后这时候左侧win键无法召唤开始菜单了，然后我把snipaste关闭之后左侧win键又正常了。

**Comment by liulex** [comment]
似乎有点混乱…… 😂
在 `首选项` - `截图` - `行为` 可以设置截图时是否屏蔽 <kbd>Win</kbd> 键。也就是说，当左  <kbd>Win</kbd> 键单击无效的时候，说明此时 Snipaste 的截图还没退出，或者是已经退出但是有 bug 导致了还在屏蔽  <kbd>Win</kbd> 键，单从描述还无法确定是哪种情况。
可以的话，发个 QQ 到 <snipaste.app@gmail.com> 吧 😂

**Comment by Aurora-kite** [comment]
> https://bugreports.qt.io/browse/QTBUG-10106 这里提到可能是检测系统代理的导致的阻塞，并且跟系统及系统设置相关，你可以试试在 Snipaste 代理设置中选择不使用代理或者手动指定代理。

怎么设置
