### ISSUE TITLE
貌似x64 exe的sha1跟网站提供的不一致？

### ISSUE THREAD

**Issue by firestarman-james** [liulex/Snipaste-Feedback#274]
貌似x64 exe的sha1跟网站提供的不一致？
（实测是：C160A1DDE41AB65848CCC73D7AEBCE16E2BC1FAB）
但x64 zip的sha1跟官网的又是一致的。

这个软件很不错，很感谢啊~

**Comment by liulex** [comment]
感谢反馈，是这次发布之后我又更新了一次语言包，其中不小心影响到了 exe 的 sha1，现已更正。
