### ISSUE TITLE
标注工具的宽度是否可以更小些，比如矩形框太粗了

### ISSUE THREAD

**Issue by snsnsjsn** [liulex/Snipaste-Feedback#276]
这是qq截图的效果。比较细腻

![github](https://cloud.githubusercontent.com/assets/11435527/21211841/f24f4fb6-c2c1-11e6-8fa3-d3a3b07c9c16.jpg)

这是snipaste截下来的，看起来很模糊

这是snipaste的，比较粗

![github 2](https://cloud.githubusercontent.com/assets/11435527/21211843/f3dda972-c2c1-11e6-848a-044e7111f03c.jpg)
这是qq截图截下来，比较清晰。

虽然问题很细，但是使用的感触不一样啊。

**Comment by septs** [comment]
@liulex

**Comment by liulex** [comment]
未来会支持连续地调整笔划粗细，类似现在的箭头标注。

**Comment by xintiandi** [comment]
这个和个人爱好有关，我的是1080p的分辨率，我反而觉得qq那个太细了。不够明显。

**Comment by paiih** [comment]
我還以為粗細不能調整了，原來是改成用滑鼠中鍵來調整....
可否建議還是給幾個固定 size, 例如原本的小中大，因為動態調粗細時，可能導致粗細不一致的狀況
icon 可以不用改，目前是中鍵滾動調整粗細，加上長按左鍵時，向下滑出小中大 size 提供選取
提供參考，謝謝
