### ISSUE TITLE
建议改进贴图缩放功能，实现以鼠标位置为中心的缩放

### ISSUE THREAD

**Issue by firestarman-james** [liulex/Snipaste-Feedback#277]
如果复制的图像文件的尺寸大于屏幕分辨率，贴图以后就盖住了整个屏幕（并且有一部分超出了屏幕范围），这时还必须使用滚轮之类的把贴图缩放合适大小（比如说能在一个屏幕中完全显示）。

建议提供切换选项：如果贴图尺寸大于分辨率，是否自动缩小以适应屏幕大小。

而且现在缩放贴图时，左上角位置是不变的。如果左上角在屏幕外，就可能导致缩放到一定程度以后贴图基本上都在屏幕外了，必须得边缩放边拖动位置。
建议提供以鼠标为中心的缩放方式，类似于网页版的百度地图。

**Comment by septs** [comment]
整理下：
- 当贴图尺寸大于屏幕时自动等比缩小
- 如果贴图放大到溢出屏幕问题
- 缩放以鼠标为中心执行

**Comment by liulex** [comment]
在 Windows 下，窗口无法平滑地进行**连续**的 移动+改变大小，所以无法实现以鼠标为中心的窗口缩放。

当然也有解决办法，但会影响到很多其他功能，代码量太大，还可能有副作用，我觉得没有必要。#105

**Comment by firestarman-james** [comment]
了解了，还是谢谢哈~

**Comment by firestarman-james** [comment]
后来想了一下，觉得如果能实现“缩放以鼠标为中心执行”，过渡效果暂时不平滑也是可以接受的。

所以建议将“缩放以鼠标为中心执行”作为一个测试功能，默认不开启，开启的时候提醒一下用户这是测试功能就好了。

辛苦啦~谢谢~

**Comment by liulex** [comment]
感谢你的坚持，于是我又再次尝试了下……

这是之前我说的 “窗口无法平滑地进行连续的移动+改变大小”：
（注意右边界）
![1231](https://cloud.githubusercontent.com/assets/2010459/21308289/4e4d5bb4-c614-11e6-80dd-3cbfb67a95c9.gif)
因为微软自家应用都没解决这个问题，所以之前我就放弃继续研究了，实现出来是这样：

![231](https://cloud.githubusercontent.com/assets/2010459/21309000/5eae35b6-c617-11e6-925c-2a98eff31619.gif)

![123123](https://cloud.githubusercontent.com/assets/2010459/21309181/2b8dc510-c618-11e6-9780-c49f4422fdce.gif)

不过我今天又尝试了下，确实还有改进的空间，效果似乎还能接受，所以会加在下个版本里 😄

**Comment by firestarman-james** [comment]
太好啦，哈哈~
真心感谢~
