### ISSUE TITLE
希望可以增加对缩略图缩小后可以右键复制缩小后的局部图像

### ISSUE THREAD

**Issue by yinhux** [liulex/Snipaste-Feedback#285]
@liulex 希望可以增加对缩略图缩小后可以右键复制缩小后的图像，我设置的缩略图图像比较大是250x250为的是缩小局部看细节，而不至于缩小后看不到细节，所以希望进行缩小后也可以右键复制缩小后的图像就好了。。就像下图这样，希望可以复制缩小后里面的局部图
![Uploading snipaste20161225_131355.jpg…]()

**Comment by dlsdgj** [comment]
不是可以对缩略图进行截图吗？

**Comment by yinhux** [comment]
@dlsdgj 右键不是更快和准确。。

**Comment by septs** [comment]
该特性不具备广泛意义。

**Comment by liulex** [comment]
确实意义不大，二次截图即可，操作不差多少……
