### ISSUE TITLE
可不可以支持保存成webp格式的图片。

### ISSUE THREAD

**Issue by hhfgy1** [liulex/Snipaste-Feedback#286]
比jpg压缩好。另外不考虑一下webp格式的动图吗。

**Comment by septs** [comment]
WebP 格式不具备广泛的兼容性
存储角度来说 WebP 并没有什么问题
但是截图是需要传播的必然不能采用 WebP 存储/传播

**Comment by liulex** [comment]
需要的话可以做到插件，不过目前似乎还没什么必要。。
