### ISSUE TITLE
About Snipaste Pro | 关于 Snipaste 专业版

### ISSUE THREAD

**Issue by EMLVIRUS** [liulex/Snipaste-Feedback#287]
I'd heard plan about this. So what's the difference.

**Comment by liulex** [comment]
Thanks for asking.

Snipaste Pro is for:
- Advanced users who wish to enjoy more new features
- Users who have very special needs
- Business users
- Users who acknowledge Snipaste's value and want to support the developer

It will include:
- More advanced options for greater freedom of customization
- Special features that are useful for users in some specific fields
- Brand new and interesting/useful features that have not yet been revealed : )

Meanwhile, the free version of Snipaste will continue to update. All existing features will remain as they are and not be taken away.

However, I don't have much spare time in the coming months. It may take quite a long time for the Pro version to be released.

---

Snipaste 专业版为这些用户准备：
- 希望享用更多功能的高级用户
- 有特殊需求的特定领域的用户
- 商业用户
- 认可 Snipaste 的价值并希望支持开发者的用户

专业版将包括：
- 更多高级选项，以进行更自由的定制化
- 为特定领域用户实现的一些小众功能
- 一些尚未公布的、全新的、有趣/有用的功能 : )

同时，免费版本的 Snipaste 还会继续保持更新。现有的所有功能都不会被收回。

不过我接下来几个月都没什么时间，所以专业版可能需要等很久，目前只实现了少量几个功能。

> 已捐赠用户会有特殊优惠 : )
> （已经/将来）通过支付宝/微信捐赠的，请将捐赠信息发送到 <snipaste.app@gmail.com>，以后专业版出来我会主动通知你们。邮件标题格式：
>
> > 捐赠渠道，交易时间（或者 订单号/交易单号）
>
> 如：
> > 支付宝，2016-12-25 23:05
> >  微信，2016-12-25 23:05:30

**Comment by yonghuming** [comment]
windows可以录制gif吗

**Comment by Nowaterisenough** [comment]
多屏情况下，win键截图会有轻微的卡顿，单屏下没问题。

**Comment by MagicStarTrace** [comment]
Currently, I use the Text Scanner on my Mac for OCR recognition and then click DeepL to translate.

I wish Snipaste Pro would support the text scanner feature for a fee!

**Comment by yonghuming** [comment]
您好，邮件已经收到

**Comment by g968948** [comment]
为什么windows吸色总是和自己输入的颜色不一致，色值都不一样

**Comment by yonghuming** [comment]
您好，邮件已经收到

**Comment by xiehaibin18** [comment]
希望在 OCR 文字识别的基础上增加翻译功能，进一步可以配置大模型的 API 和 key 实现截图 文字识别 AI 翻译的一条龙服务。

**Comment by yonghuming** [comment]
您好，邮件已经收到

**Comment by fishso** [comment]
建议pdf、网页等增加滚动截屏

**Comment by yonghuming** [comment]
您好，邮件已经收到
