### ISSUE TITLE
检查更新没有用吗？

### ISSUE THREAD

**Issue by Jason4774** [liulex/Snipaste-Feedback#289]
你好，记得之前检查更新会弹出一个提示“已经是最新”或者“有更新版本”，但是现在点击更新却没有任何反应，我更新版本都是自己在官网下载的。请问我是个例吗？该怎么解决呢？谢谢。

**Comment by liulex** [comment]
你试试改变“更新”设置里的代理选项，再检查更新，看是否有反应。
手动检查更新的时候，应该无论成功与否都有提示的。

另外，“已经是最新”这个提示现在是通过气泡通知弹出的（以前是窗口），如果你禁用了 Snipaste 的通知权限，就会导致看起来没反应了。

**Comment by otherfish** [comment]
不知为什么之前有更新了会弹出更新窗口让更新的，最近几版是能弹出让更新的窗口，但是 单击或双击也弹不出更新进度条了，直到看了这个issue，检查了一下更新的代理设置：
![snipaste20170104_123000](https://cloud.githubusercontent.com/assets/12808134/21631704/8c38825c-d279-11e6-946f-001051565a6e.png)
但是我最近明明没有改动代理设置啊，或者说我一直都没有更改过任何设置，都是out of the box使用的。
可是改了无代理，还是不能更新，不知道咋了。

**Comment by liulex** [comment]
@otherfish 单击或双击 哪里？

**Comment by Jason4774** [comment]
是我自己禁用了设置，启用后正常了，

**Comment by liulex** [comment]
@Jason4774 谢谢反馈，解决了就好。
@otherfish 我明白你意思了，是指单击气泡通知。现在单击气泡通知是先开始下载更新日志再打开更新窗口，所以如果网络有些问题，更新窗口就可能会迟迟没有出现。我在下个版本改进下。

**Comment by otherfish** [comment]
@liulex win10的操作中心弹出的，现在即使右键托盘图标手动更新也不行，没有任何反应，我网络是正常的。
