### ISSUE TITLE
键盘快捷键具体名称

### ISSUE THREAD

**Issue by 804260247** [liulex/Snipaste-Feedback#29]
你好，我试着在config.ini里面修改快捷键，不过只支持Fx键吗，有可能是我设置其他按键的名称不对，如果可以设置其他快捷键能否把**快捷键的具体名称**陈列出来呢，非常感谢！

**Comment by liulex** [comment]
你好，v1.4 及之前的版本，快捷键设置均有 bug，有一些按键显示设置成功但无效，以及修改默认快捷键之后，重启 Snipaste 之后默认快捷键没有被正确释放。
这些问题已经解决，请期待 v1.5！届时除了 PrintScreen、Tab 以及一些被系统及其他程序占用的快捷键，应可顺利设置为其他快捷键。
但建议从选项窗口进行快捷键配置，而不是手动修改 ini 配置文件。

**Comment by 804260247** [comment]
非常感谢，期待新版本

**Comment by liulex** [comment]
新版已经发布。
