### ISSUE TITLE
对NSight进行截图时直接卡死

### ISSUE THREAD

**Issue by lonelyWaiting** [liulex/Snipaste-Feedback#290]
描述：
使用`NSight`调试程序，启动`Snipaste`,将鼠标移至`NSight`所在区域，卡死

**Comment by liulex** [comment]
照这里最后一个选项设置下：
https://github.com/liulex/Snipaste-Feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE

**Comment by lonelyWaiting** [comment]
依然不行
![qq 20161227232626](https://cloud.githubusercontent.com/assets/8894664/21502605/05bc6dc6-cc8c-11e6-9516-ce771f06fad7.png)
我随便找了一个Direct3D的程序用NSight调试，然后将鼠标移到图片中相应的区域时，会导致Visual Studio直接死掉
![image](https://cloud.githubusercontent.com/assets/8894664/21502644/4ee326de-cc8c-11e6-908e-dd912c9b1f3d.png)
字符串使用英文的双引号括起来我也试过，依然是一样的结果，NSight的exe路径我确定是没有错的.
不知是否有其它的解决方法.其它软件上使用Snipaste截图倒是没遇到这种情况.

**Comment by liulex** [comment]
不不，不是用 `exclude_from_detection`，是 `crashes`；也不是填路径，填 exe 名称就行了，比如：
```
crashes=Nsight.Monitor.exe
```
你再试试~

**Comment by lonelyWaiting** [comment]
额...尴尬，居然没有看到`crashes`,我试试~

**Comment by lonelyWaiting** [comment]
依然跪..
话说开NSight调试程序时，也只有上图中那一种情况会挂掉，就是在`Geometry`下的`Graphical`下的那块灰色区域，鼠标移到其它地方都没事.

**Comment by liulex** [comment]
@lonelyWaiting 没错的，这个选项就是针对这种情况的……
现在还不行的话，要么 exe 没找对，要么 Snipaste 不够权限获得这个 exe 的名称。
今天有点晚了，改天我联系你邮箱测试一下~

**Comment by lonelyWaiting** [comment]
OK~麻烦了

**Comment by liulex** [comment]
> 话说开NSight调试程序时，也只有上图中那一种情况会挂掉，就是在Geometry下的Graphical下的那块灰色区域，鼠标移到其它地方都没事.

这个我重现了，这个是 vs 的窗口，所以应该排除 devenv.exe 才对。不过这样误伤范围太大，我再看看有没有其他办法。。。

>  使用NSight调试程序，启动Snipaste,将鼠标移至NSight所在区域，卡死

这个描述，是另一个问题，还是就是上面那个问题？

**Comment by lonelyWaiting** [comment]
我描述的就是你所重现的那个问题~
