### ISSUE TITLE
Win8.1截图保存时停止工作

### ISSUE THREAD

**Issue by zumurud** [liulex/Snipaste-Feedback#291]
---
Win8.1+Mactype（有试过停止渲染但未退出），管理员权限下运行，在任一程序任一窗口大小下截图，快捷键或点击选择保存到文件时，或贴到屏幕后选择另存为时，程序每次都停止工作。

**Comment by liulex** [comment]
刚装了个 MacType 1.2016.904.0 x64，按照你的描述进行操作，没有发生程序崩溃。 (Win 10)
如确认是 MacType 造成的，把 Snipaste.exe 排除就好了吧。

**Comment by zumurud** [comment]
并非如此。已经把snipaste.exe加入排除，后来干脆退出了mactype，程序还是会停止工作，这么看来也许并不是两者冲突。大概这条描述引起误会了=。=抱歉。

**Comment by liulex** [comment]
那应该也是其他程序冲突造成的，大概只能你自己排查一下了……因为包括你在内一共只有两个用户报告了这个问题。
或者你也可以试试 Snipaste 的其他版本，比如 32 位的，也有个别用户是用 64 位有问题而 32 位 ok 的。

**Comment by zumurud** [comment]
x86版没问题，1.11x64暂时还是一样...
谢谢你~

**Comment by liulex** [comment]
那应该是系统环境的问题，你还可以尝试下卸载重装 VC++ 2015。
谢谢反馈。
