### ISSUE TITLE
win7启动报错

### ISSUE THREAD

**Issue by xiwc** [liulex/Snipaste-Feedback#292]
版本: Snipaste-1.10.5-x64
错误截图:
![image](https://cloud.githubusercontent.com/assets/8816203/21558133/3754b812-ce70-11e6-83bb-37b5e86e3357.png)

**Comment by septs** [comment]
see https://docs.snipaste.com/#/zh-cn/troubleshooting#运行后遇到提示计算机中丢失-api-ms-win-crt-runtime-l1-1-0-dll-错误

**Comment by xiwc** [comment]
3ks
