### ISSUE TITLE
建议在编辑栏后面加一个“首选项”按钮

### ISSUE THREAD

**Issue by mlkt** [liulex/Snipaste-Feedback#294]
在编辑栏后面加一个“首选项”按钮，这样即使设置了隐藏托盘图标也能有入口打开选项窗口

![image](https://cloud.githubusercontent.com/assets/10374085/21579539/d58dfc60-cff0-11e6-9db3-0df50febde15.png)

**Comment by septs** [comment]
请自行了解内置快捷键
