### ISSUE TITLE
建议：期待添加印章功能

### ISSUE THREAD

**Issue by bonjourcs** [liulex/Snipaste-Feedback#295]
某些截图下，希望给别人指导步骤。所有，期待后期版本有印章功能。 : )

**Comment by bonjourcs** [comment]
你好，抱歉issue里没能更详细地描述，我希望在Snipaste中添加的「印章」功能，是对截图的二次编辑，可以添加序号，形状等印记。附上效果示意图，希望Snipaste越来越好。感谢你们的努力。







在2017年01月01 11时36分, "septs"<notifications@github.com>写道:



能够具体描述 印章 的需求细节以及您的期望吗？

**Comment by bonjourcs** [comment]
![示例图](https://cloud.githubusercontent.com/assets/18501114/21580246/c63c0e7e-d021-11e6-8619-7f08308a42f3.png)

**Comment by septs** [comment]
这个或许可以看作是 文本框 的边框拓展形式
