### ISSUE TITLE
可否增加功能：贴图大小为100%可以按中键进入缩略图模式 （Feature request）

### ISSUE THREAD

**Issue by firestarman-james** [liulex/Snipaste-Feedback#296]
#280 

建议进一步增加功能：贴图大小为100%可以按中键进入缩略图模式。

这样就可以实现中键功能的全面化（免除了win+click的繁琐）：
贴图大小不为100%按中键可以重置贴图，再按中键可以进入缩略图模式，再按中键又重置贴图；
贴图大小为100%按中键直接进入缩略图模式，再按中键又重置贴图。

**Comment by liulex** [comment]
你的出发点应该是，对 100% 大小的贴图按中键是没有意义的，应该把这个动作利用起来。
不过我认为不太合理：
1. 有时候（甚至常常）我们需要确认当前贴图是否已经是 100% 大小，所以会对已经是 100% 大小的贴图再按一下中键来确认，所以对 100% 大小的贴图按中键并不是没有意义的。
1. 如果加上你的设定，那么 100% 大小的贴图可以通过中键进入缩略图，非 100% 的贴图却不能通过中键进入缩略图（还是需要 win+click），这是有点反直觉的，会让用户使用的时候产生犹疑。
1. 你的想法有点类似 `在贴图闪烁时，按下贴图键隐藏所有贴图` 这个选项，但不同的是，闪烁的时候按下贴图键，这个动作确实是没有任何意义的，所以赋予它一个额外动作是合理的。

**Comment by firestarman-james** [comment]
嗯，你说的也有道理。

建议增加双击右键实现缩略图的切换吧。
同时还希望能在贴图的右键菜单中提供旋转、重置、缩略图等所有需要按键实现的操作。如果菜单过长，可以考虑放到子菜单中。这样就不用太费心去记住那些快捷键，有哪些可以实现的操作也能一目了然。

**Comment by septs** [comment]
@firestarman-james 
关于 <kbd>双击右键</kbd> 这个行为如果实现会造成其他用户认为是 bug 因为不符合惯性认知
在普遍的惯性中通常认为 <kbd>右键</kbd> 单击出现 上下文菜单 的另外并没有 UI 框架导出 <kbd>双击右键</kbd> 的 API 因此无法实现该需求。
您对于 <kbd>中键</kbd> 语义定义是？

**Comment by firestarman-james** [comment]
中键的功能保持现状我觉得没问题。

“双击右键”这个可以考虑作为一个切换选项供用户选用（默认不启用就好了）。

http://blog.csdn.net/sduvec/article/details/28450169
http://stackoverflow.com/questions/32640625/onclicked-and-ondoubleclicked-both-happen-in-qml
简单搜了下，貌似qt能实现右键双击消息处理。当然俺木有玩过qt，不敢确定。

**Comment by septs** [comment]
@firestarman-james 右键 叫作 QContextMenuEvent 因此该需求无法实现
see https://doc.qt.io/qt-5.7/qcontextmenuevent.html#details

**Comment by liulex** [comment]
@firestarman-james @septs 
右键双击，技术实现上没有问题。但对于有右键菜单的窗口，再给右键双击绑上一个功能，这是很别扭的行为。我用过的软件中，没有软件会支持这种行为。

贴图右键菜单提供哪些动作，我是有仔细安排过的，我不认为所有动作都应该放上去，该按键的就按键。初期使用可能有一些记忆负担，但实际也没几个按键。当你熟悉之后，那些菜单项就死了，因为你可能不会再点击它们，所以我觉得没有放上去的必要。

缩略图显示的区域取决于你鼠标点击的地方，而不是你所说的”中央的部分区域“。”希望能实现缩略图显示的是整个贴图按相应大小缩放的结果“，这个就是贴图缩放而已……和缩略图搭不上。

对贴图打 tag 我认为没有必要，因为现在已经有贴图分组，tag 和分组本就是比较相似的功能。
但是贴图以后会有一些更高级的操作的，已经在计划中，请耐心等待~

**Comment by firestarman-james** [comment]
@liulex 好的，了解啦，谢谢~
现在的win键不是很容易“盲”按。方便的话帮忙实现右键双击切换缩略图功能吧，作为一个默认不开启的选项。
非常感谢~

**Comment by liulex** [comment]
@firestarman-james 
可以根据自己需要换成其他按键啊，比如 <kbd>Shift</kbd> + 左键双击~
对于不合理的行为，没有必要提供选项 =.=

**Comment by firestarman-james** [comment]
@liulex 好的，刚试了发现在选项里要先把“左键单击”改成其他的，才能把“win”改成其他的，不然就改不掉win。前段时间就想换掉win，还以为被限定了只能用win。
不过貌似不能实现“ctrl+左键单击”来切换？有点可惜。
还是感谢哈~

**Comment by liulex** [comment]
@firestarman-james 对，因为 <kbd>Ctrl</kbd>+左键单击 将会有其他功能。
