### ISSUE TITLE
建议进一步对贴图提供任意角度的自由旋转功能，甚至透视变换等功能

### ISSUE THREAD

**Issue by firestarman-james** [liulex/Snipaste-Feedback#297]
现有的贴图旋转角度限制太多，不是很适用于照片拍斜等情况。
建议将来进一步提供任意角度的自由旋转功能，甚至透视变换等功能（类似于photoshop的自由变换）。
辛苦啦，谢谢~

**Comment by liulex** [comment]
Snipaste 不适合处理此类操作，以后也不打算支持，该上 PS 还是得上啊。。:joy:
