### ISSUE TITLE
选择字体的时候会出现"意大利体"

### ISSUE THREAD

**Issue by BenjaminGao** [liulex/Snipaste-Feedback#298]
1. 请问这是我电脑的问题还是,每一个字体所对应的字体风格里都有意大利体(1.11.0版本)
2. 在1.10.5版本中无法升级,今天弹出(windows10操作中心弹出)的1.11.0版本,我点击升级后无反应,我在"代理类型"里四个选项挨个换一遍都一样,点击"检查更新"都无反应,无奈在官网下载的1.11.0版本升级的
3. 现在的Sn占用内存为21.6M(1.11.0版本),我记得最初的只有10M左右,以后会不会随着功能的增多增强越来越大啊,虽然现在内存都普遍最低都是8G
![snipaste20170102_143330](https://cloud.githubusercontent.com/assets/16028320/21585365/9395f8e4-d0f9-11e6-8fbb-3a627cb2c953.png)
![snipaste20170102_145506](https://cloud.githubusercontent.com/assets/16028320/21585451/809c8922-d0fb-11e6-9ae5-e6b6193399b6.png)

**Comment by liulex** [comment]
1. 意大利体其实是 Italic，斜体，被 Qt 翻错了。。。😂😂
1. 之前的版本确实更新逻辑有点 bug，在 1.11.0 的日志里有这一条，现在应该修复了，如下次更新还有问题请再报告。
1. 内存消耗是跟当前的贴图数量有关系的，不知你对比的时候有没有考虑到这个。
  从 1.0 到 1.11，虽然功能和选项多了不少，但其实并没有增加明显内存消耗的地方，甚至应该有降低资源消耗，毕竟修了不少 bug……
  Snipaste 会尽可能保持小巧的，如有增加消耗的地方，肯定也会提供可控选项，让用户自己选择要功能还是要内存。

**Comment by BenjaminGao** [comment]
@liulex 如果下次还有更新的bug我会反馈的=.=

**Comment by BenjaminGao** [comment]
@liulex 新版1.15号发布的，我今天点更新，又没作用，上回就反馈了这个更新点了没作用的问题，这次又没作用....,不是我设置的问题，就是更新的BUG。从1.11.0->1.11.1
不是系统的问题，你们这个更新机制，就是在“更新”页面点“检查更新”也无反应

**Comment by liulex** [comment]
@BenjaminGao 谢谢反馈，请问是否点“内置快捷键”窗口也是弹不出来？

**Comment by BenjaminGao** [comment]
@liulex 不，弹出来了（1.11.1版本）
![gif](https://cloud.githubusercontent.com/assets/16028320/21974443/e95a8e62-dc01-11e6-9513-3811a675b71a.gif)

**Comment by liulex** [comment]
查出来了，下版本修复，谢谢反馈。
