### ISSUE TITLE
win10中启动不了

### ISSUE THREAD

**Issue by liguoqinjim** [liulex/Snipaste-Feedback#299]
使用的版本是v1.11.0
双击之后，鼠标loading转一下就没反应了。什么错误都没提示。系统托盘中也没有出现，按F1也没有用。
请问有错误日志吗？

**Comment by liulex** [comment]
暂时没有加入日志功能，不久后会有的。
请下载前一两个[旧版](https://bitbucket.org/liule/snipaste/downloads) 试试，确认一下是否只是 v1.11.0 有问题。

**Comment by liguoqinjim** [comment]
我试了几个
1.11.0不行
1.9.1不行

1.10.5可以
1.7.1可以

**Comment by liulex** [comment]
=_=
留个 QQ 吧 <snipaste.app@gmail.com>

**Comment by liguoqinjim** [comment]
开不了的时候可以试下关闭360。会随机的打得开打不开。。。
