### ISSUE TITLE
个人提议：作者可以建立一个投票，方便筛选需要添加的功能

### ISSUE THREAD

**Issue by StarryVoid** [liulex/Snipaste-Feedback#3]
首先作者的软件十分好用！

在Telegream讨论时，看到作者最近收到了很多人提出的各种各样的需求，作者也很善良将需求都一一比对并列出了一个列表。
个人认为：列表中很多提出的功能并不适合绝大多数人，或者说需求和软件目的违背
个人提议：作者建立一个投票，将一些想加入的功能放进去，由大家进行多选投票，高的可以收录，低的就无视吧。

举例子（不含恶意）
有一条是：添加网络上传功能
个人认为，软件核心是贴图>截图，这和网络有关的功能看不出和软件核心目的有什么贴切的地方，而且添加这种上传功能，从安全角度来看也需要作者写很多代码。

**Comment by yylzcom** [comment]
https://www.uservoice.com/

示例：
https://rainloop.uservoice.com

**Comment by liulex** [comment]
@StarryVoid 上传其实属于截图分享，还是有挺多用户需要的，除了上传网络，还有分享到其他软件，如印象笔记、有道云笔记等。
当然，我个人应该不会去写网络上传相关的代码，我基本不了解，也暂时不想了解，如果可以调用第三方 API 那是最好的。比如 Mac 平台就会和 iPic 进行合作。

@yylzcom uservoice 没有中文版，对国内用户不太友好。不知道大家是否有其他提议？

**Comment by StarryVoid** [comment]
那看来是我理解有偏差
我理解的是，程序自带的网络上传功能。

**Comment by Dwwwwww** [comment]
@liulex 
不知道Telegram的@vote能否实现呢=-=

**Comment by liulex** [comment]
@Dwwwwww Telegram 上人太少……
暂时就用 issues 吧
