### ISSUE TITLE
使用 Snipaste 截图后的图片，在 QQ 中发送后，若对方是手机用户，无法显示该图片

### ISSUE THREAD

**Issue by ziofat** [liulex/Snipaste-Feedback#30]
重现方法：
1. 开启 QQ 并和任意手机用户对话
2. 按 F1 截图后，粘贴到 QQ 对话框，并按发送键
3. 手机用户收到的信息为（iOS）：
![image](https://cloud.githubusercontent.com/assets/8521174/17460182/d3424aea-5c9d-11e6-881e-505d6d4f42c7.png)
（Android）：
![image](https://cloud.githubusercontent.com/assets/8521174/17460189/0f6347fe-5c9e-11e6-82f1-52c9a18ef022.png)
4. 使用 QQ 截图并发送后，正常。

**Comment by orzFly** [comment]
QQ 版本号？Windows 版本号？

**Comment by ziofat** [comment]
QQ：QQ 轻聊版 QQ 7.9 (14308)L
Windows：Windows 10 Pro （Version 1607，OS Build 14393.10）

**Comment by liulex** [comment]
我是 Android QQ 轻聊版 V3.5，测试了并没有问题……

**Comment by ziofat** [comment]
抱歉，更新 Snipaste 到 v1.4 后解决。
