### ISSUE TITLE
截图在QQ窗口粘贴时出现问题.

### ISSUE THREAD

**Issue by aken85** [liulex/Snipaste-Feedback#300]
发现了 bug？
* 截图在QQ聊天窗口粘贴时,就出来一个"(",是什么原因?BUG?

**Comment by liulex** [comment]
条件不充分，请再仔细描述一下。

**Comment by aken85** [comment]
有时在截图后,到QQ聊天窗口粘贴,只是出来个左括号,而没有粘贴上截图的内容.有时候同样的操作又是正常的.win10 64位系统.

**Comment by liulex** [comment]
@aken85 你提供的条件并不能让其他人重现，你可以试试其他电脑，应该也是不能重现的。。
