### ISSUE TITLE
按下f1，QQ会下线。360报毒。这个是什么原因

### ISSUE THREAD

**Issue by huchenghua** [liulex/Snipaste-Feedback#302]
按下f1，QQ会下线。360报毒。这个是什么原因

系统：win10
版本：Snipaste-1.11.0-x64

**Comment by liulex** [comment]
下载渠道？[sha-1](https://dl.snipaste.com/sha-1.txt)？

**Comment by huchenghua** [comment]
下载地址 https://zh.snipaste.com/
md5 01fc5efb99fafe5c63611513b544fb98

**Comment by liulex** [comment]
文件校验没错。
但同时并没有其他 QQ/360 用户报这个问题……
360 报毒的截屏可以给一个吗？

如果是 F1 开始截图才有问题，那么可能是你的系统限制了一些系统 API，你可以试试取消勾选 `自动检测界面元素` 再截图看看，如果还不行，就再取消勾选 `自动检测窗口`……

**Comment by liulex** [comment]
参考 #354 ，360 可能会报 ”虚拟按键“。
