### ISSUE TITLE
截图后发送到wechat（移动端）出现色差

### ISSUE THREAD

**Issue by loveofyou** [liulex/Snipaste-Feedback#303]
本机环境 ： Win10 14393.576 X64
发送截图到微信手机端，包括（wechat for win/wecaht for win10 app/wecaht Web）等途径，移动端（包括Android/Ios）接收到后出现色差。但在移动客户端内下载原图后恢复正常。
截图原文件：

![1](https://cloud.githubusercontent.com/assets/1229499/21640585/5ced4d9c-d2b1-11e6-8a28-f90a4977ab43.jpg)
客户端预览截屏：
![3](https://cloud.githubusercontent.com/assets/1229499/21640598/7853fee6-d2b1-11e6-8b2a-aaf38253f065.jpg)
客户端下载原图后预览截屏：
![2](https://cloud.githubusercontent.com/assets/1229499/21640611/873aa662-d2b1-11e6-9d4c-8fbfed5dd0c3.jpg)

**Comment by liulex** [comment]
非常感谢你的详细测试。
该问题在九月份曾经有用户反馈，当时应该已经通过发布新版解决了。
我刚刚用 v1.11.0 测试了下，WeChat for PC + WeChat for Android，对你提供的第二张图片进行截图 -> 复制到剪贴板 -> 粘贴 -> 发送，没有发生色差的情况……

Snipaste 与剪贴板有关的选项是这个，你可以尝试改变一下，看结果是否有修复。
![snipaste20170104_204617](https://cloud.githubusercontent.com/assets/2010459/21642663/db992172-d2be-11e6-9da9-605065eb7c8a.png)

**Comment by loveofyou** [comment]
非常感谢作者的及时回复。
经更新版本后问题已经消失，因为早期的版本没有检测更新，所以也一直没有更新，非常不好意思打扰了！
