### ISSUE TITLE
你好..我只是一个普通用户,实在是搞不懂关于贴图那部分的一个问题

### ISSUE THREAD

**Issue by itiszg** [liulex/Snipaste-Feedback#306]
作者你好,我的系统是WINDOWS10,这个截图软件很强大,但是许多功能我用不上,我最喜欢的就是随时可以把截图贴到屏幕上(工作需要). 但是我不知道为什么,我截图(按键盘上F1),一气截了6个图,然后想贴到屏幕上(按键盘上F3),总是只能贴一个(有时候可以贴三个),而且都是逆向顺序贴上的(就是,第一个贴出来的图是最后一次的截图).
我实在是搞不明白,软件里的教程我也看了,只是说必须是系统剪切板里有的图才可以.
那我就更不明白了,难道说,我每次截图以后,马上就贴到屏幕上,然后再继续截图,然后再贴,如此循环,才能在屏幕上列出N个我刚才的截图吗?
(其实,我的意思就是,我一口气截了好多图,比如十几个,二十几个,你这软件是否可以都保存着,然后按F3随时调用出来)
对不起我不是程序员,太专业的词语说不出来,我也不知道作者是否能看到这这条咨询..总之我很喜欢这个截图软件,确实很强大很好用.

**Comment by GregAMO** [comment]
……确定选区以后有三个去向：
保存到本地、保存到剪贴板、贴到屏幕上
推荐打开`首选项-截图-行为-单击中间将截图贴到屏幕上`
这样确定选区以后，在选区里面点一下中键即可
（如果恰好所需的是Snipaste自动识别的界面，直接按中键就行）
总之设置和帮助都看看吧

**Comment by liulex** [comment]
@itiszg 你好，很高兴收到你的反馈，谢谢你有看教程 :)

每次把新截图复制到剪贴板后，当然会丢失以前放在剪贴板里的图，所以最终贴出来的就只有一张图，因为剪贴板里只有一张图。而你说的 “逆向”，实际是把你以前已经关掉的贴图又恢复了出来。

Snipaste 不可能为你把以前的截图的保留起来，以便你以后一次性贴出的。因为我无法判断你是要保留住以前的截图，还是你就要最后一张截图，除非为“保留住以前的截图”专再门设立一个快捷键，但是这会让 Snipaste 的使用和行为逻辑复杂很多，我不太希望去实现这个功能。

那么是否就没办法 `一口气截了好多图，然后一次性贴出来` 了呢？
不，有办法，而且非常方便 :)

v1.11.0 新增运行用户自定义截图时回车键的功能，你可以这样设置：
![snipaste_20170106_212438](https://cloud.githubusercontent.com/assets/2010459/21719055/8f03cf12-d456-11e6-9d73-6833ad8a9d69.png)

然后就可以这样了：
![555](https://cloud.githubusercontent.com/assets/2010459/21719113/e3ce57e2-d456-11e6-9cab-cd6d14131488.gif)
（工具条每闪动一次，表示我按了一次回车键）

希望你喜欢这个功能。

**Comment by itiszg** [comment]
这页面都是英文的,我也看不懂,不知道哪个是回复,哪个是引用.
总之,谢谢二楼的回答,也谢谢作者的亲自答疑解惑. 
非常感谢
真心的感谢.
