### ISSUE TITLE
是否可以增加多区域捕捉的功能呢？

### ISSUE THREAD

**Issue by Caodaping** [liulex/Snipaste-Feedback#307]
在学习新软件时或者制作软件的操作手册时，经常需要对软件的菜单进行截图。但是软件的菜单有时候会有主菜单、子菜单甚至三级、四级菜单。现有的功能在截图的时候，要完整截取菜单时，会连同背景一并截取。但更期望不包含背景而仅仅是菜单。

　　是否有可能增加新的功能，在截图时按住某一个快捷键(比如Ctrl或Alt或Shift)，选择一个区域点击鼠标一次，完成一次截图；再选择一个区域点击鼠标一次，完成第二次截图；再点击......如果要完成捕捉，按回车键；如果要取消，按Esc键。完成捕捉之后，把之前截取的图拼接在一起，成为一个图片文件。这样捕捉出来的菜单不包含背景，而仅仅是菜单相关内容。

　　目前了解到hypersnap有类似功能，叫做“多区域捕捉”，picpick和snagit似乎没有！谢谢！

**Comment by liulex** [comment]
连续截图的话，见这里的演示：https://github.com/liulex/Snipaste-Feedback/issues/306#issuecomment-270903542

贴图拼接会在以后加入。
