### ISSUE TITLE
开源出来也不错啊

### ISSUE THREAD

**Issue by ZhengHui-Z** [liulex/Snipaste-Feedback#308]
开源的话利于软件以后发展

**Comment by septs** [comment]
see https://github.com/liulex/Snipaste-Feedback/issues/245#issuecomment-263056941

**Comment by JimEverest** [comment]
https://github.com/JimEverest/fastshot
Fastshot is an open-source Python-based screenshot tool for Windows, inspired by Snipaste. It provides a versatile and user-friendly interface for capturing and annotating screenshots, making it ideal for research, reading papers, writing code, and various comparison and demonstration scenarios.

Features
Always on Top: Screenshots stay on top, allowing easy comparison.
Smooth Zoom and Drag: Effortlessly zoom and drag screenshots.
Annotation Tools: Hand-drawing and text mode for annotations.
Clipboard Export: Easily export screenshots to the clipboard.
OCR Integration: Extract text from images using the built-in OCR plugin.
