### ISSUE TITLE
高dpi设置下，截图模糊，并且截图出的图片小了很多，大概是dpi的比例。

### ISSUE THREAD

**Issue by kokutoukiritsugu** [liulex/Snipaste-Feedback#31]
如图：
<img width="491" alt="default" src="https://cloud.githubusercontent.com/assets/5471433/17461595/fab03462-5cc4-11e6-90bd-772cbd2f318d.png">

截出来的图会小一圈：
![sp160807_173057 2x](https://cloud.githubusercontent.com/assets/5471433/17461602/0958a3f0-5cc5-11e6-8f47-873dafe04358.png)

这个是 print screen 键截图出来的样子：
<img width="282" alt="2" src="https://cloud.githubusercontent.com/assets/5471433/17461605/15a30542-5cc5-11e6-8bb3-a226ce58e928.png">

**Comment by kokutoukiritsugu** [comment]
系统 win10 rs1  x64，dpi设置 150%
显卡 nvidia

1.3 1.4都有这个问题。
望修复。。。软件真是太吊了。。。

**Comment by liulex** [comment]
我平时 200% 的 dpi 没有问题，特意去设成了 150% 也没有问题。
但如果屏幕本身建议使用 100% 的dpi，设成了 150%，这种情况是我还没有测试的，目前在家，也没办法测试调试了，以后我再试试。
另外就是双屏情况下，高分屏和普通屏混合使用，这个是确定了有问题的，但目前也没有条件去修复。

**Comment by liulex** [comment]
另外有一位相同问题的用户协助我测试了，确实和 DPI 有关，他调成 125% 就没问题了。
但实质上不只是 DPI 的问题，我得想办法重现了才有可能解决它。

**Comment by kokutoukiritsugu** [comment]
我显示器最大分辨率是 3840 2160
我设置 125% 也没问题了。。。

然后其他几个比率都会在左上角识别到一个 960 x 52x 的框，然后同时文字是模糊的。

<img width="1920" alt="150" src="https://cloud.githubusercontent.com/assets/5471433/17640913/682a9a50-613e-11e6-9d24-6df8d7c4d7d3.png">

![175](https://cloud.githubusercontent.com/assets/5471433/17640914/68fce6ea-613e-11e6-85b1-097ea82398f2.png)

![200](https://cloud.githubusercontent.com/assets/5471433/17640915/69b22992-613e-11e6-9ca2-171d7e51aa54.png)

**Comment by liulex** [comment]
1920 * 1200 的屏幕设置各种 DPI 也没重现问题……
目前没条件尝试你们的设置了 :persevere:

**Comment by kokutoukiritsugu** [comment]
vmware虚拟机好像可以设置超过宿主机分辨率，试试？

**Comment by liulex** [comment]
@kokutoukiritsugu 不知当前的 1.10.4 是否还存在这个问题？

**Comment by kokutoukiritsugu** [comment]
@liulex 没问题了。

**Comment by liulex** [comment]
@kokutoukiritsugu 好的，谢谢反馈。
