### ISSUE TITLE
一点小建议!

### ISSUE THREAD

**Issue by Syasuker** [liulex/Snipaste-Feedback#310]
1. 希望用户截图划取范围之后直接变成贴图; 不要有编辑操作;突出贴图功能 ;或者妥协一下双击变为贴图;因为这款应用主打不是截图而是便签我觉得可以这样操作;
2. 默认贴图的时候若贴图宽度大于屏幕宽度直接进行缩放 
3. 若图片长于屏幕高度若干请让滚轮是网页上下滚动效果吧; 
或许可以把中文名写作万能便签?

**Comment by septs** [comment]
1. 中键按可将截图变为贴图
2. @liulex 
3. Snipaste 是组合词(Snip + paste) 并且作者并没有想设定中文名称的想法

**Comment by Syasuker** [comment]
多谢回复;
1. 因为软件的截图功能并不是特别亮眼,在众多截图软件中很难杀出一条路;所以我建议主推贴图便签功能,如果能将截图选项去掉最好不过;逻辑就是把xx变成贴条这样.这只是我个人的想法;一个建议;
2. 在上面的前提下截图划取范围直接变成便签就很方便合理了;
x. 我只是不明白为啥在QQ截图上延续的双击确认操作变成了取消截图;一般来说双击不是一个向前的操作么?win mac linux都这样;双击做成贴条便签是不是要合理一点=.=

**Comment by septs** [comment]
双击并不是取消截图 而是将截图放入剪贴板

**Comment by liulex** [comment]
1. 虽然我很高兴你对贴图功能的认可，但截图我也是花了很多心思的…………而且事实是，更多用户是因为截图才用的 Snipaste.
2. 双击从来就不是取消截图……既然中键已经可以设置成直接贴图了，双击就没必要再抢了吧，就留给剪贴板吧。当然以后还会给用户更大的定制自由度。
3. 贴图宽度大于屏幕宽度直接进行缩放，这个是有用户提过的，被我漏统计了……以后会作为选项加上。

**Comment by Syasuker** [comment]
将截图放入剪贴板然后黏入系统画图板么?
一直以为这是一个很尴尬的操作来着;微软为啥不直接打开画图板粘进去呢=.=
在贴图上c 然后v入系统画图板=.=是不是更符合复制粘贴概念
目前感觉没有复制就没有粘贴的感觉=.= 貌似其他截图软件也没有使用剪贴板这个概念.

没有贬低截图的意思;QQ的截图也是这样的:)很好很强大感觉作为QQ截图本地版宣传也能很火了;
只是我过来的原因是多功能便签.希望能结合的紧密一点;
多谢回复:)

**Comment by Syasuker** [comment]
怪不得很多操作感觉不太对劲;原来我没有剪贴板的概念==
谢了:)

**Comment by GregAMO** [comment]
@Syasuker 截图放进剪贴板也可以粘贴到
其他程序（如Telegram）或其他网页（如 Github）
场景还是挺广泛的

另外新功能`首选项-截图-行为-回车键功能`对贴图狂魔也很友好的

**Comment by BianChengNan** [comment]
截图的时候现在是按快捷键ctrl+T来转换成贴图的，我在想为啥不按F3直接变成贴图呢？？？我最开始就是这么理解的...

**Comment by liulex** [comment]
@BianChengNan 有道理，确实多此一举了，下个版本会运行在截图时按下贴图键。
这样一来 <kbd>Ctrl</kbd> + <kbd>T</kbd> 似乎可以取消了……
