### ISSUE TITLE
截图后图像模糊

### ISSUE THREAD

**Issue by victormxz** [liulex/Snipaste-Feedback#311]
近期使用发现截图后，图片非常模糊，刚更新程序不久，请求解决，谢谢！

**Comment by EMLVIRUS** [comment]
![image](https://cloud.githubusercontent.com/assets/16912240/21841118/cf476afc-d81b-11e6-84a0-fec35db468d3.png)

**Comment by liulex** [comment]
@victormxz 不可能是 "近期" 出现的，因为一直就没改过这部分代码，你是不是存成 JPG 了？另外，模糊与否是很主观的，得给出对比才能说明问题啊，比如列出 Snipaste 截的以及其他软件截的……
@EMLVIRUS 你上面这张我觉得很清晰呀 =。=

**Comment by liulex** [comment]
@EMLVIRUS 得点开看 100% 的，图片被 github 固定了最大宽度。。

**Comment by EMLVIRUS** [comment]
![image](https://cloud.githubusercontent.com/assets/16912240/22871535/a2a7b9e4-f1ec-11e6-93d0-7743954a3322.png)
这个问题复现了 请注意看上面红色高亮域名（由规则拦截）的部分

**Comment by EMLVIRUS** [comment]
并不总是复现....

**Comment by EMLVIRUS** [comment]
@liulex 似乎只有jpg有问题 请看对比
![image](https://cloud.githubusercontent.com/assets/16912240/22911827/db8e8a16-f29c-11e6-95db-87c90a71abee.png)
![image](https://cloud.githubusercontent.com/assets/16912240/22911833/e650610e-f29c-11e6-8b87-4c44438f5f11.png)
![image](https://cloud.githubusercontent.com/assets/16912240/22911842/f12b8310-f29c-11e6-9182-9856b6be19b5.png)

**Comment by liulex** [comment]
@EMLVIRUS jpg 的话，截图质量选 `-1` 是不够的，see [FAQ](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98) 14.

或许我可以为选了 `-1` 的用户在保存 jpg 时自动帮他们用一个较高的值……
能否帮忙测试下，以上截图保存为 jpg 时，截图质量选多少可以 **刚好** 察觉不出质量损失？

**Comment by EMLVIRUS** [comment]
@liulex 由上到下依次为 100 95 90 85 80
![image](https://cloud.githubusercontent.com/assets/16912240/22912938/05598f16-f2a3-11e6-890d-b190ac4158c6.png)
![image](https://cloud.githubusercontent.com/assets/16912240/22912942/0ce1e756-f2a3-11e6-80be-5bb81284fd1d.png)
![image](https://cloud.githubusercontent.com/assets/16912240/22912945/13d4afe4-f2a3-11e6-984c-2ac90f324839.png)
![image](https://cloud.githubusercontent.com/assets/16912240/22912957/204f6f84-f2a3-11e6-9fbb-a21b3dff2b3b.png)
![image](https://cloud.githubusercontent.com/assets/16912240/22912967/2b3aef54-f2a3-11e6-8c57-893eecd64e05.png)
因此貌似应该是 80-90之间的值 不过80 85都差不多的感觉.........
75完全不用考虑了 如下
![image](https://cloud.githubusercontent.com/assets/16912240/22913045/7d745af8-f2a3-11e6-862d-4bfe9bb22299.png)

**Comment by liulex** [comment]
@EMLVIRUS 谢谢，那就用 `90` 吧~
