### ISSUE TITLE
建议：移动贴图时保持焦点在当前程序上面

### ISSUE THREAD

**Issue by h82258652** [liulex/Snipaste-Feedback#312]
现在移动贴图会将程序焦点转移至移动的贴图上面。移动完之后要重新将焦点变回使用的程序上面有点麻烦。
建议添加一个选项，将贴图的ExStyle设置为WS_EX_NOACTIVATE。

**Comment by liulex** [comment]
点了其他程序，焦点会转移，这是很正常、可以预期的行为啊，不至于会觉得麻烦吧……
WS_EX_NOACTIVATE 的作用是从其他程序点过去的时候，焦点仍然在原程序。
但贴图上有很多键盘操作的，所以也是经常需要焦点的，加上 WS_EX_NOACTIVATE 才是会让操作麻烦很多……

**Comment by h82258652** [comment]
@liulex 如果要键盘操作的话确实需要有焦点才行。
现在我面临的问题是公司的机器显示屏分辨率是比较低的，1440x900的，然后往往贴上3、4幅图。所以经常需要拖动贴图的位置（要不然挡住后面了）。
那这个建议现在先放着好了。过两三个月后我再关掉这个issue吧。

翻了下issue，其实感觉跟贴图鼠标穿透和透明度有点异曲同工，都是为了防止遮挡。:smile:

**Comment by liulex** [comment]
如果暂时不需要贴图，推荐 <kbd>Shift</kbd> + <kbd>F3</kbd> 来暂时隐藏。
单屏的时候确实没什么空间留给贴图。。😅
