### ISSUE TITLE
建议: 调整 "PIN TO SCREEN" 功能透明度

### ISSUE THREAD

**Issue by KayLeung** [liulex/Snipaste-Feedback#314]
"PIN TO SCREEN" 功能，如果可以增加右键即时调整透明度更好

**Comment by liulex** [comment]
用按键吧，暂时不打算增加菜单项。
https://docs.snipaste.com/#/zh-cn/getting-started#设置贴图透明度

**Comment by KayLeung** [comment]
谢谢，之前没有发现快速键
