### ISSUE TITLE
按住左键点击贴图，并通过AWSD移动贴图时反应迟缓

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#315]
在需要移动贴图时，可以按住鼠标左键点击贴图，并按awsd键来移动贴图。
但在鼠标点击后立即按awsd来移动贴图时，在前面的一段时间内，贴图没有移动，只有鼠标指针在移动。
希望能改进贴图移动的反应速度，可以即时响应awsd移动指令。

**Comment by liulex** [comment]
我在实现的时候也发现了这个，这个间隔应该是系统控制的，没法缩短。
其他普通窗口也支持按住鼠标左键+方向键来移动窗口，测试一下你会发现，也是有一小段延迟的。
当然我也没深入去研究，如果谁有 hack 的办法，欢迎指教 :)

**Comment by toryln** [comment]
确实，窗口在鼠标左键按住，大概0.5秒左右后指针会闪一下，之后才会响应方向键的移动。

不过我在测试过程中发现，在按住左键点击贴图时，如果**顺便**拖动鼠标移动即使一小点距离，然后马上按AWSD来移动贴图，AWSD的指令也能被立即响应。对于其他窗口也一样可以即时响应方向键的移动。

不知道能否利用这点特性，让Snipaste检测左键是否按住一段时间（比如0.2秒），如果0.2秒后还按住，则模拟用户移动鼠标几个像素距离（可以让指针变成手型，使贴图移动一小段距离的动作，看起来就像抓住了贴图），以便其后可以立即响应AWSD的指令。

不知道这个想法能否绕过windows的限制，不过即使不能实现，以后使用awsd来移动贴图时，先用鼠标移动一下先也可以了。

**Comment by liulex** [comment]
试出办法了，不过不确定是否适配各个系统。
已知 XP 就不行（是之前就不行，不是加了这个补丁之后才不行），但我不打算折腾 XP 了。。。
