### ISSUE TITLE
不支持滚屏截图，对于带滚动条的文档或者网页不能直接截图？

### ISSUE THREAD

**Issue by jasonshaw** [liulex/Snipaste-Feedback#316]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by jasonshaw** [comment]
现在觉得这个工具可以直接涂鸦很赞，但是唯一就是不能滚屏截图和录制gif或者视频，而fastcapture可以很好的滚屏，虽然有时候会带虚影，这个工具能很好的解决这个，那么fc就可以退役了

**Comment by GregAMO** [comment]
see #19
