### ISSUE TITLE
高 dpi 下，Chrome 窗口中的控件（如网页区、Tab 等）边界识别不准确

### ISSUE THREAD

**Issue by be5invis** [liulex/Snipaste-Feedback#318]
![image](https://cloud.githubusercontent.com/assets/240091/22021419/283de3e4-dcf8-11e6-9141-f1ee0f2a73dd.png)
![image](https://cloud.githubusercontent.com/assets/240091/22021453/6f2934f2-dcf8-11e6-90b5-1cac4437ba30.png)

**Comment by liulex** [comment]
这是一个已知问题：https://github.com/liulex/Snipaste-Feedback/wiki/故障排除#截图时无法自动选取-chrome-浏览器窗口的页面元素
其实是 Chrome 的锅，或者我以后用另一套 API 重写一遍……
