### ISSUE TITLE
双屏幕无法在副屏激活截图

### ISSUE THREAD

**Issue by viperasi** [liulex/Snipaste-Feedback#319]
只能在主屏激活截图操作，副屏无法截图。
双屏设置：副屏不显示任务栏，扩展双屏。
症状：副屏变暗，主屏出现截图界面，但无法移动到副屏；拖动一个小区域依然无法拖动到副屏；鼠标能到副屏但截图界面无法过去。

**Comment by liulex** [comment]
请问 Snipaste 版本？

**Comment by viperasi** [comment]
好吧，原来已经更新了，我还在用1.6(2016.08.10) ，以为有自动更新，都忘记更新版本。
抱歉，打扰了。
