### ISSUE TITLE
最新版本截图时背景黑色遮罩出现异常

### ISSUE THREAD

**Issue by miaowm5** [liulex/Snipaste-Feedback#320]
![snipaste_20170120_095906](https://cloud.githubusercontent.com/assets/7985604/22132920/0afb042c-def8-11e6-9ae3-58fbc4cbfd7b.png)

如图所示，只要在截图时就会出现，黑色遮罩只在鼠标移动时才会显示出来，鼠标（或截图框）未经过的地方黑色遮罩没显示
之前的版本中背景的黑色遮罩是正常的，这几天更新到最新版以后才出现了这个问题，但因为我跨了多个版本更新，所以并不知道这个问题具体是哪个版本开始出现的

===

更改了一下设置，发现在设置中开启 自动检测窗口 时黑色遮罩也是正常的

**Comment by liulex** [comment]
谢谢反馈，该 bug 是 1.11.1 不小心引进的，之前有人反馈过：#317
目前已经修复，请等待下版本更新 😄
