### ISSUE TITLE
无法更新的问题

### ISSUE THREAD

**Issue by Wsuika** [liulex/Snipaste-Feedback#322]
软件的版本是1.11.1。之前用的是较老的版本0.9几。手动更新的。
系统是win10 1607 原来是1511也一直有这个问题
应用程序每次开机都能检测到更新，但是直接点击消息没有任何反应。
在托盘右键菜单里点击更新新版，也没反应。
进入到首选项里，在更新选项卡里面点检查更新的按钮，正在检查一下很快就没了，没有什么东西弹出来。关掉不管每天开机还是会弹消息。更新又只能手动。

**Comment by liulex** [comment]
手动重启 Snipaste 即可顺利更新，1.11.2 已修复该问题。
谢谢反馈。
