### ISSUE TITLE
1.11.3 （XP 版） "Snipaste.exe - 无法找到入口，无法定位程序输入点 GetDynamicTimeZoneInformation 于动态链接库 KERNEL32.dll 上。"

### ISSUE THREAD

**Issue by Esec** [liulex/Snipaste-Feedback#325]
#129 1.22.2运行正常，跟从提示更新到1.22.3后运行失败，首选项>更新 里没有选中“包括 beta 版”
我怀疑我正在用假的snipaste【严肃脸

**Comment by liulex** [comment]
谢谢反馈！这版加了 [spdlog](https://github.com/gabime/spdlog)，确实忘了测试 XP 了……

**Comment by liulex** [comment]
有另一个问题不太好修，我先把 XP 的版本回退了，你去官网下载然后替换 exe 吧，过完年先…… 😂

**Comment by Esec** [comment]
大大新年快乐~

-------- Original message --------
From: Le Liu
Date:2017/01/27 19:45 (GMT+08:00)
To: liulex/Snipaste-Feedback
Cc: Esec <0w0@live.cn>,Author
Subject: Re: [liulex/Snipaste-Feedback] 1.11.3 （XP 版） "Snipaste.exe - 无法找到入口，无法定位程序输入点 GetDynamicTimeZoneInformation 于动态链接库 KERNEL32.dll 上。" (#325)


有另一个问题不太好修，我先把 XP 的版本回退了，你去官网下载然后替换 exe 吧，过完年先…… ??

―

**Comment by liulex** [comment]
@Esec 新年快乐~ XP 版已经暴力修复。。
