### ISSUE TITLE
建议：添加 「以命令行的方式对图片格式进行转换」 的支持

### ISSUE THREAD

**Issue by ZetaoYang** [liulex/Snipaste-Feedback#326]
需求：
我呢，有一个自己的个人独立博客，需要用 Markdown 写博文，有时需要放几个截图在网页上，我需要把图片的格式转成 「渐进式的 JPEG」 (Progressive Jpeg) 或者其他格式，比如 Png,Webp,Ico等等吧，平时都是用在线转换或者自己写的 Python 脚本来转换，太不方便了。于是就希望 能在终端中用 snipaste 直接以命令行转换图片格式。

示例：
snipaste.exe --convert 源文件 [参数] 目标文件
snipaste.exe --convert  a.jpg a.png

特别希望刘大大能够添加 「jpeg 格式图片转为 progressive jpeg」。

**Comment by septs** [comment]
> Snipaste 三个功能：贴图、截图、标注。
> 你提的需求和这三个都无关，所以是不会考虑的。

see https://github.com/liulex/Snipaste-Feedback/issues/120#issuecomment-247294758

**Comment by liulex** [comment]
@ZetaoYang 确实没看出你提的和 Snipaste 有什么关系……
就只是一个命令行方式的图片格式转换吧，这个不是很多现成工具吗？比如 ImageMagick...
如果是把截图/贴图保存成特定格式，那才和 Snipaste 有关系……
