### ISSUE TITLE
pdf ownerguard 支持

### ISSUE THREAD

**Issue by yuuuxt** [liulex/Snipaste-Feedback#330]
发现一个使用上的问题: 
http://www.armjisoft.com/?page=licensingsystems 

pdf ownerguard 似乎可以限制截屏, 当系统中打开了被pdf ownerguard 保护的pdf后, 截图的ctrl+c就无效了, 系统本身的print screen也失效了,但是截图的ctrl+s还是有效的; 贴图功能也是有效的;

用ditto看, 似乎该软件限制了图片到剪贴板? 但是随意google一个图片, 右键复制还是能进入剪贴板的; 所以失效的只是截图 -> ctrl+c 的功能; 

希望能针对这种情况做一下处理, 使软件功能恢复正常; 或提供一些建议, 谢谢:)

---
更新: 发现取消勾选"以windows bitmap 格式复制图片"后即可使用 :)
![image](https://cloud.githubusercontent.com/assets/3153534/22603568/eca82b3a-ea82-11e6-9de8-bbd6390319ab.png)

**Comment by septs** [comment]
这个问题不应该被处理 这是 pdf ownerguard 的行为设定
（根据 #151 作者仅会解决因第三方原因导致的意外退出问题）

**Comment by yuuuxt** [comment]
并非与 #151 同类型的问题, 已自己找到解决办法, 供参考.

**Comment by liulex** [comment]
谢谢你提供的详细描述和解决办法。
涉及版权的问题，Snipaste 不该做针对性的破解。
不过，这个 pdf ownerguard 看起来就像个摆设，导致根本不用做针对性处理也能绕过。。 😂

**Comment by yuuuxt** [comment]
本意不是破解，而是在打开了被保护的PDF以后，整个系统的截图功能都给屏蔽了，做别的事情很不方便，严重影响使用体验…

**Comment by GitHub7796** [comment]
qq自带的截图倒是可以不被屏蔽
