### ISSUE TITLE
特定场景下截屏热键失效

### ISSUE THREAD

**Issue by brantxia** [liulex/Snipaste-Feedback#331]
最新的win10企业版，打开网络共享中心，查看WLAN属性或者本地连接属性，窗口处于激活状态时，按下 全局快捷键的截屏（我设置成PrtSc）无法激发截屏功能，此时只能点击状态栏图标

**Comment by liulex** [comment]
热键失效都是权限问题：[故障排除](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%95%85%E9%9A%9C%E6%8E%92%E9%99%A4#%E6%9C%89%E6%97%B6%E5%80%99%E5%BF%AB%E6%8D%B7%E9%94%AE%E4%B8%8D%E5%93%8D%E5%BA%94)。
