### ISSUE TITLE
希望加入“延时截图”和“滚动截图（网页长截图）”的功能。

### ISSUE THREAD

**Issue by yu4204314222** [liulex/Snipaste-Feedback#332]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by GregAMO** [comment]
- 「延时截图」功能已存在，查看首选项 - 热键，此软件最新版本为1.11.3
- 「滚动截图」See #19 (在 #282 列出了大部分已收集建议 )
- 以后注意下不用使用默认模版描述啦

**Comment by septs** [comment]
2. 与 #19 重复
