### ISSUE TITLE
更新失败

### ISSUE THREAD

**Issue by wocala** [liulex/Snipaste-Feedback#333]
正在重试...
正在重定向...
正在重定向...
下载完毕.
正在将已下载文件写入到 C:/Users/*****/Dropbox/软件/Snipaste-1.11.0-x64/4de26e74-a8e6-4f4d-a930-bcaebf9d3de9.zip
错误: Failed to open archive file: -1000

文件夹中有一个文件名为4de26e74-a8e6-4f4d-a930-bcaebf9d3de9.zip.tm8760，修改后缀为zip后可以正常打开
请帮助解决，非常感谢~

**Comment by liulex** [comment]
我注意到你之前也提过一个同样的 issue #267，请问是每次更新都这样吗？

**Comment by liulex** [comment]
应该是和 Dropbox 有关，Snipaste 将 *.zip.tm8760 改名为 *.zip 之后，Dropbox 又把它改回去了；或者是 Snipaste 在尝试将它改名的时候，被 Dropbox 干预了导致没有改名成功。
应该也是概率性的，我放到 Dropbox 目录也没能重现。

下个版本我还是直接写文件吧，不使用额外缓存了。

**Comment by wocala** [comment]
嗯，最近都是这样的。

**Comment by ZetaoYang** [comment]
也许**增量更新**好一些。
