### ISSUE TITLE
Esc的作用

### ISSUE THREAD

**Issue by BianChengNan** [liulex/Snipaste-Feedback#335]
如果当前正在编辑一个标注，按Esc能否只是退出这个标注呢而不是退出本次截图呢？直接退出本次截图有些别扭。qq这个功能个人感觉就比较别扭！

**Comment by liulex** [comment]
留 <kbd>Esc</kbd> 作为可以任意时候中止截图的快捷键是有必要的。
标注的时候按 <kbd>Ctrl</kbd> + <kbd>Z</kbd> 即可。

**Comment by BianChengNan** [comment]
不是说Esc不作为终止截图的快捷键，是在编辑标注的时候按一下Esc先退出编辑，再按一下Esc才终止截图。
因为如果按一次Esc没终止截图的话，绝大多数人还会再按一次的，而且一般情况下最多按两次Esc就可以退出了

**Comment by liulex** [comment]
用 <kbd>Esc</kbs> 作为取消当前标注不太直观，<kbd>Esc</kbs> 通常是关闭或退出的意思。
比如在贴图标注的时候，按下 <kbd>Esc</kbs> 是退出标注（关闭工具条），再按下则关闭贴图，这种才比较直观。
