### ISSUE TITLE
线条，矩形框的二次编辑

### ISSUE THREAD

**Issue by BianChengNan** [liulex/Snipaste-Feedback#336]
能否像文字标注那样，也可以重新编辑矩形框，线条等其它标注呢？？？（貌似已经在考虑中了？）

**Comment by GregAMO** [comment]
请查看#79 中作者 liulex 的回答
> 对文字的直接二次编辑已在 1.10.2 支持。
其他形状的也已经实现，不过只对未来的专业版开放。
