### ISSUE TITLE
贴图 按住ctrl复制一份

### ISSUE THREAD

**Issue by BianChengNan** [liulex/Snipaste-Feedback#339]
按住ctrl，并用鼠标拖动贴图，能否复制一份，就像在同一个目录下复制文件那样？

**Comment by GregAMO** [comment]
目前你可以：对此贴图 Ctrl+C 或 右键复制图像，然后按贴图快捷键

**Comment by liulex** [comment]
@GregAMO 相同的图像不会被贴出来。
以后的专业版可以拷贝贴图，包括标注记录。
