### ISSUE TITLE
快捷键绑定问题

### ISSUE THREAD

**Issue by quericy** [liulex/Snipaste-Feedback#34]
将**贴图快捷键**修改Alt+F3以后，并没有和其他任何快捷键冲突：

![图1](http://i.imgur.com/B19UyEH.png)

但是每次重启计算机以后，**贴图快捷键**都会显示为**冲突×** :

![图2](http://i.imgur.com/DTiDG2O.png)

再手动设置一次又可以正常使用:

![图1](http://i.imgur.com/B19UyEH.png)

**Comment by liulex** [comment]
你好，1.5 新版已修复此问题。

**Comment by quericy** [comment]
感谢回复，确实，发了issue没多久就看到你的最新版本了~~
