### ISSUE TITLE
截图：自动选中元素

### ISSUE THREAD

**Issue by BianChengNan** [liulex/Snipaste-Feedback#344]
截图开始后，可以通过鼠标移动来选中小元素，这功能很赞，但是可以有个小小的改进。
某些对话框中，不能选中最外侧的对话框，只能选中其中的小元素（按钮啦，标题栏啦这些），而不能很快的选中对话框，而往往对话框是比较关心的。

建议：按住ctrl或者其它的快捷键，可以扩展当前选取到父对象。按一次向上扩展一级，如果可以反向选择那更好了！

**Comment by GregAMO** [comment]
请查看 `首选项 - 热键 - 内置快捷键列表 `
其中有 Tab：切换检测窗口 \ 检测界面元素

**Comment by liulex** [comment]
专业版已经实现了该功能，通过滚轮可以选取父元素/子元素。
