### ISSUE TITLE
贴图：穿透功能

### ISSUE THREAD

**Issue by BianChengNan** [liulex/Snipaste-Feedback#346]
这个功能是针对所有贴图的？为啥我在一个贴图上开启穿透，其它贴图也穿透了？是否应该区别对待呢？

开启穿透后，重启系统回来不穿透了，这应该是个bug？
snipaste(x64)1.11.3 
win10 x64

**Comment by GregAMO** [comment]
目前的鼠标穿透就是针对 全部贴图 的
单个贴图鼠标穿透的讨论 可见 #206 
期待提出更好的解决方案

**Comment by BianChengNan** [comment]
@liulex 不知道我在#206里说的是否看到，可以参考

**Comment by liulex** [comment]
@BianChengNan 多选操作以后会支持的（已经保留了 <kbd>Ctrl</kbd> +<kbd>单击</kbd> 这个操作）。
至于单独的穿透，我不希望为此再分配一个全局快捷键。

**Comment by BianChengNan** [comment]
@liulex 我想表达的意思是，针对选中的贴图才进行穿透操作，如果多选足够方便的话，不必要再设置一个快捷键，还用原来的快捷键就可以了！

**Comment by liulex** [comment]
@BianChengNan 
意思是，如果有选中，按下快捷键就使其穿透；如果没有选中，就解除所有穿透？
这样的确不错，毕竟我们往往只希望某张贴图穿透。😄

**Comment by BianChengNan** [comment]
@liulex 对，就是这个意思

**Comment by BianChengNan** [comment]
@liulex 对于其它操作都可以效仿，比如透明度，大小啥的
