### ISSUE TITLE
图文混排的情况下，贴图只能显示文字，不能显示图片

### ISSUE THREAD

**Issue by brucmao** [liulex/Snipaste-Feedback#347]
目前单独复制文字或者单独复制图片，使用贴图可以正常显示。
但是如果网页是图文混排的情况，使用贴图，文字可以显示，图片不能正常显示。

如下图
https://ooo.0o0.ooo/2017/02/13/58a13910c6b1c.png

**Comment by liulex** [comment]
同 #161。
