### ISSUE TITLE
bug:快速保存快捷键失效

### ISSUE THREAD

**Issue by BianChengNan** [liulex/Snipaste-Feedback#349]
如果其他软件（为知笔记）占用了快速保存的快捷键的时候，快速保存功能会失效！

关键是按完ctrl+shift+S后，我的截图操作自动完成了，但是并没有保存。

win10 x64 

snipaste x64 1.11.3

**Comment by septs** [comment]
我认为用户有意设置快捷键并发生冲突
该问题属于用户自身配置导致的可用性问题

**Comment by BianChengNan** [comment]
@septs 确实是冲突了，但是这种问题避免不了，现在的情况是虽然冲突了，但是应该响应到相关的按键了，但是后续处理上出了问题，即使不能完成操作，可以给出一个提示！不要静默的退出了！！！

**Comment by liulex** [comment]
@BianChengNan 你是在为知笔记里将 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd> 设为了全局快捷键？
其他程序是无法再收到该按键的，因为会被注册了全局的那个程序先捕获。
Snipaste 截图退出，是因为有其他程序被激活了，所以自动退出，而不是它响应了 <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>。
你可以取消勾选“截图时如果有其他程序窗口被激活，自动退出截图”。（不过刚测试了下这个选项失效了，下版本会修复）

**Comment by BianChengNan** [comment]
@liulex 截图时如果有其他程序窗口被激活，自动退出截图 这个是未勾选状态，难道默认是开启的？那说的通了，有可能是这样的
