### ISSUE TITLE
建议：在截图编辑功能当中加入更多样式

### ISSUE THREAD

**Issue by 7starsseeker** [liulex/Snipaste-Feedback#35]
我之前在用faststone capture，那个的截图编辑很厉害……有些功能个人觉得可以引入到这边
1.截图编辑可以提供单独窗口显示（可选）；
2.截图编辑样式加入选中部位模糊和选中部位高亮（见附图），并且可以自己定义模糊和高亮程度
![2016-08-08_125130](https://cloud.githubusercontent.com/assets/18816083/17469552/ee45935a-5d66-11e6-9745-1fca0ecca540.png)
![2016-08-08_125155](https://cloud.githubusercontent.com/assets/18816083/17469556/f413321a-5d66-11e6-9195-b5aaa95e150d.png)

大概就是这两个建议了，多谢！

**Comment by 7starsseeker** [comment]
因为现在图片编辑当中只有马赛克这一种样式……

**Comment by liulex** [comment]
你好，现在还有模糊这种样式哦，点击一下那个马赛克的预览图标即可切换过去 :-)
以后会加入反向马赛克/反向模糊的功能。
至于其他标注的样式，应该是不会考虑了，毕竟 Snipaste 的主打功能是**贴图**。
