### ISSUE TITLE
快捷键占用但是在快捷键列表并没有找到有相应的快捷键Ctrl+F3

### ISSUE THREAD

**Issue by msccreater** [liulex/Snipaste-Feedback#350]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---
快捷键占用但是在快捷键列表并没有找到有相应的快捷键Ctrl+F3

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
请详细描述一下……
