### ISSUE TITLE
[建议]是否可以提供固定长宽比和固定尺寸的截图？

### ISSUE THREAD

**Issue by qianliwg** [liulex/Snipaste-Feedback#353]
比如我在写微信公众文章时上传图片的尺寸一般会选择相同尺寸，或者做Gif动画时会固定尺寸。

顺便提一下，能不能后面再加上录制GIF的功能呢？

**Comment by G-monitor** [comment]
图片大小问题：
好像作者有收到这类反馈，但是现在貌似还是得手动调整大小
以前收到的类似建议：#198 #28 

GIF问题：https://github.com/liulex/Snipaste-Feedback/issues/282#issuecomment-268239323
> GIF 录制
无计划。请使用 LICEcap 或 ScreenToGif 等软件。

**Comment by GregAMO** [comment]
固定尺寸，目前可以使用[命令行选项](https://docs.snipaste.com/#/zh-cn/command-line-options)
