### ISSUE TITLE
按Fn组合键时会触发热键

### ISSUE THREAD

**Issue by Bimos** [liulex/Snipaste-Feedback#355]
按`Fn+F3`时，触发了`F3`热键。

**Comment by liulex** [comment]
Snipaste 未开启时，在其他程序按 <kbd>Fn</kbd> + <kdb>F3</kbd> 同样会触发 <kdb>F3</kbd>。

**Comment by Bimos** [comment]
刚刚试了几个软件，包括一个用Qt写的软件sqlite Studio， 没有这个现象。

**Comment by Bimos** [comment]
刚刚又试了Snipaste又不会触发了。。

**Comment by liulex** [comment]
我倒是几乎所有软件都把 <kbd>Fn</kbd> + <kbd>F3</kbd> 当 <kbd>F3</kbd> 了（包括 vs, Firefox, Chrome, Sublime Text, Total Commander ...)，<kbd>F1</kbd> 和 <kbd>F2</kbd> 则不会，不太清楚什么原理。。。
