### ISSUE TITLE
描边能否增加白色描边？？

### ISSUE THREAD

**Issue by Cader** [liulex/Snipaste-Feedback#356]
如题，当截图内容是暗色的时候，需要白色描边才能醒目一些。

**Comment by GregAMO** [comment]
如果你说的是 截图状态下 表示 截图范围 的边框
它的颜色是跟随 首选项 的 主题色 的

**Comment by Cader** [comment]
抱歉，少打了两个字，我想建议的是，截图后添加文字 ，文字描边能否增加白色描边

**Comment by GregAMO** [comment]
此建议已收录至 #282 「已收集的建议」
你可以用 :+1: 为那个条目投票
> 设置背景色、文字描边颜色 #83
