### ISSUE TITLE
截图时做文字笔记打不出中文

### ISSUE THREAD

**Issue by stelvetica** [liulex/Snipaste-Feedback#358]
如题

**Comment by orzFly** [comment]
1. Snipaste 版本
2. 操作系统版本
3. 输入法名称、版本
4. 输入法是 IME 模式还是 TSF 模式？

**Comment by GregAMO** [comment]
之前也有过一个讨论#165 
可参考一下那个情况，
> Win7x64位 + 手心 可以尝试开启
「设置 - 皮肤 - 显示设置 - 单行模式」

**Comment by liulex** [comment]
@stelvetica 
之前 @GregAMO 帮忙测试过，确实特定系统下特定输入法有问题。
只能从输入法方面解决了（改变输入法设置/更换输入法）……

**Comment by stelvetica** [comment]
好，现在又可以打字了，不知道什么原因。同时反馈另一个事情：超过截图范围外的字，复制粘贴不被保存下来。

发自刘谡

在 2017年3月4日，17:08，Le Liu <notifications@github.com<mailto:notifications@github.com>> 写道：


@stelvetica<https://github.com/stelvetica>
之前 @GregAMO<https://github.com/GregAMO> 帮忙测试过，确实特定系统下特定输入法有问题。
只能从输入法方面解决了（改变输入法设置/更换输入法）……

**Comment by liulex** [comment]
@stelvetica 抱歉，没能理解你描述的情形。。

**Comment by stelvetica** [comment]
是这个意思，截图时候打字打出截图范围的的文字不保存

截图时候的样子：
[计算机生成了可选文字: 丨 2  辽  7  Cig: 2 7  ・ 60  1 ・ 67  欧 非  7  1 ・  0 ・  仇  0  0 ． 02 ％  8 ％  09 ％  ・ 09 ％  ・ 03 ％  成 交 金 额  29 ・ 91 亻 乙  51 20 亿  12 ・ 41 乙  21 08 亿  20 ・ 15 亿  2 ・ 97 亿  11 ・ 95 亻 乙  80 ． b 乙  年 初 至 今  4 ・ 14 ％  0 、 22 ％  4 ・ 24 ％  285 ％  4 、 02 ％  3 ・ 52 ％  序 号  1  2  3  4  5  6  7  8  一 ^ 300 期  代 码  801230  801770  801890  801210  801160  801080  801760  801140  名 称  综 合 伸 万 ）  通 信 伸 万 ）  1 伸 ）  休 闲 服 务 伸 万 ） 工  公 用 事 业 伸 万 ）  电 子 伸 万 ）  传 媒 伸 万 ）  轻 工 制 造 伸 万 ）  筲 0 ／ 山 盲  美 洲 市 炀  L76 亿  200g 61  1 4 ． 77  2 匕 上 0  Z 寻 0 ．  321096  1199 6  307 ￡ 3  0  申 万 一 行 丑  念 块 主 题 行 业 中 信 一 级 行 业  000001 止 证 综 指 ] 3233 ・ 51 娌 0  3235  3234  沪 深 成 交  3248 《  2 过  SAC 行 丑 指  现 伯  10 ・ 05 ％  6 ・ 93 ％  3 ・ 77 ％  2 ・ 77 ％  2 ・ 09 ％  t41 ％  1 ・ 21 ％  0 ・ 97 ％  1 ・ 15 ％  t11 ％  成 交 里  235 ・ 60 万  160 ・ 99 万  1415 ・ 59 万  1683 ・ 03 万  126 ・ 08 万  105 ・ 30 万  30 刀 万  年 初 至 今  46 ・ 65 ％  2 ・ 17 ％  7 ・ ％  1 ・ 37 ％  7 ・ 32 ％  5 ・ 46 ％  7 ・ 71 ％  11 ・ 12 ％  1 ・ 60 ％  2 ・ 77 ％  1 ・ 25 ％  6 ・ 35 ％  0 图 范 围 内 的 文 字 截 图 范 围 外 的 文 、  3 ・ 32 万  3 ・ 1 历  169 ・ 51 万  50 ・ 91 万  42 ・ 9 历  35 ・ 8  B  的 524 ， 27  3234  3234  3234  3233  3233  3233  23 ・ 93 亿  17 ， 9  刂 山 1 就  刂 ． 刂 1  刂 ． 刂 2  刂 2  23 ， 93 亿  17 ， 95 亿  11.97 亿  5 ， 98 亿  市  52 思  5 2 周 《  A  Microsoft YaHei U 丨  丨 ” × H  0 囗 0 囗 囗 囗 囗 囗 0 囗 《  创 丑 祈 我 的 自 选 股  的 1 蔗 证 成 指 ]  13 ： 刂 刂 13 ： 3 刂 1 中 0 刂 1 中 30 15 ： 刂 0  0 冫 凵 凵 上 辶 生 凵 上 0 。 凵 上 0  刂 的 2  土 rd 讯  Windi-R 讯  沪 指 小 低 开 ， 人 工 智 能 念 持 续 造 好  ！ 商 品 伯 继 续 扩 容 ， 瓦 楞 纸 6 个 月 不 到 领 6]
截图结果：
[cid:image006.png@01D29726.4E3A4A00]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Le Liu<mailto:notifications@github.com>
发送时间: 2017年3月4日 22:28
收件人: liulex/Snipaste-Feedback<mailto:Snipaste-Feedback@noreply.github.com>
抄送: stelvetica<mailto:stelvetica@live.cn>; Mention<mailto:mention@noreply.github.com>
主题: Re: [liulex/Snipaste-Feedback] 截图时做文字笔记打不出中文 (#358)


@stelvetica<https://github.com/stelvetica> 抱歉，没能理解你描述的情形。。

―

**Comment by GregAMO** [comment]
请直接来GitHub 评论。
邮件不仅附带一堆小尾巴，
带来隐私泄露
而且不能传送图片给 GitHub
