### ISSUE TITLE
复制内容，按F3生成的图片，可否上下左右边距留大些？

### ISSUE THREAD

**Issue by congcong0806** [liulex/Snipaste-Feedback#359]
图片在下方，现在的边距很小！谢谢！
[点击查看图片](http://ww1.sinaimg.cn/large/9b84e6acgy1fd8tk7rbk0j20go2lc7aw)

**Comment by liulex** [comment]
之前的版本，对于 Html 转的图片没有加边距，纯文本转的有边距。
下个版本会统一并给出设置：
![default](https://cloud.githubusercontent.com/assets/2010459/23509560/310ee25a-ff91-11e6-9978-5f831284d7ff.png)
