### ISSUE TITLE
设置含有F2的快捷键会导致在Windows资源管理器下无法使用F2进行重命名

### ISSUE THREAD

**Issue by lenppqq** [liulex/Snipaste-Feedback#36]
把一个快捷键设为Alt+F2后，Windows资源管理器下无法使用F2进行重命名
清除Alt+F2后，即可使用F2进行重命名

**Comment by liulex** [comment]
更新了 1.5 版吗？
之前的版本确实有些问题，更新后应该可以解决。
我刚刚按照你说的测试了下，没有问题。

**Comment by lenppqq** [comment]
的确忘记更新了
