### ISSUE TITLE
性能：感觉新版本反应变慢了

### ISSUE THREAD

**Issue by IceWeet** [liulex/Snipaste-Feedback#360]
不知道是不是做过性能优化，总感觉新版本对快捷键的响应变慢了（直接点击托盘图标似乎并不慢）。

如果是做过性能优化，想建议把是否优化性能作为一个选项：

- 允许机器配置比较好的用户选择用更多的机器资源消耗换效率；
- 对于配置不那么高的用户，则可以选择用可能稍微慢一点的响应，换取对机器资源的消耗变低。

**Comment by StarryVoid** [comment]
@IceWeet 的确有这个体验。。我以为是ssd变慢了

**Comment by liulex** [comment]
@IceWeet @StarryVoid 
点击托盘图标和通过快捷键进行截图，执行的是同一个函数。
如果有快慢差别，就是这两个动作哪个更快执行到那个函数。
但这个响应速度不是我能控制的……（除非我强制让点击图标等一会再执行截图函数 🌚 

如果追求更高性能，可以尝试一下[设置](https://github.com/liulex/Snipaste-Feedback/wiki/%E9%AB%98%E7%BA%A7%E8%AE%BE%E7%BD%AE) `General/high_process_priority` 为 `true`.

**Comment by joshatt** [comment]
没注意什么版本, 感觉一直都是慢----F1按下后,经常10秒才开始截图. 按liulex说的, 提高优先级后, 特别好用了, 立即开始截图

**Comment by shiyu619** [comment]
请问有没有什么解决的方法呢

**Comment by cooper1x** [comment]
@liulex win10设置优先级为3，还是会有2s的延迟

**Comment by git10135405** [comment]
我也遇到这个问题 有时候延迟很久
