### ISSUE TITLE
滚屏截图

### ISSUE THREAD

**Issue by CyshallChan** [liulex/Snipaste-Feedback#361]
作者有考虑滚屏截图吗？
有的话，大概啥时候会出阿，感觉这个功能还是蛮有用的。

**Comment by ZetaoYang** [comment]
@CyshallChan 滚动截屏 你可以先用 FastStoneCapture。

**Comment by GregAMO** [comment]
See #19 
实际上截图软件里面实现这个功能的真的很多啊…

**Comment by CyshallChan** [comment]
@GregAMO 但是我只想用这款软件。
