### ISSUE TITLE
扩大截屏自动选定区域？

### ISSUE THREAD

**Issue by JimAmuro** [liulex/Snipaste-Feedback#362]
我非常喜欢snipaste的自动选定区域，很准，但是这也是个问题，比如我想截整个chrome书签栏，但是如果我放在某个书签上面，自动选定区域就只有那个书签，书签栏如果被书签占满的话我必须找一个很边边角角的地方才能截整个书签栏，所以我想能不能搞一个类似于编辑器里面expand selection的扩大自动选定区域的功能，比如放在一个书签上，按某个键就可以扩大范围，就不用找很tricky的地方了。谢谢！

**Comment by EMLVIRUS** [comment]
good idea!

**Comment by liulex** [comment]
谢谢建议，该功能已经实现，是将来专业版的特性之一 😉 
![pro_detect](https://cloud.githubusercontent.com/assets/2010459/23576470/3bee437c-00e1-11e7-8337-5f62ac73f130.gif)
