### ISSUE TITLE
[Bug]在截图上绘制内容，特定情况下鼠标图形显示错误

### ISSUE THREAD

**Issue by G-monitor** [liulex/Snipaste-Feedback#363]
重现步骤：
1. 截图、圈出截图范围
1. 选择任意鼠标形状不是由系统提供的绘制工具（比如马赛克）
1. 拖动截图范围线（调整截图大小）
1. 松开鼠标，把鼠标移回截图范围内

把鼠标挪出截图范围再挪回来就又正常了
当前使用的版本：1.12-Beta1

**Comment by liulex** [comment]
赞！
