### ISSUE TITLE
Border around snippet

### ISSUE THREAD

**Issue by hanzelmannes** [liulex/Snipaste-Feedback#365]
Feature request

It would be nice if it is possible to automaticly place a border around the snippet. Let user choose in setup: color and thickness.

**Comment by G-monitor** [comment]
https://github.com/liulex/Snipaste-Feedback/issues/197#issuecomment-257551728 
>以后交给插件系统，包括添加外围阴影。

This feature will be implemented by plugins(or extension) later.
(It's been four months..... :( sad )

**Comment by liulex** [comment]
I may offer an entry "Copy with shadow" / "Save with shadow" in the context menu of the image window, before the plugin system comes out, if you are interested...
