### ISSUE TITLE
剪切板，文字转图片，HTML格式的内容，行间距有些大

### ISSUE THREAD

**Issue by congcong0806** [liulex/Snipaste-Feedback#366]
可否调小些？谢谢！
[点击查看图片](http://ww1.sinaimg.cn/large/9b84e6acgy1fdd49t7rtej21220o84bh)

**Comment by septs** [comment]
1. 请提供网页链接。
2. 您当前使用的操作系统是？
3. 您当前使用的浏览器是？

请提供以上信息以便复现该问题

**Comment by congcong0806** [comment]
1，https://mp.weixin.qq.com/s/ZH9Ll5PfKbZ2PXWqv9U4iA
2，Win 7 64bit
3，Chrome

**Comment by ZetaoYang** [comment]
发现一个 Bug 。文字转图片后，贴到桌面上 右键 复制Html 没有任何反应，反而会清空粘贴板。

**Comment by liulex** [comment]
@congcong0806 
这实际是 Qt 的 bug：https://bugreports.qt.io/browse/QTBUG-4355
它把 `<p><br /></p>` 渲染成两个空行了。

@ZetaoYang 
并非清空了剪贴板，而是只放进去了 HTML，没有纯文本。所以可以粘贴到 word，但不能粘贴到记事本等只接受纯文本的地方。不过确实是个 bug……

以上两个 bug 将在 1.12 版修复。
