### ISSUE TITLE
建議：[參數設置] 快速儲存目錄使用系統環境變數

### ISSUE THREAD

**Issue by it4u** [liulex/Snipaste-Feedback#367]
這應該不算是 Bug，所以來請求看能不能在後面版本加入：

![#1](https://github.com/it4u/Aaron/raw/master/a1.png)

* 希望可以在 [輸出] > [快速儲存], 可使用系統環境變數，方便在不同電腦，都不需要再改一次；其次 IT 人員在大量配置電腦時，也不需要一台一台改，只需在 config.ini 設置固定的環境變數即可。

![#2](https://github.com/it4u/Aaron/raw/master/a2.png)

**Comment by liulex** [comment]
很好的建议，已经加上~ 😄 
桌面的话，只需 `%desktop%` 即可。

**Comment by it4u** [comment]
感謝！請問還支持其他環境變數嗎？什麼版本會釋出呢？

**Comment by liulex** [comment]
@it4u Snipaste 1.12.
支持所有系统的环境变量。上面的 `%desktop%` 是我弄错了，这个变量是我自己以前加进系统设置里的，误以为是系统自带的了。 😅

**Comment by it4u** [comment]
瞭解了，好棒啊，請問哪個版本會釋出呢？

**Comment by it4u** [comment]
抱歉，已看到 . 1.12 已更新. 謝謝!
