### ISSUE TITLE
QQ浏览器不能截图

### ISSUE THREAD

**Issue by xin446990** [liulex/Snipaste-Feedback#37]
在qq浏览器截不了图，但是如果先截个图，把图片放在浏览器上面，点击图片（注意是点击图片，图片覆盖在浏览器上方，浏览器没最小化）然后就能使用截图了，只要把图片移开，就能截取浏览器上面的内容。是不兼容还是限制了？希望作者大大能改进，加油一直支持。

**Comment by liulex** [comment]
首先很抱歉现在才回答你的问题。
根据你的描述，我猜是因为你的 QQ 浏览器是以管理员权限打开的？
如果当前窗口是以管理员权限打开的，Snipaste 的快捷键是无法生效的，除非你也以管理员权限打开 Snipaste.
但是，我并不是在鼓励你使用管理员权限去打开 Snipaste，没有这个必要，我自己也不是用管理员权限运行的 Snipaste.
遇到这种情况，你只需要点击一下其他非管理员权限打开的窗口，或者点击一下任务栏，即可使用截图快捷键开始截图了。或者直接左键点击一下 Snipaste 的通知栏图标，也可以开始截图。

**Comment by xin446990** [comment]
应该是你说的那样，我建议你可以弄个全局快捷键，这样在别的窗口上就能正常使用了，而且貌似还可以在全屏游戏里使用

**Comment by liulex** [comment]
本来就是全局快捷键，但因为系统的权限问题，系统不允许它获得响应。
全屏游戏截图，还请使用游戏或平台自带的截图键。
