### ISSUE TITLE
在 首选项-输出 设定的 图片格式 无效

### ISSUE THREAD

**Issue by 10100010110000101010** [liulex/Snipaste-Feedback#370]
![设定的 图片格式](https://cloud.githubusercontent.com/assets/22018718/23732983/502b1634-04b1-11e7-80ba-0e0697f9fd5d.png)
系统 win10

保存至文件时：总是输出为上一次保存的类型。可能是系统原因

复制时：固定为png格式。（然后被qq压成*

以上两种情况，设置的格式都没有任何作用

**Comment by liulex** [comment]
逻辑是这样：

1. 手动保存的，每次会使用上一次保存时的后缀。
1. 快速保存/自动保存的，会使用命名规则中的后缀。

以后或许可以给第一种行为加个选项。

复制并无所谓 PNG / JPG。

**Comment by 10100010110000101010** [comment]
复制时的确是png格式呀，题图就是复制进去的

**Comment by 10100010110000101010** [comment]
我错了，是qq的问题，会把本文框的图片转成jpg

我觉得 输出为上一次保存的类型 就挺好

另，复制的截图的确是png格式呀，为什么

**Comment by liulex** [comment]
@10100010110000101010 把剪贴板中的图像转化成什么格式，是由执行粘贴的那个程序决定的。
