### ISSUE TITLE
Auto-Save does not work resp. require additional manual "save"

### ISSUE THREAD

**Issue by pstein** [liulex/Snipaste-Feedback#375]
I started (portable) Snipaste on 64bit Win 7 and enabled auto-save with an existing directory.

Now I started a Snip: I selected a windows and expected that it is automatically saved (as *.png).
Much to my surprise the selected windows stays brigth and the surrounding background dark grey and the Snipaste toolbar appears.

I am forced to manually select the tiny "save" icon to really perform the save.
As a result I have two file instances from the snapshot:

One from the manual save and one from the auto-save.

How can I immeediately, automatically save a snapshot without more manual interaction?

Whats the difference to "Quick Save" and how to start this variant?

Peter

**Comment by liulex** [comment]
I think you have misunderstood the meaning of "Auto Save".
It means to automatically save every successful screenshot (no matter it is copied or pinned or quick saved) to the target folder, as a measure of backup. NOT saving the screenshot automatically when you release the mouse buttons.

"Quick Save" is to save the screenshot to the target folder with <kbd>Ctrl</kbd> + <kbd>Shift</kbd> + <kbd>S</kbd>.

At the moment there  is no way for taking screenshots without more manual interaction. But I may introduce one in the future if there are some audience.

**Comment by pstein** [comment]
Autosaving snapshot into target folder is part of the most snipping tools.
I want to have as less overhead as possible.
I appreciate Snipaste but need urgently this autosave feature (in my sense).
Could you add this in the next release?

Thank you
Peter

**Comment by liulex** [comment]
You request can be categorized into #38 (Customize the action combination on screenshot done).

There are a lot of other features piling up but currently I have limited time for Snipaste., therefore I cannot promise you when it will be added. Sorry.
