### ISSUE TITLE
How to save an arbitrary rectangle and not a window?

### ISSUE THREAD

**Issue by pstein** [liulex/Snipaste-Feedback#376]
Selecting a windows on desktop works (on 64bit Win 7).

But assume I want to 8auto)save an arbitrary rectangle with border NOT associated with a window?

How do I do this?

I miss a hotkey entyr filed for this variant

Peter

**Comment by liulex** [comment]
Sorry, I don't quite understand what you mean... But if you want to repeatedly snip the same area on the screen, you can use the <kbd>R</kbd> key on entering snipping.

**Comment by pstein** [comment]
I mean with "rectangle snipping" a capturing of an desktop area which is not identical with an window.
Almost all other snipping tools have such an option.

Have a look a the sample on the following page:

http://www.free-screen-capture.com/how-to-screen-capture/how-to-capture-rectangle-screen.html

The red square/box/rectangle captures NOT a full window but only a fish from a bigger image.

How can I do this with SniPaste?

Peter

**Comment by liulex** [comment]
Press <kdb>F1</kbd>, then just drag and release the left mouse button.
