### ISSUE TITLE
"ALT" key not possible as part of a hotkey combination?

### ISSUE THREAD

**Issue by pstein** [liulex/Snipaste-Feedback#377]
As far as I found out a hotkey combination with "ALT" key seems to be not possible (on 64bit Win 7).

I tried 

ALT+PrtSc

for starting a snip but Snipaste does not accept it.

Can this special key be allowed in future versions?

Thank you
Peter

**Comment by liulex** [comment]
Only <kbd>Tab</kbd> and <kbd>Backsapace</kbd> are disallowed.
For other unaccepted key combinations, the only explanation is that they are held by other applications.

But if all key combinations containing <kbd>Alt</kbd> are not accepted, something may go wrong and I will look into it. Could you try other key combinations that contains <kbd>Alt</kbd> and report back?

**Comment by pstein** [comment]
Hmm, almost all ALT key combinations work except ALT+PrtSc.

I wonder which other application is blocking the ALT+PrtSc

I try to find it out
