### ISSUE TITLE
How to disable "history"?

### ISSUE THREAD

**Issue by pstein** [liulex/Snipaste-Feedback#378]
When I look at the installation directory of SnipasteI a subdirectory called "history".

I guess recent sniping activities are stored here.
I don't want this remembered.

How can I disable history and recent snips?

I found no appropriate options.

Peter

**Comment by liulex** [comment]
For snipping history:
![default](https://cloud.githubusercontent.com/assets/2010459/23792303/565c6cae-05c1-11e7-9dcc-29261f970896.png)

For image windows:
![default](https://cloud.githubusercontent.com/assets/2010459/23792331/722f23ea-05c1-11e7-98af-9cf447142064.png)
Note that you will lose all the image windows when you restart Snipaste if you disable `Auto backup`.
