### ISSUE TITLE
希望增加截图框长宽设置和锁定

### ISSUE THREAD

**Issue by ys746663912** [liulex/Snipaste-Feedback#381]
希望增加截图框长宽设置和锁定。
因为有一些截图要正方形或者固定比例的，每次手动调大小很麻烦。
比如我要截几十张600*600的图，按一下快捷键直接就截好啦、或者设置长宽比固定，拖动任意一边框来缩放截图框大小，避免手动调节慢。像素级调整可以很精准，但是达不到这个速度。

**Comment by EMLVIRUS** [comment]
好主意 建议添加到截图工具栏里 这样就可以直接输入数字

**Comment by liulex** [comment]
重复： #28 #353 

另外，重复相同尺寸截图用 <kbd>R</kbd> 即可。

**Comment by ys746663912** [comment]
好的，用R快多了，再加个长宽锁定就好了。
