### ISSUE TITLE
可不可以加个修剪裁切功能，贴图

### ISSUE THREAD

**Issue by NUKW** [liulex/Snipaste-Feedback#382]
贴图有时候截大了，直接把贴图裁小就好了
还有贴图的缩放只能固定比例缩放，加个开关就好了

**Comment by liulex** [comment]
贴图裁剪：#284 

贴图单边缩放的话，能否说明一下使用场景？

**Comment by NUKW** [comment]
好吧其实主要是修剪裁切，没找到修剪自然而然的脑子跑到可缩放上
不过单边缩放可以是缩放显示框，这样要显示一部分而另一部分有用的时候就可以先只显示一部分了，也不用裁切

**Comment by liulex** [comment]
显示图像部分区域可以用缩略图功能，#284 也提出可调整的缩略图，目前已基本实现。
