### ISSUE TITLE
希望绘图中双击保存，撤销第一次点击造成的效果

### ISSUE THREAD

**Issue by taroxd** [liulex/Snipaste-Feedback#383]
~~也就是说，希望按住鼠标后，移动至少 x 像素后才开始进行绘画。~~
在绘图模式下双击时，即使鼠标有轻微的移动，也不要把图画上去。

如果按住鼠标，移动了 1 像素就立刻开始绘制的话，在双击保存图片的时候容易出现如下的情况（下方的箭头是双击的位置）：
![image](https://cloud.githubusercontent.com/assets/6070540/24029341/4e57cd2e-0b10-11e7-8da4-ae307990f00a.png)

我鼠标 DPI 只有 2500，指针无加速度，已经很容易出现这样的误操作了。如果 DPI 更高、桌子与鼠标之间的摩擦系数更小的话，很难保证每次双击的时候指针没有位移。

telegram 相关聊天记录：
![image](https://cloud.githubusercontent.com/assets/6070540/24029348/5c66b5e2-0b10-11e7-898c-57aad49a7acf.png)

**Comment by liulex** [comment]
Done~
