### ISSUE TITLE
一些关于高分屏的问题

### ISSUE THREAD

**Issue by autodotua** [liulex/Snipaste-Feedback#384]
![2017-03-24 4](https://cloud.githubusercontent.com/assets/26277009/24281120/1b976f08-1091-11e7-8212-c009901099db.png)
如图，我的显示器分辨率是1920×1080，DPI为125%，用此软件截屏时会出现一个虚拟的窗口，经过检查，分辨率为1536×824，正好为1080P的0.8（即1/1.25）。

**Comment by liulex** [comment]
同 #318.
你的情况又有些不同，有用户跟我反映过，测试结果是多出来的这个虚拟窗口确实存在，但我这边不会妨碍到 Snipaste 的元素选取，他那边会，所以大概属于玄学……
单单解决这个意义也不大，因为高分屏的 Chrome 本身元素识别就有问题，只有等以后用 UI Automation 重写一遍了。
