### ISSUE TITLE
貼圖群組功能

### ISSUE THREAD

**Issue by allenyllee** [liulex/Snipaste-Feedback#385]
所謂的貼圖群組功能，其實有點類似 #45  + #345  
就是我可以按crtl+左鍵 點選多張貼圖，
然後在被選中的貼圖上按右鍵跳出選單，
可以將這些貼圖群組起來。
被群組的貼圖就會好像一張貼圖一樣，
滑鼠可以任意移動、放大縮小，
圖片的相對位置皆保持不變。

為什麼需要這個功能？
因為我用貼圖功能來看code 很方便，
當看到一個不知道的函數或變數型態時，
可以先跳過去把該函數/變數 的定義截圖下來，
貼在桌面上，再回到原本的地方對照著code看。
但是通常這些函數變數位置都很分散，當數量一多，
圖通通都疊在一起就變得很難找，
而且其實有些函數/變數定義是特別常用可以擺在一起看的，
所以才會想到把他們群組起來。

如果再加上貼圖編號的話，
就可以更清楚分辨這張貼圖是在哪個地方截出來的，
對照起來又更方便了。

**Comment by liulex** [comment]
其实 #345 的贴图多选，就已经包含了这个意思啦。
还是谢谢您的详细描述，这个功能会有的。
