### ISSUE TITLE
发现一个bug

### ISSUE THREAD

**Issue by l123838456** [liulex/Snipaste-Feedback#389]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---
/*
以下是我填写的：
snipaste(64 位) 
版本：1.12（20170309）
原截图快捷默认是F1，我改成F12之后没有反应，
在首选项——热键——截屏：按下F12，
鼠标点其它地方，再关闭首选项
右击通知栏小图标，可以看到菜单的截图里是显示F12，但是我按F12没有反应
再右击通知栏小图樯，选择重新启动，启动后发现热键——截屏快捷键被清空了，通知栏里的截图后面也没有F12快捷键显示
*/

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
热键是否设置成功以 首选项—热键 右边一栏的图标状态为准。
不过右键菜单中的显示确实应该保持一致，会在下一版修复，谢谢反馈~

**Comment by liulex** [comment]
@l123838456 另外，<kbd>F12</kbd> 是被 Windows 系统保留的，所以不能注册成功。

> https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309(v=vs.85).aspx
> The F12 key is reserved for use by the debugger at all times, so it should not be registered as a hot key. Even when you are not debugging an application, F12 is reserved in case a kernel-mode debugger or a just-in-time debugger is resident.
