### ISSUE TITLE
建议：截图定位参考点、屏幕贴图不置顶

### ISSUE THREAD

**Issue by misybing** [liulex/Snipaste-Feedback#391]
工具非常好用，不多说

建议

1. 截屏的时候左右上下边界给出点，方便定位参考，如图：
[https://pan.baidu.com/s/1qXOSTrQ](https://pan.baidu.com/s/1qXOSTrQ)

2. 截图贴到屏幕上可设置置顶/不置顶，以及默认置顶/不置顶
原因：临时的截图贴在屏幕顶层，在所有窗口最上面，用完即关没问题。但想将特定截图长时间放在屏幕上，如自我激励的话，女神照片，只想让她在桌面壁纸上层，能移动调整替换，而不遮挡其他使用窗口。

**Comment by liulex** [comment]
1. 一般软件在边界上画锚点，是为了表示鼠标移动到该边界附近可以调整该边界。但 Snipaste 调整截图区域的时候是无需将鼠标移动到边界上的（边界外任一点均可），所以就没有画那些锚点。不是很理解为什么能起到定位参考的作用，能解释下吗？

2. 允许不置顶的话，交互、逻辑等会复杂一些，不过确实有着一定使用的场景。以后再看看吧。

**Comment by misybing** [comment]
1. 是的，Snipaste在这点上做得更好，非常便于操作。一般软件画锚点(a)表示鼠标移动到该边界附近可以调整该边界，没问题；(b)同时也能表示了边界的中点，定位参考作用不是说对边界的定位，而是对所截取图片内容的定位，比如想截取内容左右对称的图片，左右留白相当的图片就很有用（对一般软件，边界中点四个点有用，四个拐角的点就没必要了，拐角边线相交本就是点）
建议Snipaste边线中点画一个边长为线宽的白色正方形即可，不用单独设锚点。

2. 这样的话，幸苦开发哥哥了，不过确实会很有用，这样的贴图结合桌面壁纸灵活性会非常强（另建议对设置了开机启动的用户，再开机默认保留上次贴图状态。我已经开始描绘美好的使用体验了(●'◡'●)）。

**Comment by liulex** [comment]
1. 谢谢解释，已经加上该功能：
![default](https://cloud.githubusercontent.com/assets/2010459/24584335/0e401e1e-179d-11e7-9072-b8467cc4cf4f.png)

2. 现在开机没有恢复贴图状态么？

**Comment by misybing** [comment]
1. 神速，赞！对样式更优雅的建议（对比图如下）：
`<img src="http://wx2.sinaimg.cn/mw690/a51f1b45gy1fe895sarjcj20b80audgf.jpg">`
另觉得截图边线有点宽，不知道基于什么考虑的。觉得颜色不变，宽度同下面工具条应该不错。

2. 因为置顶影响操作，没有保留贴图到关机过...刚重启测试了一下，是可以的。

**Comment by misybing** [comment]
1. 神速，赞！对样式更优雅的建议（对比图如下）：
    <img src="http://wx2.sinaimg.cn/mw690/a51f1b45gy1fe895sarjcj20b80audgf.jpg">
    另觉得截图边线有点宽，不知道基于什么考虑的。觉得颜色不变，宽度同下面工具条应该不错。

2. 因为置顶影响操作，没有保留贴图到关机过...刚重启测试了一下，是可以的。

**Comment by liulex** [comment]
@misybing 我觉得上面的好看。。
这里可以自定义边框宽度：
![default](https://cloud.githubusercontent.com/assets/2010459/24585060/df29ae30-17b3-11e7-8ac1-64ffe970abc3.png)

**Comment by misybing** [comment]
阔以，这个问题不大，有了就很好
边框宽度已改，完美

**Comment by tanshuozheYeto** [comment]
能设置优先级吗？，前后都可以的那种
