### ISSUE TITLE
windows 10下使用截图时，输入文字后，再次使用截图软件崩溃

### ISSUE THREAD

**Issue by caceng** [liulex/Snipaste-Feedback#393]
windows 10下使用截图时，输入文字后，再次使用截图软件崩溃

**Comment by caceng** [comment]
不管是32位还是64位都这样，我系统是windows 10 64位，崩溃后任务栏有图标显示，鼠标移上去，图标消失

**Comment by liulex** [comment]
谢谢反馈，请提供详细的操作步骤。
