### ISSUE TITLE
最小化贴图后多了一个Form

### ISSUE THREAD

**Issue by Jason4774** [liulex/Snipaste-Feedback#394]
![default](https://cloud.githubusercontent.com/assets/19594338/24498492/3d843576-1571-11e7-8735-99fe81c10e00.gif)
最小化贴图后多了一个Form

**Comment by liulex** [comment]
不支持最小化操作，也希望不要这样做，因为是未经测试的行为，可能造成贴图丢失、备份/恢复失败等问题。
所以通过其他软件强制最小化/最大化的后果请自负 -.-

**Comment by Jason4774** [comment]
这个问题不影响使用，只是自己发现了就反馈一下，谢谢你的回复。

**Comment by liulex** [comment]
谢谢你的反馈。
另外，建议按照[这里](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)最后一条设置一下，贴图会更方便些。

**Comment by Jason4774** [comment]
谢谢，我知道这个，这个问题我之前也反馈过，然后你给我说过，但是我习惯性能只保留两个，谢谢提醒。
