### ISSUE TITLE
建议：可以考虑在截图的边缘自动加一块空白区域，用于编辑和批注

### ISSUE THREAD

**Issue by amulelernen** [liulex/Snipaste-Feedback#396]
这软件真是太厉害了，完全满足了我个人学习和工作的需求，感谢大神！~
在此提个建议，比如说在截取PDF的时候，会出现在截图区域无法编辑图片的情况；如果用户可以自定义一个距离，然后在截图以后，软件自动沿着图片的某条边补出一个该距离的空白区，专门用于编辑和批注，会方便很多，比如这样子：
![12](https://cloud.githubusercontent.com/assets/26796606/24511140/ba9f785a-159d-11e7-98eb-37cc7e08693a.png)
更进一步地，可以以截图为中心，在周围自动地补上一圈的空白区。

**Comment by liulex** [comment]
谢谢建议，加空白区域毕竟还是不美观，也不好控制所需的区域大小。
其实对于笔记标注我已经有想法了，会做得很方便很灵活的，请期待将来的更新~

**Comment by misybing** [comment]
真帅

**Comment by amulelernen** [comment]
哦，好的好的~我个人是觉得OneNote里给图片做批注不太方便，故希望截图的时候可以直接整合好一起放进去。期待大神的更新~
