### ISSUE TITLE
贴图真是一个非常棒的功能，有个小建议

### ISSUE THREAD

**Issue by Hero-here** [liulex/Snipaste-Feedback#397]
我经常使用贴图功能，常常在屏幕贴了很多块，在我拖动这些贴图的时候，需要一块一块的拖，很慢，而且还要排列它们的顺序，因为有一些是相关的，就是这样...
所以我想是不是可以搞一个合并贴图的功能，在一组的贴图可以同时拖动，同时隐藏，同时显示，同时销毁，小小的建议，希望开发者考虑
还有非常感谢开发者写出这么好的工具，而且免费开源，在这里点个赞👍，感謝，辛苦了

**Comment by liulex** [comment]
暂时还没开源哈 😅 
同一组的贴图同时隐藏，同时显示，同时销毁，现在已经可以了啊……
同时移动这个有人提过了~ #345

**Comment by Hero-here** [comment]
我的意思是，可以像选择文件一样，Ctrl+左键单击，选择屏幕上的贴图，然后右键可以选择合并为贴图组，或者释放，现在的贴图组我觉得有些不是很方便，还有一个，同时缩放😊

**Comment by liulex** [comment]
@Hero-here 我知道啊，#345 就包含了你的意思，还有 #385

**Comment by Hero-here** [comment]
嗯嗯，加油👊，期待这个新功能
