### ISSUE TITLE
贴图功能

### ISSUE THREAD

**Issue by zmple** [liulex/Snipaste-Feedback#4]
首先怒赞该软件，满满的惊喜，非常出色。
其次说下我的小期望，这么精美的工具，如果可以替代windows图片查看器、QQ影像等默认图片预览软件，可以通过上下键缩放，左右键播放目录下的其他图，那就太完美了！

现状：目前能想到的用它打开图的办法，F2打开贴图，右键替换为文件，选择指定目录下的一张图，打开
期望：关联文件格式，双击直接打开目录下的图片类型文件，支持更多格式

最后，再次怒赞这款软件，棒棒哒！

**Comment by liulex** [comment]
你好，Snipaste 并不打算成为一个看图软件，这方面其实有很多优秀的软件，实在没必要单纯为了减少运行软件的数量，而往 Snipaste 里面塞。:-)

你所描述的现状略微繁琐了一些，有更简单的办法。
如选中文件，Ctrl + C 复制，然后 F2 贴出。
又或者直接拖拽文件到某一个贴图（该贴图会被自动替换，如果需要，可以再次 F2 唤出）。

希望有解决你的疑问。
