### ISSUE TITLE
问题：调节画笔的透明度以后光标就消失了 - 已解决，更新英特尔显卡驱动即可

### ISSUE THREAD

**Issue by amulelernen** [liulex/Snipaste-Feedback#400]
RT。Alpha值在127及以上的时候，各个编辑工具都正常；到了127以下的所有数值，矩形、画笔、记号笔中的“填充”功能正常，但是画画却在截图内找不到圆形光标了，可以绘图，但是无法确定下笔的位置。折线也是如此；只有椭圆并不受此影响。我除了快捷键以外并没有做其他的设置修改。还请大神解决~

交流排查以后，不是软件的问题，更新下显卡驱动就可以了。Win7 旗舰版更新到win64_154516.4627这个版本即可。

**Comment by liulex** [comment]
我无法重现，可否录个动图/视频？

**Comment by amulelernen** [comment]
录屏了，但是没法传到comment里面……我直接发到您的邮箱了，详见其中附件。发件人是amulelernen@163.com。

**Comment by liulex** [comment]
感谢帮忙测试。
