### ISSUE TITLE
给你一个解决方法->Help wanted: replace the following images with English ones...

### ISSUE THREAD

**Issue by chengdong0421** [liulex/Snipaste-Feedback#408]
看你在[这个页面](https://docs.snipaste.com/#/advanced-tips)里想把图片里的中文换成英文，
我觉得你可以把电脑系统语言换成英语，然后运行软件，重新录一个英文版的动图。

**Comment by liulex** [comment]
@chengdong0421 要不然你以为我是什么意思 🙂

**Comment by chengdong0421** [comment]
@liulex 我的意思是说，你把电脑系统的语言调成英文，那么系统界面都是英文的了，再重新录制一下动图，就是英文版的动态图了。不用从汉语版的动图翻译成英语，而是直接录制的就是英文版的。

**Comment by liulex** [comment]
> Help wanted: replace the following images with English ones
这句话就是指希望有人帮忙在英文系统里照着录制一遍动图，然后提个 pr……
我想并没有让人把动图逐帧 PS 的意思……
