### ISSUE TITLE
不可以自定义快捷键到PrtSc

### ISSUE THREAD

**Issue by my522cn** [liulex/Snipaste-Feedback#41]
F1~F12都被占用了，建议还是用系统的PrtSc键，已经习惯picpick和FScapture的快捷键了
1.

**Comment by myoss** [comment]
+1

**Comment by myoss** [comment]
+1

**Comment by myoss** [comment]
+1, 赞作者，简直黑科技

**Comment by myoss** [comment]
+1, 赞作者，简直黑科技

**Comment by myoss** [comment]
+1, 赞作者

**Comment by GregAMO** [comment]
> 无法设置截图快捷键为PrintScreen。
Snipaste 调用 QxtGlobalShortcut 来实现全局热键，该模块就不支持捕捉 PrintScreen 按键以及被系统占用的快捷键，我也不打算修改它使它支持。如果你坚持要使用这些快捷键，请寻求第三方软件（如 AutoHotkey）的辅助。

来自Snipaste(-首选项-关于)-[用户手册](https://snipaste.gitbooks.io/snipaste/content/zh/problems/windows.html)

你可以使用Shift+F3、Ctrl+\之类不常用组合键
也可以用AHK把超级不常用的组合键=带PrtSc的组合键
AutoHotKey可以非常简单

> #x::Send, !{F4} =>按下"Win+X" =按下 "Alt+F4"

更多就去搜吧~

**Comment by liulex** [comment]
上面的同学已经说的很清楚了，目前结合 AutoHotKey 可以满足你们有关快捷键的所有需求（包括 PrintScreen 和 Win 组合键）。
目前 Snipaste 不会自己去解决这个问题，但（大概很久）以后会解决的。

**Comment by yes-github** [comment]
Win11可以通过关闭系统自带的截图功能来释放这个快捷键
![Snipaste_2024-09-07_16-02-10](https://github.com/user-attachments/assets/b73a7b00-842e-4558-a156-daec32696b01)
