### ISSUE TITLE
贴图无法操作但正常的显示Bug

### ISSUE THREAD

**Issue by scruel** [liulex/Snipaste-Feedback#411]
Bug 
[splog.txt](https://github.com/liulex/Snipaste-Feedback/files/908852/splog.txt)
一个昨天截的图，并用Ctrl+T贴在桌面上。
之前对图进行了一些编辑操作，完成编辑，一切正常。
然后再次点击编辑，一直按Ctrl+Z，直到回退到需要达成的状态，点击完成编辑（esc）。
然后鼠标就无法再操作这个贴图了，直接穿透，右击也没有反映，无法移动，无法操作，无法销毁，一直就贴在那，这一个贴图组就一直会有这个图，即便是切换组，然后换回来还是这样，重启软件也还是这样。。。log文件已附上。望解决，谢谢。

**Comment by liulex** [comment]
https://docs.snipaste.com/#/zh-cn/faq

> 8. 贴图无法移动了，右键菜单也出不来。
>    这是贴图的鼠标穿透模式。
>    Snipaste 1.12 之后，在贴图上按 <kbd>X</kbd> 可使其鼠标穿透。如需取消，请按下 <kbd>F4</kbd>（默认），其功能为：`取消光标所在位置的贴图的鼠标穿透状态；如果没有贴图位于光标之下，则取消所有贴图的鼠标穿透状态`。
