### ISSUE TITLE
[新功能建议]希望增加一个贴图销毁后重现的功能

### ISSUE THREAD

**Issue by scruel** [liulex/Snipaste-Feedback#412]
希望增加一个销毁后回退的功能，双击销毁后不是直接消失，而是移入贴图回收站，大概存10大小左右（或可自定义，销毁也可定义是否放入回收），可以支持回退操作。望考虑，谢谢。

Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by liulex** [comment]
[关闭单张贴图](https://docs.snipaste.com/#/zh-cn/getting-started?id=%e5%85%b3%e9%97%ad%e5%8d%95%e5%bc%a0%e8%b4%b4%e5%9b%be)

[销毁贴图](https://docs.snipaste.com/#/zh-cn/getting-started?id=%e9%94%80%e6%af%81%e8%b4%b4%e5%9b%be)
