### ISSUE TITLE
Snipaste 无法正确把截图复制到剪切板

### ISSUE THREAD

**Issue by xloger** [liulex/Snipaste-Feedback#413]
具体操作为当截图完毕后，双击退出截图状态，截图没有成功复制到剪切板里。假如选择按下 C 截取颜色也是如此。

但是假如是手动点击最右按钮“复制到剪切板（Ctrl+C）”，是可以的。

我觉得应该是与我电脑里某软件冲突了，怀疑是有道词典或 [Ditto](https://xbeta.info/ditto.htm)，但是将两个软件退出依旧不行，也尝试了用管理员权限运行 Snipaste 依旧不行。

**Comment by liulex** [comment]
Ditto 和 有道词典 没有问题的，只能请你继续排查了……
找到原因之后，我才能判断是否可以解决。

**Comment by xloger** [comment]
那请问下 Snipaste 有哪可以查看日志之类的么？我想也许能帮助定位问题原因

**Comment by liulex** [comment]
目前的日志没细到这个程度，对这个问题没有帮助的。
你把其他后台程序一个个关掉，关一个测试一次截图双击，应该就能找出来了。

**Comment by xloger** [comment]
有点尴尬，之前这个问题一直存在，但是在给予了管理员权限后就可以了（我之前是受不了这个问题了于是翻了一遍 faq 和设置，发现新加上了管理员启动这个功能，然后当时自动重启应用了并没有生效，但是大概是重启电脑后生效了）。
打扰到你了...

**Comment by liulex** [comment]
@xloger 
但你的情况是手动点击按键可以复制、双击不可以复制，不像是系统权限问题呢……

比如你进入 guest 用户（以便不受其他后台软件的干扰），单独运行 Snipaste，不给管理员权限，应该也是可以正常双击复制的。

**Comment by xhufo** [comment]
我也遇到这个问题了，解决方法和他一样
