### ISSUE TITLE
Allow cursor keys to position the cross hair

### ISSUE THREAD

**Issue by koppor** [liulex/Snipaste-Feedback#417]
When moving the cross hair, it is sometimes not easy to hit the right UI item. See here:

![grafik](https://cloud.githubusercontent.com/assets/1366654/24944537/fcdc9352-1f5b-11e7-8fd2-51d5f74ef55f.png)

Hitting the border of this area is not easy. I need be very slow with my mouse.

The idea is to allow cursor keys to position the selection tool (cross hair). It would move pixel by pixel and then I can select the UI components to screenshot easily.

Another idea would be <kbd>Ctrl</kbd>+<kbd>cursor-left</kbd> to select the next UI element left of the current one.

**Comment by liulex** [comment]
You can use <kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd> to move the cursor pixel by pixel, which I think is more convenient for right-handed people.

The arrow keys are for moving the snipping area or the image window.

If you insist on using the arrow keys for cusor moving, I could offer an option for exchanging the functions of arrow keys and <kbd>W</kbd> <kbd>A</kbd> <kbd>S</kbd> <kbd>D</kbd>.

**Comment by koppor** [comment]
It would be very nice to have such an option. Reasoning: Not all users are gamers and used to <kbd>W</kbd><kbd>A</kbd><kbd>S</kbd><kbd>D</kbd> :suspect: 😇

**Comment by liulex** [comment]
OK. I will add it in the next version. 😄

**Comment by koppor** [comment]
Works great, thank you!
