### ISSUE TITLE
关于「取色器颜色模式」的疑问

### ISSUE THREAD

**Issue by Jay021** [liulex/Snipaste-Feedback#418]
当我使用截图功能，按 C 键复制颜色数值，F3 粘贴贴图。

如下图
![snipaste20170412_154558](https://cloud.githubusercontent.com/assets/20473663/24946988/81645c64-1f97-11e7-961b-a2334fa282d6.jpg)
其中 HSL,HSV 的数值我认为有些问题，HSV中，数值区间分别为 0-360,0-100,0-100，如上图 255 是无法输入到常见的 PS 中使用的，建议修改一下。

![snipaste20170412_155506](https://cloud.githubusercontent.com/assets/20473663/24947220/890aed7e-1f98-11e7-8d51-10230f886384.jpg)
（PS 中示意说明）

另外建议在截图界面添加显示 HSL 或 HSV 模式的数值（HSL 和 HSV 数值是一样的），因为在调色时，HSV模式更常用，有些软件色模式默认为 HSV ，RGB 需要单独切换，操作较为繁琐。如 C4D 、KeyShot 等三维建模渲染类的软件。

**Comment by liulex** [comment]
应该是 HSV 和 HSB 一样吧？HSL 和 HSV 是不同的。

其实 HSL，HSV 和 HSI 我都用不到，所以不太清楚真正用到的人需要怎样的格式。S 和 V 是 0-255，只是因为 Qt 给的默认实现就是这样，所以我猜 255 的格式还是有一些软件在用的。

我开了个新 [issue](#419)，你可以具体说说你的需求。

**Comment by septs** [comment]
根据 wikipedia 的描述
HSV 和 HSB 是等价的
----------------------------------------
see https://en.wikipedia.org/wiki/HSB_color_space
see https://en.wikipedia.org/wiki/HSL_and_HSV
（HSB color space 会重定向至 HSL and HSV）

**Comment by Jay021** [comment]
感谢指正，确实是 HSB 和 HSV 是一样的，是我弄混淆了；不过恰好，我其实就是需要 HSB 或者 HSV 这样的数值，只是没有描述清楚，给大家带来困扰了，不好意思。

**Comment by vngano** [comment]
希望增加这个功能
