### ISSUE TITLE
Ctrl+Shift+S 保存到指定目录在我的win7下无效！

### ISSUE THREAD

**Issue by ziluoxingjun** [liulex/Snipaste-Feedback#42]
也不是说完全无效，10次中有1，2次是可以的，不知道为啥……

**Comment by liulex** [comment]
你好，无效指的是按了没反应，还是提示保存失败？
另，贴图和截图都有 Ctrl + Shift + S 功能，都是一样的“无效”吗？
另，Shift + 点击保存按钮 也是实现同样的功能，也无效吗？
以上问题并非责问，只是在排查问题 :-)

**Comment by ziluoxingjun** [comment]
截图的时候按了没反应，没有任何提示；
贴图的时候按了是成功的；
Shift + 点击保存按钮 也是成功的；

**Comment by liulex** [comment]
@ziluoxingjun 感谢你的反馈，据此已经确认问题并修复，请期待下个版本。
