### ISSUE TITLE
屏幕贴图上添加文字的描边设置没被记住

### ISSUE THREAD

**Issue by Null-C** [liulex/Snipaste-Feedback#420]
重现的过程：
f1 截图， ctrl+t 贴到屏幕上，space 打开编辑栏，选择文本编辑（此时默认开启了描边），关闭描边，输入文字，结束操作。
下次再执行相同操作时，文本编辑的描边功能仍然为开启状态，虽然我上次已经关闭了。
希望能记住描边关闭的状态。

在其他位置进行文字编辑，描边状态没有问题，只是在我上述操作过程中，有些问题。
win10_x64

**Comment by liulex** [comment]
每个贴图的工具条状态是独立的，新贴图的工具条状态均使用默认设置。

将来会允许自定义工具条的默认设置。
