### ISSUE TITLE
官网被QQ标注为危险网站了

### ISSUE THREAD

**Issue by yym0924** [liulex/Snipaste-Feedback#421]
如题
[http://guanjia.qq.com/online_server/result.html?url=https%3A%2F%2Fzh.snipaste.com%2F](url)
上面是腾讯电脑管家的检测地址
希望官方人员能去申诉一下。

**Comment by EMLVIRUS** [comment]
要想申诉成功的话，貌似要交`保护费`，所以。。。😈

**Comment by h82258652** [comment]
国产流氓都是这样，无视就好。

**Comment by septs** [comment]
单纯申诉没任何意义无法获得 bypass
并且根据部分其他社区用户报告
1. 需要备案（ISP备案？公安部备案？）
2. IP 需要在大陆境内
3. 需要符合腾讯单方面模糊设定的审查（根据某报告 申诉后 3 月内仍然会在“黑名单”内观测）
（以上限制可能来自政策合规性需要）

**Comment by KazamaSion** [comment]
目前经由申诉，已经解除了黑名单。  
申诉图如下：  
![](https://i.loli.net/2018/05/08/5af1acf3cb744.png)  
效果图如下：  
![](https://i.loli.net/2018/05/08/5af1abff4a98c.png)    

之前无法申诉成功可能的原因如下：  
1. 源站系 DigitalOcean，相关 IP 段可能已被拉黑。导致一举报就进黑名单；   
2. 在使用 CDN 前，源站对大陆的访问相当差( https://github.com/Snipaste/feedback/issues/162 )，导致负责申诉的人员无法正常访问网页，无法进行处理。   

申诉失败基本发生在更换 CDN 前。更换 CDN 后则直接成功，故有以上推断。  
申诉成功与否的原因有很多，如果不加以排查，而是只是出于“厌恶”，则无法解决问题。
