### ISSUE TITLE
{Feature request} 改进 贴图分组 易用性

### ISSUE THREAD

**Issue by wocala** [liulex/Snipaste-Feedback#422]
贴图分组是个很好用的功能，但操作有些繁琐，如下：
1. "鼠标位于贴图上方，右键，移动到分组，选择一项"(有些繁琐)
2. 或者"鼠标位于贴图上方，右键，按M，选择一项"(操作割裂)。

不知道是否还有其他方法，但这两种还可以改进，比如说：
"鼠标位于贴图上方，按M，选择对应快捷键"(分组也有对应快捷键)
或者作者有什么好的方法。
谢谢~

**Comment by liulex** [comment]
因为移动贴图到另一个贴图组是比较低频的操作，既然是低频操作，就要有低频操作的样子……（误

不过有时候确实需要批量移动贴图到另一个组，这个等贴图批量操作出来就好了。#345

**Comment by wocala** [comment]
好的

**Comment by wocala** [comment]
@liulex 那可否在右键菜单里 给贴图组 增加快捷键(比如1，2，3，4)？
就像新分组的是N

**Comment by liulex** [comment]
不可行，因为分组可以多于 10 个啊…… 也可以多于 36 个……
以后可以参考浏览器标签页，引进“固定分组”（Pinned groups）的功能，可以给已固定的分组分配快速切换、快速移动到 等快捷键。

**Comment by wocala** [comment]
好的~
