### ISSUE TITLE
【建议】可以借鉴参考ShareX的一些优点,比如截长图、OCR文字识别、图像合并...等

### ISSUE THREAD

**Issue by nn200433** [liulex/Snipaste-Feedback#423]
ShareX的项目地址:https://github.com/ShareX/ShareX
![image](https://cloud.githubusercontent.com/assets/15652213/25069260/86afb0dc-22ae-11e7-872a-1955ac1a3d7a.png)
![image](https://cloud.githubusercontent.com/assets/15652213/25069263/a09fc9b4-22ae-11e7-9d26-bc4ead915d99.png)

**Comment by liulex** [comment]
我觉得……没有必要搬太多其他截图软件的功能过来。

Snipaste 和 ShareX 的定位其实不太一样，如果 ShareX 和 Snipaste 都有你离不开的特性，那何不在电脑上同时保留两者呢，而不是期望其中一个囊括另一个。

虽然我是这么想的，不过你提到的功能在 #282 都有人提过了。。。

**Comment by nn200433** [comment]
确实,我提到的功能,好多在#282都有人提过,这说明有一部分人还是需要这些功能的，这些功能虽然不是经常使用的功能，但在某些特定的场合还是要用到的╮(╯▽╰)╭，这样我就得再去寻找安装其它的软件是一件非常痛苦的事情。竟然大神您选择一些功能以插件形式存在，那么这些扩展功能也可以作为插件商店中的插件，让用户自行安装，不脱离只为截图而生的初心。

**Comment by liulex** [comment]
Snipaste 为贴图而生…… 💔

**Comment by nn200433** [comment]
....为截图+贴图而生，无论是截图还是贴图，都很强大！！！
