### ISSUE TITLE
【建议】有关缩略图透明度的问题

### ISSUE THREAD

**Issue by cul2137** [liulex/Snipaste-Feedback#425]
缩略图能够设定大小的确挺方便的。但是我是重度参考图用户，经常一次性贴好多个参考图，用的时候希望原图是不透明的，暂时不用的时候点成缩略图，需要缩略图带透明度，不遮挡界面。这个时候操作比较繁琐，要看的时候重置图片，暂时隐藏的时候调节透明度，然后切换成缩略图。

希望能够增加缩略图的透明度设定：
1、缩略图除了设置尺寸还可以设置默认透明度，多一个选项“与原图片相同”；
2、或者，切换缩略图是，缩略图的透明度在原图的基础上减去一个百分比，默认就是不减去。
3、缩略图的外边框能够自定义（当然这个比较没影响，只是图透明，边框挡界面有点奇怪而已。）

**Comment by cul2137** [comment]
观望了好久，第一次建议，不知道前面的文字会缩小，请见谅！

**Comment by liulex** [comment]
@cul2137 谢谢，很好的建议！

针对你的建议，我做了如下修改：
1. 允许在缩略图模式调节透明度。
2. 透明度能影响到缩略图的外边框。

然后，如果希望在还原缩略图的时候使它不透明，那么在选项里勾上`缩略图接受”重置“操作`，用中键还原就好了。

我觉得这样应该能大致满足你的需求。如果是给缩略图模式加个默认透明度或者默认减轻一个百分比，那么还原的时候肯定期望能恢复原来的透明度，然而在缩略图模式你又可以更改透明度，于是我就无法决定你是想要哪个透明度。所以我觉得这个选项不太好 。

**Comment by cul2137** [comment]
能参考我的意见我很开心，也看到你做的改动和说明了。但是，我觉得这样操作还是有点繁琐，如果贴图的透明度和缩略图的透明度互不影响或许比较好。毕竟缩略图的时候如果不遮挡后面的东西的话完全没必要去调节透明度，往往使用起来不需要一直调节透明度。贴图不透明，缩略图直接带50%透明度，像这样省去ctrl+滚轮的步骤或许比较友好。
目前1.12版本，缩略图保持原贴图透明度。
可以增加一个选项“缩略图用固定透明度”并带百分比设置选框。
不勾选就和现在一样，勾选缩略图就用特定透明度。这样或许比较好。

**Comment by cul2137** [comment]
![Uploading image.png…]()

**Comment by cul2137** [comment]
![Uploading snipaste20170418_173208.png…]()
就是增加类似图片上的选项，这样应该能符合比较多人的需求吧！

**Comment by liulex** [comment]
我完全明白你的意思，但你设想的选项应用面太窄了，限制也太多了，不是一个合适的选项。

另外，现在的缩略图只是一个很初步的阶段，以后功能会丰富起来的。

**Comment by cul2137** [comment]
我没有想到缩略图还有什么特别功能可以展现，所以才觉得这样的设定比较合适。我有看到他们提的意见，有人提到重置缩略图只重置透明度不重置大小，有人提到缩略图不能调节通明度。所以我一开始以为你是希望我用预加的功能来代替，但是从长远的角度考虑的确会限制以后增加新功能。
我还是希望你们能考虑把这个功能添加到高级设置里边。只要能使用起来更加方便，我是不怕设置麻烦的。

**Comment by liulex** [comment]
我觉得以上做的修改已经足够，没有必要再将多个功能绑定成一个，限制将来的实现逻辑。
