### ISSUE TITLE
1.12版本贴图无法拖动

### ISSUE THREAD

**Issue by zhouhongfei11** [liulex/Snipaste-Feedback#426]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 更新到1.12后，贴图无法进行拖动，系统是win7 64位

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by GregAMO** [comment]
@zhouhongfei11 看下更新日志，
新版本支持单个贴图鼠标穿透
