### ISSUE TITLE
Use %APPDATA% for local files

### ISSUE THREAD

**Issue by koppor** [liulex/Snipaste-Feedback#427]
I am using [syncthing](https://syncthing.net/) to sync my machines. I have following issue:

Files are causing conflicts

Snipaste creates `hsitory\snip\...j.sp` files on each PC. Syncthing tries to copy these, but the files are causing conflicts, because they have been changed at the other machine:

![grafik](https://cloud.githubusercontent.com/assets/1366654/25222511/f11e827e-25b8-11e7-8b8e-be98a86bcda3.png)

It is even harder for the log file, because the log file is locked by the process and thus SyncThing goes crazy:

```
 11:00:25 INFO: Puller: final: rename \\?\C:\Users\koppor\BTSync\software-portable\Snipaste\splog.txt \\?\C:\Users\koppor\BTSync\software-portable\Snipaste\splog.sync-conflict-20170420-110025.txt: The process cannot access the file because it is being used by another process.
[PEIZ2] 11:00:2
```

Would it be possible to use `%APPDATA%`? Then, I could sync the binary of snipaste, but the files local to the machine would be locally stored.

**Comment by liulex** [comment]
You could change the history directory, as well as the log file location. See [Advanced Configs](https://github.com/liulex/Snipaste-Feedback/wiki/Advanced-Configs).

Example:
>
>[General]
>history_dir=c:/abc
>
>[Log]
>file=c:/def/splog.txt

**Comment by koppor** [comment]
- I think, environment variables are not expanded there? This should be possible. On one PC, I use `C` as main drive, on the other one `D`.
- The `config.ini` also stores `last_save_folder`, which also changes on two different installations.

Reading that, I think, it is just a bad idea to synchronize a portable app. I have to extract it on each PC, where I use it.

**Comment by liulex** [comment]
It is not good to use one `config.ini` across machines. Most of the settings in it are unaware of external changes, therefore the changes would be overridden when Snipaste is closed.

You could make use of the new feature introduced in v1.14 to keep the real `config.ini` in different places on each PC.
> Support symbolic link for `config.ini`
