### ISSUE TITLE
希望取色器可以增加复制颜色代码时不带#的选项

### ISSUE THREAD

**Issue by noisay** [liulex/Snipaste-Feedback#43]
很多软件还有icon网站（比如阿里巴巴的iconfont）在识别颜色的时候是不包含#的，现在的版本取色识别复制颜色代码后都是带#的，需要手动去掉#。所以希望增加一个取色复制颜色代码时不带#的选项。感谢作者的付出

**Comment by liulex** [comment]
已经添加，将出现在 1.6 版，请静待发布。
