### ISSUE TITLE
Win taskbar 图标样式建议

### ISSUE THREAD

**Issue by huaiyin98** [liulex/Snipaste-Feedback#434]
在Windows下TaskBar的图标因为视觉误差的原因会显得蓝色最深黄色适中，红色最浅甚至有些突出。每次点击使用的时候强迫症都点受不了。

**Comment by EMLVIRUS** [comment]
无法get到你的点在哪里

**Comment by huaiyin98** [comment]
在视觉上图标左下角红色色块相较上端蓝色色块更大

**Comment by liulex** [comment]
你指的应该是通知栏图标吧？
这个问题我们有过讨论，但没有更好的配色方案提出。
通知栏图标支持自由设置颜色，例如可以设为全白的，就不存在视觉误差问题了。
