### ISSUE TITLE
无法删除贴图，也无法取消贴图，一直存在

### ISSUE THREAD

**Issue by BenjaminGao** [liulex/Snipaste-Feedback#435]
### bug

1. 我把一个html5在线播放器全屏了，然后ctrl+t，直接贴图。但是，这个图一直存在，无法点击，只能shift+F3隐藏贴图
2. 我把应用重启后，依然如此，shift+F3显示贴图**仍然**不能点击显示的贴图
3. 我删除了贴图文件夹里的这个图，再次shift+F3，仍然有这个图，(数据在内存里不是实时更新的原因么？不知道)
4. 我又重启了应用，按shift+F3不显示了
这个BUG...

### 待优化，还是我的原因？

按F1截图时，选择框跟随鼠标变动，但是不流畅，系统windows10 15063.14
图二效果，看着不是很明显，图中的鼠标速度很快，说服力不强。但是有时候鼠标速度根本不快，就是卡顿，而且相当明显(没夸大)

![snipaste20170426_234437](https://cloud.githubusercontent.com/assets/16028320/25443459/7c4e4b10-2ada-11e7-848a-0fce0cea6459.png)

![gif](https://cloud.githubusercontent.com/assets/16028320/25444763/d11f0388-2ade-11e7-93e6-2aa73d2e748a.gif)

**Comment by liulex** [comment]
1. 你按到了 <kbd>X</kbd>，详见 [1.12 的更新日志](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%9B%B4%E6%96%B0%E6%97%A5%E5%BF%97#v112).
2. 这个在 1.13 应该有改善。

**Comment by BenjaminGao** [comment]
好的，明白了，谢谢
