### ISSUE TITLE
win7按F1后延迟很久

### ISSUE THREAD

**Issue by shiyu619** [liulex/Snipaste-Feedback#436]
第二次会好点

**Comment by Genteure** [comment]
见 https://github.com/liulex/Snipaste-Feedback/issues/373#issuecomment-295261902
> 所以就是系统内存调度问题吧。。。长时间没用就被打入冷宫了。

**Comment by liulex** [comment]
以及 https://github.com/liulex/Snipaste-Feedback/issues/360#issuecomment-291495337 。

**Comment by gongnl** [comment]
我也碰到一样的问题，首次按F1启动截图时很慢有5秒左右的延迟，第二次开始就正常了，请问是有没有办法优化？
我的系统配置如下
制造商：Hewlett一packardCompany
型号：Hp pro 3380MT
分级：4.6 Windows体验指数
处理器：Intel(R)Core(TM)i3-3240 CPU @ 3.40GHz 3.40GHZ
安装内存（RAM):4.00GB(3.39GB可用）
系统类型：32位操作系统
