### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by April-BOY** [liulex/Snipaste-Feedback#437]
Bug report?
* Please describe the steps to reproduce as detailed as possible.

Feature request?
* Besides telling me what you want, please also describe what it does and why you need it.
* To avoid duplicates, please also check out the requested features before you post: https://github.com/liulex/Snipaste-Feedback/issues/282

---

发现了 bug？
* 请描述一下重现的步骤，越详细越好

请求新功能？
* 除了告诉我你想要什么，请再描述一下它具体是怎样的，以及你为什么需要它
* 为避免重复，发布之前请检查一下它是否已被提出过：https://github.com/liulex/Snipaste-Feedback/issues/282

**Comment by April-BOY** [comment]
is:issue is:open 望可以增加【截图拼接】的功能呢！就是像手机上的截图软件一样，可以将几张截图进行拼接；还有【滚屏截图】的功能，就是对有【滚动条】的网页或者文件能截取全部的内容

**Comment by GregAMO** [comment]
see #19
