### ISSUE TITLE
一个建议，一个问题

### ISSUE THREAD

**Issue by ruixt** [liulex/Snipaste-Feedback#439]
有一个建议：
快捷键最好能自定义      截图后添加箭头、文字、涂鸦等，没有清除功能，没有清除快捷键，比如按下E就全部清除，适合培训讲师点重点

一个问题：
XP下无法运行，说缺少  api-ms-win-crt-runtime-l1-1-0.dll   文件，但下载了几个版本都不对

**Comment by septs** [comment]
1. @liulex 
2. [常见问题 - 运行后遇到提示计算机中丢失 api-ms-win-crt-runtime-l1-1-0.dll 错误](https://docs.snipaste.com/#/zh-cn/troubleshooting?id=%e8%bf%90%e8%a1%8c%e5%90%8e%e9%81%87%e5%88%b0%e6%8f%90%e7%a4%ba%e8%ae%a1%e7%ae%97%e6%9c%ba%e4%b8%ad%e4%b8%a2%e5%a4%b1-api-ms-win-crt-runtime-l1-1-0dll-%e9%94%99%e8%af%af)

**Comment by GregAMO** [comment]
@ruixt Ctrl + Z撤销上一次标注（可以再恢复）
Ctrl + Shift + Z移除所有标注（无法再恢复）
