### ISSUE TITLE
无法使用快捷键切换鼠标穿透

### ISSUE THREAD

**Issue by RuioWolf** [liulex/Snipaste-Feedback#441]
需要在右键菜单里切换。。

**Comment by liulex** [comment]
不再提供全局切换的功能，菜单以及全局快捷键只是`取消`穿透，详见最近的更新日志或 [基础操作 - 使贴图鼠标穿透](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C#%E4%BD%BF%E8%B4%B4%E5%9B%BE%E9%BC%A0%E6%A0%87%E7%A9%BF%E9%80%8F)。
