### ISSUE TITLE
【建议 - 交互】关于文字标记内容的移动及（二次）编辑

### ISSUE THREAD

**Issue by feimiao** [liulex/Snipaste-Feedback#442]
![tim 20170506082327](https://cloud.githubusercontent.com/assets/18380365/25768470/4e0339f0-3237-11e7-9bf7-7ee1103c9cc3.png)
![tim 20170506082343](https://cloud.githubusercontent.com/assets/18380365/25768471/53a8b38a-3237-11e7-8f0a-4af5363b1ead.png)
1. 希望已添加的标准文字，鼠标可以直接拖拽进行移动；而不是单击进入编辑状态，然后通过周围虚线框移动。（编辑状态可以通过双击进入）
2. 希望可以考虑回车退出编辑状态，Shift + Enter 进行换行。

（题外：希望可以更新箭头工具样式为非等宽箭头，如QQ截图的箭头；箭头可以进行二次编辑；按住Ctrl 或其他某个键点选标注可以直接删除；穿透与退出穿透为何不设置为同一个键呢？比如退出穿透的F4）

**Comment by liulex** [comment]
1. 
   1. 双击已经绑定有动作。
   1. 可以直接拖拽文字框 _四周_ 进入移动状态，无需先单击。不过目前光标没有体现出来可以这么做，我会在下一版本改进光标的状态。
1. 所有形状都可以通过 鼠标右键 退出编辑状态，如果换成 Shift + Enter 换行，大概会不断有 issues 和邮件来问怎么换行。。。
1. 个人不喜 QQ 截图的箭头。。。也方便我区分某个截图是通过什么工具截的。
1. 以后会添加删除指定标注的功能。
1. 因为“设为穿透”这个动作不需要使用一个全局快捷键，我也明白这个会造成一些费解，我再想想…… 😂

**Comment by feimiao** [comment]
为何不直接设置为整个文字上部均可进行拖拽移动？（拖拽移动，单击编辑）四周的可选范围较小，有一定的失误率欸~~~😀

**Comment by GregAMO** [comment]
@feimiao 因为文本框之间是可以有重叠部分的。（在别处新建一个文本框后拖动到重叠状态）
关于你说的失误率，下一版本改进光标状态后，你可以再来试试看想象中的失误率。
如果你有很频繁的 拖动文本框游走 的需求，请把目标文本转换成贴图。
文字转贴图的背景，可以调整透明度( Alpha 通道)

**Comment by liulex** [comment]
1.13.1 已修复光标状态，可拖拽移动的区域还是挺宽的（当然，与当前文字大小有关）。

我觉得还是保持已编辑文字和正在编辑文字这两者的操作一致性比较好，所以不赞同"拖拽移动，单击编辑"。

**Comment by ruixt** [comment]
报告，程序画出的类似QQ的箭头太瘦了!   不醒目!

**Comment by GregAMO** [comment]
@ruixt 拜托看下用户手册
箭头粗细可通过滚轮上下滚动调节
