### ISSUE TITLE
sublime text 3 不能高亮

### ISSUE THREAD

**Issue by 23330** [liulex/Snipaste-Feedback#444]
sublime text 3 用的pythonIED插件, 复制python代码然后贴图的时候代码没高亮,还是黑色字体。
并且不能自动捕获win10的开始菜单

**Comment by liulex** [comment]
应该是指创意者更新之后的 win10 吧？在那之前我记得是可以捕获开始菜单范围的。

至于Sublime Text 的代码复制，可结合 https://github.com/liulex/CopyAsHtml 使用。

**Comment by 23330** [comment]
是的更新后的win10 感谢

**Comment by liulex** [comment]
更新后的还没试出办法，以后有闲心再研究看看……
