### ISSUE TITLE
请求新增账号同步功能

### ISSUE THREAD

**Issue by JosephCN** [liulex/Snipaste-Feedback#445]
1、多设备设置同步，我的设备比较多，经常在其中一台设备修改了设置，但是忘记在其他设备修改。
2、贴图多设备之前同步，或者截图后可在其他设备获取。

**Comment by ysc3839** [comment]
我觉得不太现实。你可以考虑用网盘来同步。

**Comment by liulex** [comment]
设置都在 config.ini 里，自行通过网盘同步即可。不过不同设备的配置还是有一些差异的，比如文件夹路径，可以通过环境变量来解决。

贴图则不太适合同步，因为不同设备的屏幕设置一般是不同的，因此贴图的屏幕位置等信息无法共用，不过以后会提供贴图组导入/合并的功能。
