### ISSUE TITLE
【建议】希望区域大小的显示可以更加直观

### ISSUE THREAD

**Issue by feimiao** [liulex/Snipaste-Feedback#446]
![snipaste_20170507_163212](https://cloud.githubusercontent.com/assets/18380365/25779124/5602dc5c-3343-11e7-96ef-fb19aa91a70a.png)
如图所示，此种更加直观——虽然不影响使用。
😀

**Comment by EMLVIRUS** [comment]
您的意思应该只是指示长宽吧

**Comment by liulex** [comment]
在图片中央显示大小信息就没必要了，至于在边缘显示，确实会提高一点易用性，但有一些边界条件处理起来比较麻烦，还是算了吧 🌚
