### ISSUE TITLE
功能“取消鼠标穿透”无效，求解

### ISSUE THREAD

**Issue by klzsysy** [liulex/Snipaste-Feedback#448]
* 功能“取消鼠标穿透”无效
不管设置什么快捷键，或是以管理员身份，均无法使用，以至于贴图永远处于最上方。
此外如果我设置该“取消鼠标穿透”为X键，那么X键就失效了，其他键也是一样

![image](https://cloud.githubusercontent.com/assets/3226923/25948972/734f73d6-3688-11e7-8cc4-ba3b9b39b050.png)
![image](https://cloud.githubusercontent.com/assets/3226923/25948987/7cdf8f58-3688-11e7-9113-b260e08e056f.png)

**Comment by cul2137** [comment]
我个人用的快捷键是Alt+4.版本更新后（1.12）针对单个贴图点击穿透功能出现后，照样正常使用。系统是win10家庭版1511。
像你这样说一个问题的时候最好把版本号，系统等详细信息贴出来，这样直接问谁也没法帮助你的。
当然问我没用的，同样是用户只能讲讲我的使用情况而已。

**Comment by liulex** [comment]
@klzsysy "取消鼠标穿透"和“贴图置顶显示”是两件事情，不要混淆了它们的含义。
自定义的快捷键设置是全局的，你设为了单字母的，自然该字母按键就无法用于打字了。

**Comment by klzsysy** [comment]
@liulex “贴图置顶显示”这个选项并没有找到，我的操作就是按了F1截图后直接点击下方的“贴到屏幕上”，该贴图确实是置顶显示，但并没有找到不置顶显示得选项，按F4也鼠标也无法穿透，版本是1.13.3。

![image](https://cloud.githubusercontent.com/assets/3226923/26763349/2d552826-4984-11e7-9111-fcfdd40a3dea.png)
