### ISSUE TITLE
【建议】截图下方加个查找相似图片的按钮，能实现么？

### ISSUE THREAD

**Issue by ylx3351657** [liulex/Snipaste-Feedback#449]
要不然要查找相似图片要把截图保存，然后打开百度图片，然后上传图片，实在是太麻烦了。如果截图下方加个查找相似图片的按钮，那只要点击一次，就直接打开相似图片的结果，效率不是很高。

**Comment by ylx3351657** [comment]
对了，有一个开源的chrome插件“二箱”，能实现多引擎以图搜图，以及截图搜图，可惜只限于浏览器中，如果有个本地版的就更方便了。

**Comment by septs** [comment]
可等待未来的插件系统
https://github.com/liulex/Snipaste-Feedback/issues/282#issuecomment-268238525
