### ISSUE TITLE
启动后贴图好像自动置顶了，会挡到其它窗口，怎么默认不置顶

### ISSUE THREAD

**Issue by ylx3351657** [liulex/Snipaste-Feedback#450]
启动后贴图好像自动置顶了，会挡到其它窗口，怎么默认不置顶

**Comment by GregAMO** [comment]
see #391  以后会考虑不置顶，目前可以按快捷键显示 / 隐藏贴图
> 允许不置顶的话，交互、逻辑等会复杂一些，不过确实有着一定使用的场景。以后再看看吧。

**Comment by ylx3351657** [comment]
能否这样：设置成鼠标穿透后，取消窗口置顶，这样不会影响到其他的交互了吧。因为我有一些图片打算长期固定在桌面上。

**Comment by zoeysnowy** [comment]
@GregAMO  Hi Greg，非常喜欢Snipaste~ 也想问能不能有桌面固定功能，交互上可以设置三层：checkbox-默认贴图固定桌面；贴图右键设置固定/置顶；贴图分组设置固定/置顶。谢谢开发组的各位了！
