### ISSUE TITLE
【建议】设置成鼠标穿透后，取消窗口置顶

### ISSUE THREAD

**Issue by ylx3351657** [liulex/Snipaste-Feedback#452]
设置成鼠标穿透后，取消窗口置顶，这样不会影响到其他的交互了吧。因为我有一些图片打算长期固定在桌面上。

**Comment by cul2137** [comment]
我个人觉得，截图贴图软件是为了方便截图，参照用图。因为windows系统切屏总不是很方便。贴图主要方便信息输入、对比、参照之类的。不是用来修饰桌面的。如果要用来装饰桌面，我以前用的是Rainmeter，还支持脚本编写。

**Comment by ylx3351657** [comment]
谢谢您的推荐，以前知道这个软件，没深入用，今天研究了一下，惊喜。

**Comment by liulex** [comment]
鼠标穿透 和 窗口置顶 是两件事，各有各的用处，我看不出将它们进行绑定的必要。
