### ISSUE TITLE
建议在首选项中加入"设置优先级"

### ISSUE THREAD

**Issue by qssc** [liulex/Snipaste-Feedback#453]
CPU高占用的时候经常不响应，必须手动调优先级到“正常”，但这样也仅本次运行，游戏时截图很麻烦。
![default](https://cloud.githubusercontent.com/assets/28760462/26162616/ca410bd4-3b59-11e7-8a5f-a67dd13938a2.png)

**Comment by ysc3839** [comment]
我觉得虽然这个功能实现起来很简单，但是没必要，可以用外部工具实现。如果你要的话我用Python给你写个自动设置的工具。

**Comment by septs** [comment]
该功能请求缺乏广泛的适用性，就目前来看属于个例事件。

**Comment by liulex** [comment]
@qssc 正常情况下不就是“正常”优先级的么，“低于正常”是系统干的还是第三方？
