### ISSUE TITLE
在Listary 搜索界面无法截屏

### ISSUE THREAD

**Issue by Jarvanh** [liulex/Snipaste-Feedback#46]
截图快捷键无效，无法截取如下界面

![](http://i.imgur.com/yvoq5ZQ.png)

**Comment by liulex** [comment]
我这边没问题，你是以管理员权限运行的 Listary 吧？如果是这样，Snipaste 也需要管理员权限，它的快捷键才能在管理员权限的窗口起作用。

**Comment by Jarvanh** [comment]
@liulex 原来如此，非常感谢。
