### ISSUE TITLE
置顶图片希望可以添加新的隐藏逻辑

### ISSUE THREAD

**Issue by liu4shuai4163** [liulex/Snipaste-Feedback#47]
我希望 隐藏置顶图片 可以通过使用`esc`

**Comment by liu4shuai4163** [comment]
我在myeclipse和vs2015里复制代码 然后 f2 没有办法带有html格式
尝试了很多次,没有一次成功
我是windows 10 insider用户,使用最新的预览版14393

虽然有些小小的问题,但是这个工具本身的素质是极其优良
感谢开发者
衷心的感谢您,开发出这样优秀的截图工具

**Comment by liulex** [comment]
新版已经可以用 `Esc` 隐藏贴图。
vs2015 请安装 Productivity Power Tools 扩展，并打开这个扩展的 "HTML Copy" 功能。

**Comment by liu4shuai4163** [comment]
那么.eclipse 或者myeclipse 有没有类似的插件推荐呢

**Comment by liulex** [comment]
抱歉，我并没有使用那两个 IDE 的经验。
