### ISSUE TITLE
User Guide

### ISSUE THREAD

**Issue by EMLVIRUS** [liulex/Snipaste-Feedback#49]
Add a users' guide about directions to use Snipaste features in case that newbies are confused by complex operating to advanced features.
Plus, URL https://github.com/liulex/Snipaste-Feedback/zh/basics on this repository wiki page is inaccessible.

**Comment by liulex** [comment]
Sorry for the inconvenience.
The wiki page of this repo was outdated and I have just updated its content.

For the moment I am quite busy and cannot find time to finish the English version of user guide. **If anyone wishes to translate the Chinese version to English version, please drop me an email** (which can be found on snipaste.com or the About Dialog of Snipaste).

**Alternatively, you may also check out the internal shortcut list first**, which can be found on `Options Dialog` - `Hotkeys` - `Internal hotkeys` and should help most users master the common usages of Snipaste.

**Comment by liulex** [comment]
The English document is now available.
Please check [here](https://github.com/liulex/Snipaste-Feedback/wiki).
