### ISSUE TITLE
能设计成不常驻吗？

### ISSUE THREAD

**Issue by xiaogu** [liulex/Snipaste-Feedback#5]
截图工具不是一直都使用，通常截好后不需要常驻，能设计成截图操作都完成后，就退出吗？
比如我将snipaste放置在任务栏上，需要截图时，点击一下，截好就让他自动退出内存，下次再要截图，还是从任务栏上点击启动。
谢谢，snipaste非常好。

**Comment by liulex** [comment]
Snipaste 常驻的原因是因为它主要是个贴图软件。
关于你的需求，以后会增加命令行参数，使用命令行调用即可直接截图。
