### ISSUE TITLE
希望加入自动检查更新的功能

### ISSUE THREAD

**Issue by chenjunyu19** [liulex/Snipaste-Feedback#50]
Snipaste 最近更新的很勤快，这是好事，然而却引出了另外一个问题：不去看根本就不知道更新了。
所以我建议发现新版本后能够提示，不要求能自动更新~~（当然能就更好）~~。例如在任务栏托盘图标上显示一个红点，这样就能知道更新了。

**Comment by liulex** [comment]
你好，当我闲下来之后，会增加自动更新功能的。

**Comment by S-Kee** [comment]
希望添加，不然我现在隔一周就会上官网看看，在顺道看看Github中大家的建议~~

**Comment by liulex** [comment]
1.7 已加入自动更新。
