### ISSUE TITLE
调色板

### ISSUE THREAD

**Issue by hiforrest** [liulex/Snipaste-Feedback#52]
我是Faststone capture和picpick的用户，看到snipaste觉得很惊艳，很好用。但有一个遗憾，snipaste取色后没有类似photoshop的调色板工具来调色（或者看颜色），对设计师来说这是一个很实用的功能，希望能加上。
![photoshop](https://cloud.githubusercontent.com/assets/2953848/17611838/4cfe3500-607d-11e6-8065-6b0a41a280dd.png)

**Comment by liulex** [comment]
你好，取色后，按贴图键即可查看颜色，贴出的颜色卡片上还有很多其他操作可以方便设计师。
