### ISSUE TITLE
提交几个bug及建议，v1.6

### ISSUE THREAD

**Issue by BluYous** [liulex/Snipaste-Feedback#53]
使用矩形和椭圆工具的时候，按住shift之后松开，一直都是画□和○，但是工具栏却显示矩形/椭圆

希望 → 也增加shift功能，并且→末端调小一点，太大了容易遮住其他部分，不容易精确指出位置

还有应该就是win10(其他没试过)的问题，在打开开始菜单后会自动检测到被开始菜单遮住的窗口(以及桌面图标)，而不是自动检测开始菜单，至少不要检测到被开始菜单遮住的部分。

**Comment by liulex** [comment]
矩形和椭圆的图示确实有不一致的问题，感谢反馈！此问题已经修复，请期待下一版。

箭头的话，你画的时候不要遮挡住你要指出的位置就可以了吧？

开始菜单的问题是无解的，因为截屏实际是一个全屏的窗口，当你启动了截屏，这个窗口就被激活了，所以开始菜单就收回去了，所以是无法检测到开始菜单上的元素的。因为开始菜单收回去了，自然就检测到桌面上的元素了，但我想这并不会影响用户的正常使用吧？
自动检测功能有它**技术上**的局限性，还请不要对它抱有太高的期望。:-)
