### ISSUE TITLE
希望增加快捷键功能的开关

### ISSUE THREAD

**Issue by tanglueyi** [liulex/Snipaste-Feedback#55]
有时候在别的程序里会用到F1跟F3键，但是又不想临时退出Snipaste，希望添加一个开关快捷键的功能

**Comment by liulex** [comment]
你好，既然是全局快捷键，那暗含的意思就是它应该尽可能在任何时候都有效。
如果 `F1` 和 `F3` 对你而言不方便，你应该给 Snipaste 设置另外的快捷键。
我印象中，并没有哪个程序会提供一个开关快捷键的功能吧？提供这样的功能只会让更多用户抱怨 Snipaste 的复杂。
