### ISSUE TITLE
截图无法保存

### ISSUE THREAD

**Issue by tianxiang8534033** [liulex/Snipaste-Feedback#58]
点击保存截图，无法保存，保存弹框会闪退

**Comment by liulex** [comment]
是**每一次**都那样吗？
另外，对贴图窗口的图片进行保存呢？

**Comment by tianxiang8534033** [comment]
现在可以了。有时不行


来自 魅族 MX5

-------- 原始邮件 --------
发件人：liulex <notifications@github.com>
时间：周日 8月14日 23:45
收件人：liulex/Snipaste-Feedback <Snipaste-Feedback@noreply.github.com>
抄送：田翔 <1184909560@qq.com>,Author <author@noreply.github.com>
主题：Re: [liulex/Snipaste-Feedback] 截图无法保存 (#58)

**Comment by liulex** [comment]
有时不行也是不合理的，如能找到导致保存失败的条件，还请继续反馈 :-)
