### ISSUE TITLE
特别想增加：贴图到桌面（把工作提醒订到桌面）

### ISSUE THREAD

**Issue by seafz** [liulex/Snipaste-Feedback#59]
我工作时，QQ群有各单位的通知，非常容易忘记，要是能把贴图放到桌面提醒自己就好了（现在贴图置顶，影响打开的别的文档界面）。这些桌面截图可以在桌面整理分类就更好了，可以把通知区分开来，也当成通知日记备份了，便于以后查找。截图自动命名为2016-08-08 18：59 -01  就更好了，非常希望添加此功能，一定受广大办公人员的喜欢。

**Comment by GregAMO** [comment]
我暂时是通过反复按（隐藏所有贴图的热键）来对贴图招之即来挥之即去的，
这个热键实际上是（隐藏\显示所有贴图），你把鼠标悬停在设置项上面就看见解释了。
这样查看的时候也不一定要回到桌面啦。

**Comment by liulex** [comment]
是的，@GregAmo 的方法是针对你的需求最好的解决办法，其实也是很方便的。
至于截图命名的格式，以后会让用户自己定义。
