### ISSUE TITLE
希望截图时十字线设为全屏的十字线

### ISSUE THREAD

**Issue by icksky** [liulex/Snipaste-Feedback#6]
感谢作者带来这么好用的软件。我是做前端的，之前一直用 FSCapture ， 除了截图 还会用来量 UI 尺寸。全屏十字线就是这个时候用的。

直接看图吧，以下文字助攻用。[图片地址](http://ww3.sinaimg.cn/mw690/8eac7e02gw1f6e9ycrq8oj20f009ggm3.jpg)
比如量一个圆形的头像尺寸，要定位到它的左上角拉框，但是十字线太短，就不知道该点是否到达圆形图片的上边缘跟左边缘，要是全屏十字线，就可以看到了。

**Comment by Dwwwwww** [comment]
为什么不试试Alt键呢？

**Comment by icksky** [comment]
@Dwwwwww 感谢。我试了一下，发现要选定某个范围，或者它自动选出一个窗口的时候按 Alt 才有用。这样就不能很好的定位起始点，而是要拉出选区之后再调整。如果未选中即可按 Alt 出十字线，才能更好的定位左上角的点吧？

**Comment by liulex** [comment]
你好，该功能已实现，将出现在下个版本，即 v1.5。
为不影响其他无此需求的用户，需要按住 Alt 才会触发。

**Comment by icksky** [comment]
@liulex 哈哈，给力。感谢~

**Comment by liulex** [comment]
1.5 版已经发布。

**Comment by icksky** [comment]
@liulex 3Q，昨天就下载使用了。给力~~
