### ISSUE TITLE
【win7_x64_v1.6】自动检测窗口及元素无效

### ISSUE THREAD

**Issue by Tingfant** [liulex/Snipaste-Feedback#61]
选项中反复勾选，重启软件，重启电脑等都未能解决。请问一下可能是什么原因？

**Comment by GregAMO** [comment]
如果是以下情况（chrome）：

> 截图时无法自动选取Chrome 浏览器窗口的页面元素
请在 chrome://accessibility/ 打开 Global accessibility mode。
Firefox 及 IE 浏览器则无需额外设置。

来自 Snipaste-首选项-关于-[用户手册](https://snipaste.gitbooks.io/snipaste/content/zh/)

如果是其他软件，那就把截图和软件名提供给作者吧~
（我也是Win7 x64，似乎没遇到哪个软件没法自动选取。）

**Comment by Tingfant** [comment]
@GregAMO 是任何地方都无法识别窗口和元素，而非局限于某一软件。

**Comment by liulex** [comment]
听你的描述，我觉得是这两个没选项没勾上……
![sp160814_095121](https://cloud.githubusercontent.com/assets/2010459/17650073/6b52ec4e-6276-11e6-9d55-22e1f8d2022e.png)

**Comment by Tingfant** [comment]
@liulex 勾选，未勾选，重启软件或系统，这些都排列组合起来试过了，应该不是这个原因。

**Comment by liulex** [comment]
@Tingfant 是的，已经确认不是选项的问题。
不知能否加入我们的 Telegram 群或者给我发封邮件留下你的其他联系方式，协助我进行测试？

**Comment by liulex** [comment]
@Tingfant 该问题应该已经修复，将整合进 1.7 版。
你也可以留个联系方式，我给你发修复版，以确认是否完全修复。

**Comment by Tingfant** [comment]
@liulex 很乐意协助你进行测试，但是由于我没有使用Telegram，就麻烦你发我邮箱吧。
email：hi@liumy.me 
测试后我会第一时间反馈给你。不知道你是否方便email你的联系方式给我，以便更即时的沟通解决现在及以后可能存在的一些问题。

**Comment by JokerQyou** [comment]
我也遇到了这个问题。软件版本 `1.6 (2.16.08.10)` 环境 Windows 10 pro 64 bit (`1607 (内部 14393.51)`)。开始以为是不能检测窗口和窗口元素，后来发现跟屏幕有关系。我使用的是笔记本电脑，主显示器是外接的，笔记本的屏幕是第二显示，模式是扩展。当截取笔记本屏幕（第二显示）区域时，可以检测窗口和窗口元素；当截取外接屏幕（主显示）区域时，窗口和窗口元素都检测不到，只能识别到整个屏幕区域。

**Comment by Tingfant** [comment]
@JokerQyou 你描述得应该又是一个问题了，我的问题使用修复版已经解决。
@liulex  让作者帮忙看看你的问题吧 。

**Comment by liulex** [comment]
@JokerQyou 屏幕设置改变后，需要重新启动 Snipaste.
另不知道你的情况是否为一个高分屏，一个普通屏？这种情况就确实还没处理好。除此之外的多屏应该是没有问题的。

**Comment by JokerQyou** [comment]
@liulex 两个都是普通屏幕，没有高分屏。另外屏幕设置我没有改变过，从安装 Snipaste 之前就是这样的，并且我在刚安装之后为了测试，重启过多次 Snipaste。

目前观察到的唯一例外就是 Qt Designer 软件，其中预览窗口时弹出的菜单，可以被 Snipaste 检测到。除此之外基本没有软件可以在主显示上检测。甚至同一个 Chrome 浏览器，移动到第二显示就可以检测到窗口和元素，再次移动到主显示就不行了。

**Comment by liulex** [comment]
@Tingfant 抱歉，我之前没理解好你的意思，以为你是说截屏窗口无法覆盖到第二屏幕。
如果是自动选取的问题，我目前有个内测版应该可以解决。
如感兴趣，可将你的 IM 联系方式（Telegram 或 QQ）发到 <snipaste.app@gmail.com> ，以确认是否能解决你的问题。

**Comment by Tingfant** [comment]
@liulex 呃，我想你应该是@错人了。 @JokerQyou 看一下上面作者说的吧。

**Comment by liulex** [comment]
@Tingfant 是的，@ 错了……
不过 @JokerQyou 也联系过我了，他的问题和你们的不一样，我也无法解决……

**Comment by JokerQyou** [comment]
如果 issue 原作者的问题解决了那么你们可以关掉这个 issue 了 :smiley:

**Comment by anysafepan** [comment]
@liulex 我跟你一样的问题呢，你有修复版的吗？发我一份吧，非常感谢！邮箱是1723674604@qq.com

**Comment by liulex** [comment]
@anysafepan 加 Telegram 群或者等下周的新版吧
