### ISSUE TITLE
希望增加自动贴图功能

### ISSUE THREAD

**Issue by xuxulll** [liulex/Snipaste-Feedback#63]
希望增加在截图后自动贴图功能. 一般来说截图的时候就希望自动贴图上屏了...谢谢!

**Comment by liulex** [comment]
……有的啊，截图的时候 `Ctrl `+ `W` 或者点那个图钉的图标 (v1.6)。

**Comment by yinhux** [comment]
@liulex  @xuxulll 我想他应该说的是截图后不需要安任何按键就直接拖拽截图就贴在桌面的吧

**Comment by moonhuahua** [comment]
截图后按中键贴图如何，这个改软件应该很简单

**Comment by liulex** [comment]
@moonhuahua 当前版本就可以，在托盘图标上按中键。
如果想要在任意地方按中键都贴图，这不是一个软件应该有的行为。

**Comment by moonhuahua** [comment]
@liulex 我的意思是在截图的区域，而且仅当截图时才触发，这样不可能和其它软件冲突的！
而且，其实此时，用空格代替Ctrl+ W 是更喜闻乐见的
不知截图时有没有独立的class，我会点ahk，用ahk是很简单的

**Comment by liulex** [comment]
那就是截图**时**按中间，而不是截图**后**，这个可以考虑加入。

用空格代替 Ctrl+W 也许对你是喜闻乐见的，但实际空格的行为在截图和贴图上应该保持一致，才不会让用户困惑。

**Comment by liulex** [comment]
已经实现，下一版会增加。
