### ISSUE TITLE
建议增加录制gif功能

### ISSUE THREAD

**Issue by ixinshang** [liulex/Snipaste-Feedback#65]
有时需要一个时间段的记录，需要录制gif，咱们的snipaste很不错。 加上录制gif就更好了。
最后，感谢开发。

**Comment by GregAMO** [comment]
> 不会考虑
GIF 录制
请使用 [LICEcap](http://www.cockos.com/licecap/)

来自 [用户手册-新功能请求](https://snipaste.gitbooks.io/snipaste/content/zh/requests/)

既然作者这么说了……那就再念一遍：”贴图是本体。“

**Comment by liulex** [comment]
是的，GIF 录制可使用 [LICEcap](http://www.cockos.com/licecap/).

**Comment by ixinshang** [comment]
好的，感谢开发维护。

**Comment by yxhink** [comment]
原来有这个软件LICEcap ，谢谢推荐！！
