### ISSUE TITLE
Windows64位完整版 Windows Defender 报病毒

### ISSUE THREAD

**Issue by Erimus-Koo** [liulex/Snipaste-Feedback#66]
Qt5Core.dll
Qt5PrintSupport.dll
特洛伊木马
Trojan:Win32/Varpes.M!cl

![image](https://cloud.githubusercontent.com/assets/17139670/17656912/bbca0c9a-62f1-11e6-8bb6-65330df7c82d.png)

**Comment by Erimus-Koo** [comment]
下载地址 http://zh.snipaste.com/ 首页
![image](https://cloud.githubusercontent.com/assets/17139670/17656955/2782f5d2-62f2-11e6-990c-b1ae58d318a3.png)

**Comment by liulex** [comment]
1. 此情况确实有几位用户碰到了。
2. 那两个 dll 文件为 Qt 提供的，并非 Snipaste 生成的，所以不必担心 Snipaste 是否有恶意行为。
3. 请试试下载另外两个版本（XP 和 32位），是否同样报毒呢？我也使用 Windows Defender，但重复下载测试后并没有报毒。
4. 请问当前报毒的 Windows Defender 的病毒库定义的版本是？有用户反应说更新病毒库定义之后，问题解决，你可以试试。
期待你的再次反馈 :-)

**Comment by Erimus-Koo** [comment]
现在用32位的没有问题。
病毒库上午9：52更新，版本 1.225.3929.0

**Comment by Erimus-Koo** [comment]
病毒库版本更新到 1.225.3963.0
不报错了。

**Comment by StevenSun121** [comment]
版本：1.225.3963.0
时间：8-15 3:39
64位报错
32正常

**Comment by liulex** [comment]
太奇怪了，我这边从官网下的 64 位包，3929 和 3963 都没报错…… =.=

**Comment by StevenSun121** [comment]
版本：1.225.3974.0
时间：8-15 4:38
一切正常

**Comment by Erimus-Koo** [comment]
恩 我64位今天又报错一次 
现在 1.225.4044.0 没问题
但还是老老实实先滚回32位了

**Comment by liulex** [comment]
最后做个声明（总结）。

Qt5Core.dll 和 Qt5PrintSupport.dll 是 Qt 官方提供的，和 Snipaste 自己的代码无关，因此不存在感染病毒的可能。如果不放心，可以自己到 [Qt 官网](https://www.qt.io/download/)下载安装 Qt，并提取同名的 dll 替换之。

不管是 64 位还是 32 位，Qt5 开头的 dll，除 Qt5PrintSupport.dll 是 Snipaste 1.5 才提供的之外，其他都是 Snipaste 1.0 版本就已经提供并从未改动过（所以更新包里并没有它们），所以近日才开始的 Windows Defender 报毒只能是误报……

但我自己的机器上也是安装的 Windows Defender，却从来未报毒，所以为什么有些人报有些人不报，我也不清楚其中的原理……

解决办法的话，有部分用户反馈说升级病毒库之后就不报了，也有部分用户是 64 位报 32 位不报，所以要么升级Windows Defender 的病毒库版本，要么使用 32 位的版本，要么自己找可靠的地方下载同名 dll 进行替换……

**Comment by arctg70** [comment]
只好换到32位版了。
