### ISSUE TITLE
Download Speed; Encountering Server Error

### ISSUE THREAD

**Issue by EMLVIRUS** [liulex/Snipaste-Feedback#69]
![sp160816_212454](https://cloud.githubusercontent.com/assets/16912240/17700444/53e98436-63f8-11e6-93d0-6e330f456c11.png)
![sp160816_212959](https://cloud.githubusercontent.com/assets/16912240/17700517/a93c3c1c-63f8-11e6-810a-633388e20c03.png)

While downloading latest full 1.6 pack, download is forced to be terminated with a server error
I could not even finish downloading after many retries: finally forced terminated with max server retry reached.
Here is a result about speed test from speedtest.net
![sp160816_214607](https://cloud.githubusercontent.com/assets/16912240/17701082/f8528304-63fa-11e6-8000-195315b0b953.png)

**Comment by liulex** [comment]
Sorry for the troubles.
You may try the download links on the [Chinese website](http://zh.snipaste.com/download.html). The files are the same, just hosted on different places.

Starting from the next version (v1.7), I will also put the release files on Github.

**Comment by EMLVIRUS** [comment]
The Chinese website you mentioned is exactly where I encountered the problem (Browser addon spoofing so that I go to Chinese one).
Now I successfully got it on English site.

**Comment by liulex** [comment]
Oh, then maybe the download links on the Chinese website have poor support for downloading outside China. But they are good in China. That's why I gave seperated links for Chinese and English websites.
Thanks for your quick feedback.

**Comment by EMLVIRUS** [comment]
Emm. Actually, I'm now in China. Guangzhou......
So.....
That can be strange enough....

**Comment by liulex** [comment]
:joy:
