### ISSUE TITLE
高dpi下与其他软件冲突,几乎无法使用

### ISSUE THREAD

**Issue by quericy** [liulex/Snipaste-Feedback#74]
### 环境
SurfacePro3 ， 2160X1440分辨率，150%DPI
使用其他软件开启适配高DPI选项的话，Snipaste的截图将存在严重问题。

### 示例
例如，开启EnPass的Scale for High-DPI displays选项，重启系统后；
![如图所示](https://i.imgur.com/sktILyH.png)

### 问题
Snipaste截图过程中，全屏文字虚化，如下图：
![如图所示](https://i.imgur.com/wPbkR9d.jpg)

Snipaste截图后，贴图出来将只能展示图片的一部分，对比如下：

**原图：**(使用FsCapture截取相同范围)
![如图所示](https://i.imgur.com/4vj9xvt.png)

**Snipaste截取后贴图：**(尺寸和截图范围不正常)
![如图所示](https://i.imgur.com/ID2NXjP.png)

**Comment by liulex** [comment]
关于高分屏的适配，我最近在测试 Mac 版的时候解决了一部分，那些修改应该对 Windows 也是适用的。
如果方便的话，是否可以留个 IM 联系方式（Telegram or QQ）？我把内测版发给你测试一下？
我邮箱：<snipaste.app@gmail.com>

**Comment by quericy** [comment]
@liulex 已发~
