### ISSUE TITLE
希望可以增加命令行参数

### ISSUE THREAD

**Issue by brucmao** [liulex/Snipaste-Feedback#75]
我想有带参数的启动方式，比如
Snipaste.exe /jietu   ;这样启动就是截图
Snipaste.exe /tietu  ;这样启动就是贴图

**Comment by liulex** [comment]
以后会增加以命令行方式的调用

**Comment by liulex** [comment]
v1.10 将初步支持命令行选项，见 [命令行选项](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%91%BD%E4%BB%A4%E8%A1%8C%E9%80%89%E9%A1%B9)。

如有建议可在此提出。
