### ISSUE TITLE
截图自动消失

### ISSUE THREAD

**Issue by makejiang** [liulex/Snipaste-Feedback#76]
windows 8.1 64-bit
版本 1.6 (2016.08.10)

重现流程:
1) 按F1启动截图
2) 按鼠标左键选择截图起始点
3) 拖动鼠标选择截图区域
4) 松开鼠标左键
5) 所选截图界面消失, 就和没操作一样.

**Comment by makejiang** [comment]
Sorry, 关闭有道词典即可正常.

**Comment by liulex** [comment]
同 #62 
下个版本会修复同取词功能的冲突
