### ISSUE TITLE
双击缩小贴图，再次双击恢复原大小

### ISSUE THREAD

**Issue by yinhux** [liulex/Snipaste-Feedback#77]
作者大大可否增加个双击缩小贴图，再次双击恢复原大小【缩小成一个小正方形，而且可以移动】因为感觉隐藏贴图这个不是很方便，如果缩小贴图的话就可以知道自己想要哪个而去双击它，感觉这个用起来和方便，隐藏的贴图的话是进行全部隐藏，不是很直观，希望作者能考虑下 谢谢

![2016820- -92438](https://cloud.githubusercontent.com/assets/21018274/17827901/24c94016-66b8-11e6-8c6a-175294abc62a.jpg)
就像这样，可以点哪里，就以哪里缩小，并且可以移动，再次双击就会恢复原大小，或者直接在缩小后进行关闭或者销毁

**Comment by yinhux** [comment]
![2016820- -92438](https://cloud.githubusercontent.com/assets/21018274/17827901/24c94016-66b8-11e6-8c6a-175294abc62a.jpg)
就像这样，可以点哪里，就以哪里缩小，并且可以移动，再次双击就会恢复原大小，或者直接在缩小后进行关闭或者销毁

**Comment by liulex** [comment]
你说的事 Setuna 的行为吧。它的双击缩小确实很好玩，但现在贴图上面的操作太多了，很难再想一个合理的鼠标操作给这个操作。但我有空的时候会研究一下怎样比较合理的。

目前来说，如果你只是想要把它缩小放到一边，可以尝试滑动滚轮。当然，没有双击缩小那么方便。

**Comment by GregAMO** [comment]
赞同 + 双击关闭贴图已经误点击好多次了_（捂脸）_，更期待双击缩小这个操作

**Comment by miaowm5** [comment]
希望能够在选项里提供一个切换双击行为的选项，保留双击关闭贴图的功能……
因为我自己用的时候很多贴图都是贴上去->使用->销毁的，用完之后马上就关掉了，根本没有什么缩小了放一边的需求，1.8版关掉贴图变成了得右键+选择，挺麻烦的……

**Comment by liulex** [comment]
@miaowm5 目前还可以通过 Esc或 Ctrl + 单击 来关闭贴图。你提到的问题会在下个版本加个选项。
