### ISSUE TITLE
The v1.16.1 detects wrong Windows elements if the app is made with Java and Python

### ISSUE THREAD

**Issue by raindropsfromsky** [liulex/Snipaste-Feedback#796]
The previous version (V1.16) was working fine on my Windows 10 64-bit PC.

But as soon as I installed the v1.16.1, it has started misbehaving: It detects Windows elements with an offset.

First, here is a screenshot of the LMMS window, from which I tried to capture the elements:
![image](https://user-images.githubusercontent.com/9047168/35076495-c8f8f026-fc1e-11e7-856f-e7e8d4e1e671.png)

I have tried to capture the two elements that are marked with red outline. 
One is a button, and the other is a songs tracks area. They get captured as shown below:

**Example-1: Button**
![image](https://user-images.githubusercontent.com/9047168/35076304-bb820c8a-fc1d-11e7-81ec-6b0b5b4f42df.png)

**Example-2: Tracks** 
![image](https://user-images.githubusercontent.com/9047168/35076259-803e2dfc-fc1d-11e7-8388-91bf21c0c445.png)

Note that even the **size** of the captured area does not match the original element's size.

**Comment by raindropsfromsky** [comment]
**Update:** 

While I was filing this bug, I tried to capture elements from my browser itself.
I am using FireFox 57.0.4 ('Quantum").
It works perfectly.

So I tried it on DoubleCommander and xplorer2 (both double-pane file explorers).
Both work perfectly.

But it fails to work with **Blender 3D** totally: Not a single element is auto-detected!
(Blender 3D is Python-based)

It also does not work with LibreOffice (not a single element is auto-detected!)
LibreOffice is Java-based.

So I suspect that SniPaste is unable to work with some libraries like Java, Python, Qt...

**Comment by liulex** [comment]
Your conclusions are correct. Element detection doesn't work for all applications. It relies on the accessibility interface provided by the target application. For applications that do not implement such an interface, Snipaste can do nothing about it.

However, for the song editor in your screenshot, it is something related to DPI scale. I am not sure if it can be overcome. But I just downloaded LMMS and ran it, and found that its interface not scaled (while the other applications are scaled correctly to my system setting 125% DPI). Does it requre any extra configuration to make its interface scaled?

**Comment by raindropsfromsky** [comment]
I installed the 32-bit version of v1.16.1 at office. 

Then I observed a strange thing: snipaste was unable to detect the elements only in one child window of LMMS. It was able to work in the other windows! Then I moved the window to the left of the monitor, and it started detecting the elements properly! (This particular window was much smaller than my 17" monitor.)

Please let me know how to do additional experiments.

BTW please download the latest version of LMMS (1.2.0 RC5), as it is redesigned in a major way. If you try the old stable version, you may arrive at wrong conclusions.

**Comment by liulex** [comment]
@raindropsfromsky I have reproduced your problem. I think it's the problem of LMMS itself, just like [Chrome](https://github.com/Snipaste/feedback/wiki/Troubleshooting#ui-elements-in-the-web-browser-cannot-be-automatically-detected-when-snipping). With available APIs, I have no way to tell a properly scaled window from a bad one.

**Comment by raindropsfromsky** [comment]
So will it get sorted if we simply move the window to the left side of the
screen?

**Comment by liulex** [comment]
The different behavior on different monitors also depends on the implementation of LMMS. Maybe you should file an issue to them about the Accessibility defect.

**Comment by raindropsfromsky** [comment]
I will. But I don't know what the issue really is.

Can you please help me identify the issue?

As it happens, I have a daily dialogue with them, as I am writing the user
manual for LMMS.

**Comment by liulex** [comment]
Sure. You may ask the development team to test it with [inspect.exe](https://msdn.microsoft.com/en-us/library/windows/desktop/dd318521(v=vs.85).aspx). When the system DPI is larger than 100%, the beta version of LMMS works no problem with `UI Automation`, but bad with `MSAA`(Microsoft Active Accessibility). I guess it's related to some build configuration.

**Comment by raindropsfromsky** [comment]
Thanks @tresf !

It seems Blender has its own GUI toolkit called GHOST. (found from Quora)

**Comment by tresf** [comment]
@raindropsfromsky thanks.  For the purposes of resolving this bug, I think @liulex can safely close this out as the bug exists elsewhere.  If not already, I would suggest summarizing the findings here into a bug report at LMMS and closing this out.

For the record, LMMS on Windows currently uses Qt 5.4.  (Mac and Linux use Qt 5.9)

Qt 5.9 is available directly from qt.io, but placing it into the build system is not trivial, so it's on the back burner for now.
