### ISSUE TITLE
部分功能的操作提示缺失，快捷键功能没有在菜单中体现

### ISSUE THREAD

**Issue by flying19880517** [liulex/Snipaste-Feedback#8]
1. 希望能在截图的时候提示怎么选颜色，我是看文档才知道按C的，然后再按F2粘贴，在设置等地方找了半天都没找到提示。最好可以在坐标、颜色的下面加上一行“按C键取色”这样的提示，并且按C后直接粘贴出来，不用再按F2了，因为复制到剪贴板的那段颜色基本上没什么用，主要还是粘贴后右键中的。
<img alt='选取颜色' src='https://cloud.githubusercontent.com/assets/344444/17290209/ec2e7ffc-580f-11e6-9871-6654be529a91.png' width='200'/>

2. 图片窗口右键没有调整透明度的菜单，缩放功能就有菜单（针对不知道怎么用快捷键调整透明度的用户），旋转也是类似
<img alt='缩放菜单' src='https://cloud.githubusercontent.com/assets/344444/17290339/8b0c9456-5810-11e6-84e7-f8ba66e03403.png' width='200'/>

3. F3穿透应该在系统托盘菜单那里加个项“启用关闭穿透”，否则不知道的用户误按了F3，就不知道怎么处理屏幕上的贴图了

4. 操作时能用WSAD的地方都应该可以用上下左右，用上下左右的地方也要可以用WSAD才行，不同的用户有不同的习惯，这两套应该一致

暂时遇到这几个，其他的纯靠快捷键的功能也应该有类似的菜单或者有所提示。或者要在比较容易找到的地方放个快捷键大全，及帮助文档链接，而不是先点到官网，然后再从官网寻找文档链接。

PS: 贴图部分的Alt取色其实没啥必要吧，~~而且还是按C不行，得双击完成取色，~~按了C也没提示去色成功，直接按F1不就可以了？这个应该砍掉。

**Comment by Dwwwwww** [comment]
> 操作时能用WSAD的地方都应该可以用上下左右，用上下左右的地方也要可以用WSAD才行，不同的用户有不同的习惯，这两套应该一致

容易和快捷键冲突啊，上下左右很少人用吧_(:з」∠)_

**Comment by flying19880517** [comment]
FastStone Capture就是用上下左右微调的，还有啥软件也是这样的，反正至少有两个，我也在Snipaste选择的时候试过上下左右，不行，还以为Snipaste没有这个功能，后来看文档才知道是WSAD。

**Comment by liulex** [comment]
1. 即使不看文档，官网首页就有写基本的操作快捷键，首页这么短，总该浏览浏览一遍吧。
2. 再次，调整透明度首页就有写。菜单里有调整缩放，是为了方便高分屏用户，他们的图片通常需要一半缩放或者 2 倍缩放。
3. 这个可以考虑加入，但看过官网首页就不会发生这样的事。
4. 上下左右和 WASD 不一样，是为了实现更多的功能。使用 WASD 来调整光标移动，是考虑到用户右手拿鼠标，左手自然使用 WASD 更方便一些。上下左右弄成和 WASD 一致是肯定不会的，但可以考虑为左撇子用户交换 WASD 和上下左右的功能。

基本的快捷键大全，在官网首页就是了，还不容易找到吗？
帮助文档确实不应该跳转那么多次，目前是为了让用户尽早看到，临时放在了 gitbook。

你认为不需要的功能，其他用户可能很需要，就这么武断地砍掉？你不需要，不要按 Alt 即可，完全不会影响你正常使用。贴图也没有其他快捷键需要 Alt，不会让你误触吧？

每次都显示那么详细，我觉得很不舒服。
如果你想要使用 Snipaste，请适应它的习惯；适应不了，也可以继续用你喜欢的其他软件。
Snipaste 不可能满足每一个用户的使用习惯，请你谅解。

**Comment by flying19880517** [comment]
bye

**Comment by flying19880517** [comment]
似乎你有个误区，就是所有人都是从官网下载，并且完整看了首页的，还有不是我用着舒不舒服，我既然已经完整看了帮助文档，那么上面所列的就已经知道了，所以我提这些是为了让其他人更好的使用，但是这部分功能必须看文档才能知道，这就是用户体验上做的不好的地方。文档虽然详尽，但是并不能很快从中找到想要看的内容，最好能做到不用看文档也能了解大部分功能，除非是瞄着vim那个方向。既然拿出来想要让更多人使用，那么就不仅仅是设计师和程序员在用，还有很多普通用户在用，有些提示友好一些总是好的。决定权是在你手里的，让你觉得不舒服的，这个理由相当充分，没人愿意让自己不舒服。但是仅你掌握还不够，你还得让用户掌握，在你觉得舒服的地方，不然你为什么要写帮助文档，那里面有什么是你都没掌握的。

> 让我们一起把 Snipaste 变得更好。

呵呵

还有，我是来提建议的，是本着探讨商量的心，而不是吃多了撑的来被责问的，你看看你的评论内容，相当多的反问，语气比较强烈，不知道你是觉得我是非常挑剔的用户不予理会，还是平时说话就这样，反正结论还是能看明白的，看来我昨天吃的有点撑。

**Comment by liulex** [comment]
你好，普通用户可以使用 Snipaste，高级用户也可以。
普通用户，大多只需要 QQ 截图的功能吧，请问 QQ 截图有的功能，Snipaste 与之相对应的功能，是否有哪里做的很隐蔽，而没有让用户发现呢？

既然你已经知道了有取色这个功能，而这个功能是其他软件没有的（就我自己接触过的软件来说），那你就应该知道它的快捷键。为什么？因为我在每一句介绍有这个功能的话之后，都有说“按C”。即使是动图的演示，也能看出来是“按C”所以取色的。我不知道你为什么知道了有这个功能，却不知道“按C”。如果是从其他网站得知的，而那个网站没有介绍功能的使用，为什么要我来背这个锅？

按照你这个逻辑，从其他网站下载的，用户中毒了，是不是也应该我来背锅？因为并不是所有用户都从官网下载啊。

既然你认为你代表着大多数的用户，那我告诉你，我收到的两百多封邮件，没有一个用户说，”这个功能我用不上，你砍掉吧“。也没有一个用户说，“这个功能不符合我的使用习惯，你改成我习惯的那样吧”。

我对大多数用户的态度怎么样，你可以问问给我发送过邮件的人。但你这种这么以自我为中心的，我还真的不待见。

**Comment by StarryVoid** [comment]
首先作者没必要至气

这位反馈者主要反馈功能太多并且对于小白难以理解。
作者您看着他一顿抹杀劳动成果十分生气。

实际没必要啊，首先这个是免费软件，面向专业人士。如果是小白的话，用QQ不是更方便。
软件本身功能是贴图，其次是截图，因为十分满足很多专业人士的需求所以出名了。

您两位真的没必要争吵。。当然如果我说的哪里有问题在此抱歉。
