### ISSUE TITLE
希望添加 GIF录制  和简单的屏幕录像功能

### ISSUE THREAD

**Issue by nonono33333** [liulex/Snipaste-Feedback#80]
希望添加 GIF录制  和简单的屏幕录像功能

**Comment by 2220209876** [comment]
同需要

**Comment by GregAMO** [comment]
#65 相同问题
![image](https://cloud.githubusercontent.com/assets/20766212/18030907/5ce07fec-6cfc-11e6-837c-b85569071461.png)

**Comment by yxhink** [comment]
确实是一个很有竞争力的功能，个人认为，通过快捷键并在小范围内进行短视频或gif录制是一个不错的且有意义的功能，很多操纵需要使用箭头指向、标记步骤等等在制作截图，截屏范围内录制可以解决这个问题，顶上，希望大家来支持下snipaste。
