### ISSUE TITLE
关于快捷键优先级的问题

### ISSUE THREAD

**Issue by S-Kee** [liulex/Snipaste-Feedback#84]
在前几个版本的时候，当切换到其他软件的时候，按F1就是当前软件的帮助，按F3也不会是贴图。当点一下任务栏，再按F1就是Snipaste的截图功能。非常喜欢这种方案，虽然是全局快捷键，但会让路给当前激活的软件。需要截图的时候，点一下任务栏，取消当前软件的激活状态，就可以使用Snippate的截图功能。但是现在的最新版本，快捷键永久的占用了，无论什么时候都是截图。在使用其他很依靠快捷键的软件中，比如说Total_ command之类的软件时，就十分的不方便。希望可以回归之前的快捷键方案。谢谢！

**Comment by liulex** [comment]
Snipaste 的快捷键方案从未改变。

你所提到的前几个版本的行为，是因为当前窗口的程序为管理员权限打开的，而 Snipaste 不是管理员权限打开，所以 Snipaste 的全局快捷键无效，需要点击一下任务栏或者其他非管理员权限打开的窗口，再按快捷键才能激活 Snipaste 的功能。

既然 Snipaste 可被设置的几个快捷键是全局快捷键，就应该任何时候都起作用，而不是只在某些时候起作用。
在管理员权限打开的窗口不起作用，是系统权限所致，并不是 Snipaste 特意的设定。
所以如果要避免快捷键冲突，还请设定为不同的快捷键。
但截图快捷键以后可能会增加一个可定义的黑名单列表，在某些程序（如游戏）激活时不激活截图。

**Comment by S-Kee** [comment]
非常感谢作者大大的回复，解决解决了我的问题。祝Snipaste成为业界第一，越来越棒！

**Comment by hxse** [comment]
期待黑名单功能
