### ISSUE TITLE
隐藏单张贴图的操作会删除贴图

### ISSUE THREAD

**Issue by hiforrest** [liulex/Snipaste-Feedback#88]
ctrl+单击、左键双击和esc和左键双击在说明里是隐藏贴图，但实际会删除贴图。shift+F3隐藏所有贴图功能正常。

版本1.6

**Comment by liulex** [comment]
抱歉，之前的文档和 Snipaste 内的文本没有把**关闭**贴图和**隐藏**贴图区分开。

对贴图进行 `双击` / `Ctrl`+`左键单击` / `Esc` 执行的是**关闭**贴图，可以理解为关闭浏览器标签：在设定的数量内，已关闭的贴图可以被恢复；关闭 Snipaste 时，如果已关闭的贴图没有被显示出来，它们会被自动销毁（即使未达到最大计数）。

**隐藏**所有贴图，一定不会销毁贴图，即使关闭 Snipaste 时它们都是隐藏状态。

希望我有解释明白。

[文档](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C#%E5%85%B3%E9%97%AD%E5%8D%95%E5%BC%A0%E8%B4%B4%E5%9B%BE)已更新。

**Comment by hiforrest** [comment]
明白关闭和隐藏的区别了。
如何恢复已关闭的贴图？

**Comment by hiforrest** [comment]
明白关闭和隐藏的区别了。
如何恢复已关闭的贴图？

**Comment by hiforrest** [comment]
明白关闭和隐藏的区别了。
如何恢复已关闭的贴图？

**Comment by liulex** [comment]
再次按下（若干次）贴图键
