### ISSUE TITLE
（win7）安装、截图正常，保存时直接闪退

### ISSUE THREAD

**Issue by tmuer** [liulex/Snipaste-Feedback#90]
win7安装、截图正常，保存时直接闪退，

**Comment by liulex** [comment]
应该是和 #58 一样，但反馈的信息太少，无法确认问题。
请问，闪退是指 Snipaste 整个程序退出，还是指文件的保存对话框退出？
对贴图的图片进行保存，是否也“闪退”？

**Comment by tmuer** [comment]
我系统是win7,64位，这次下载32位软件成功运行，不知道是什么原因~

**Comment by liulex** [comment]
好吧，那么先关闭此 issue，如 bug 再现请再开一个。
