### ISSUE TITLE
任务栏图标会变化

### ISSUE THREAD

**Issue by Arieser** [liulex/Snipaste-Feedback#91]
任务栏图标会变化，不太清楚触发原因
环境：win10，fps屏
<img width="26" alt="sp160823_232012" src="https://cloud.githubusercontent.com/assets/12909107/17915784/fea46ebc-69df-11e6-908c-ef96f91515d3.png">
<img width="18" alt="sp160824_094627" src="https://cloud.githubusercontent.com/assets/12909107/17915782/fd578efe-69df-11e6-845f-477793572431.png">

**Comment by liulex** [comment]
:joy: 这表示鼠标穿透状态，看[这里](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C#%E4%BD%BF%E6%88%AA%E5%9B%BE%E9%BC%A0%E6%A0%87%E7%A9%BF%E9%80%8F)

**Comment by Arieser** [comment]
鼠标穿透没问题，但是图标没有变化呀

**Comment by liulex** [comment]
上面的图标表示开启了贴图的鼠标穿透，上面的图标表示没有开启鼠标穿透……
