### ISSUE TITLE
希望添加一个全局（默认）透明度的功能

### ISSUE THREAD

**Issue by EosPeng** [liulex/Snipaste-Feedback#96]
使用过程中甚是满意，截图功能基本不用，主要是贴图。
但是每次都会调整每个贴图的透明度为70%。因为也想知道贴图遮挡了哪些内容。

所以希望在设置里面添加个全局（默认）透明度的设置，使得每次贴图出来，都默认是设置值。

**Comment by liulex** [comment]
很高兴你喜欢贴图功能，你要的功能已经实现，见[预告](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%96%B0%E7%89%88%E9%A2%84%E5%91%8A)。
