### ISSUE TITLE
希望添加 ”一键销毁所有贴图“ 以及 ”一键显示所有隐藏但未销毁的贴图“ 的快捷键 + 上报一个BUG

### ISSUE THREAD

**Issue by toryln** [liulex/Snipaste-Feedback#97]
工作中有时需要贴出好几张图进行对比（比如绘制UI，我会同时贴出好几个相关的图作为参考），
我将”可被再次恢复的隐藏贴图数“设置为10，这样就可以按需要随时Esc隐藏贴图，
或者依次按F3恢复较早之前的贴图。

 当阶段性工作完成后（比如完成了当前UI的制作，开始下一个UI制作），希望将所有贴图都销毁，
而当前销毁的方式是每次按贴图键F3打开隐藏的所有贴图
（热键Shift+F3支持的隐藏/显示所有贴图需要已经使用F3将图贴出来后才起作用），
然后依次Shift+Esc来销毁单张贴图，有些不方便。当忘记做这个工作时，或者漏掉销毁某些图后，
下一次贴图就会把之前的贴图也贴出来。

所以，如果有一键销毁所有贴图的快捷键，就可以安心开始下一阶段的工作；
如果有一键显示所有通过Esc隐藏但未销毁的图（有些图不需要我会直接按Shift+Esc销毁），
就可以不需要依次按F3将较早的图依次贴出来。

另外再报一个BUG，当所有贴图都显示出来时，再次按F3，OK，所有贴图会闪烁。
但有时强迫症发作，喜欢按好几下F3，结果有时Snipaste会将当前剪贴版中的图再次贴出来，
导致屏幕上显示好几个同样的最后在剪贴板中的图。

 再次感谢大师出品相当顺手好用的工具！同时希望我的需求能被看到~~~~

**Comment by liulex** [comment]
首先非常感谢你详细的反馈。

根据你的使用场景，建议你利用贴图分组这一功能。当你需要销毁所有贴图的时候，通过托盘菜单将该分组关闭即可，相当于销毁该分组的所有贴图，应该比你提出的需求来的更方便一些。

另外，关闭单张贴图（即按 Esc），如果你在退出 Snipaste 的时候没有把已关闭的贴图显示出来，它们也会被自动销毁的。抱歉之前没有把这一点说明清楚，请看更新后的[文档](https://github.com/liulex/Snipaste-Feedback/wiki/%E5%9F%BA%E7%A1%80%E6%93%8D%E4%BD%9C#%E5%85%B3%E9%97%AD%E5%8D%95%E5%BC%A0%E8%B4%B4%E5%9B%BE)。

不知道了解了以上几点之后，你是否还需要“一键显示所有隐藏但未销毁的贴图”？其实关闭贴图只是给你提供一种后悔药，防止你刚把贴图关闭之后，又后悔了，想找回来，所以我建议设置为 1 即可。
**如果你本来就不想这张贴图消失，而只是想暂时隐藏它，就不应该关闭它**，而是使用“隐藏所有贴图”，或者把它移动到另一个贴图分组。

关于贴图重复出现的 bug，确实有很多情况下会出现，目前我追加解决了一部分情况，见[新版预告](https://github.com/liulex/Snipaste-Feedback/wiki/%E6%96%B0%E7%89%88%E9%A2%84%E5%91%8A).

新版还需等一段时间才发布，如果希望提前体验，可加入我们的[内测群](https://telegram.me/joinchat/BGyWwEEW8CEjnhGb5sUDEw)（需科学上网）。

**Comment by liulex** [comment]
楼主报告内测版已经解决问题，此 issue 关闭。

**Comment by toryln** [comment]
使用分组的功能确实很棒，多多利用分组功能会提高不好效率！BUG解决了真是太好了
