### ISSUE TITLE
保存时的命名规则可以自定义吗？

### ISSUE THREAD

**Issue by sishentibu** [liulex/Snipaste-Feedback#98]
即手动保存和自动保存图片的时候的命名规则，可以自定义吗？
例如以某一特殊字符开头，或纯数字命名等。

**Comment by liulex** [comment]
以后会增加的，感谢建议。

**Comment by sishentibu** [comment]
@liulex 辛苦了

**Comment by gymgle** [comment]
非常期待这项功能。感觉 FastStone Capture 的设置不错，能自定义保存文件名的格式：

![sp20160928_152849](https://cloud.githubusercontent.com/assets/2842518/18904347/3a3efb88-8590-11e6-946b-e419f3643dfd.png)

**Comment by hujy23** [comment]
对！如楼上，可以模仿一下faststone capture的这个功能

**Comment by liulex** [comment]
刚发布的 1.9.0 已经实现。
至于其中的计数，我感觉没有必要，这个数字意义不大，也不好跟踪。

**Comment by liulex** [comment]
如有增加其他变量的需求，可以继续评论补充。

**Comment by sishentibu** [comment]
感谢特地提醒
![sp20161027_203805](https://cloud.githubusercontent.com/assets/13832182/19767422/5244fece-9c85-11e6-9d27-234820f23fc9.jpg)
这地方的命名规则只适用于自动保存。不知可否把手动保存的自动命名也适用这个规则？

另这个自动备份功能，没发现是什么用的。。
![sp20161027_204020](https://cloud.githubusercontent.com/assets/13832182/19767490/af6735fe-9c85-11e6-9106-26cf9e960ff9.jpg)

**Comment by liulex** [comment]
@sishentibu 
其实我本意是让手动保存的也应用这个规则的，没想到忘了改了，下个更新会加上去。

如果关掉自动备份，那么你的贴图在每次关闭 Snipaste 之后就没了。

**Comment by sishentibu** [comment]
@liulex 了解
谢谢

**Comment by qiantangit** [comment]
不知老大试没试过Greenshot？希望能借鉴一下其中部分功能。
--------------------
${NUM} incrementing number
   虽然被否过一次，还是再提一下，不知道有没有希望。日期时间足以用来排序，不过加个序号对人更直观一些，有利于后期选择。

${title} Window title    
   是JD购物页面还是编辑器窗口？同样是方便后期处理。 

 还有就是利用"\\"自动生成文件夹。
“You can also have Greenshot create directories dynamically, simply use the backslash symbol (\\) to separate folders and filename.
Example: the pattern ${YYYY}-${MM}-${DD}\\${hh}-${mm}-${ss}
will generate a folder for the current day in your default storage location, e.g. 2008-06-29”
--------------------

关于输出的有以上3项。还有一个关于编辑（贴图）中添加顺序数字标注的需求，虽然文本中也可以变通添加，不过Greenshot中这个功能可以随意删除中间数字而更新其它数字标注，这种情况用文本的话就太繁琐了，具体一试便知：）

**Comment by nuosong** [comment]
能不能像FS Capture那样 自动编号 比如20180404_001，20180404_002，20180404_003......同时每天自动从001开始编号 这样命名简洁不少 一看到hhmmss的命名 有点密集恐惧 谢谢

**Comment by hujy23** [comment]
@nuosong 会提issue竟然不会看设置🌚

**Comment by nuosong** [comment]
@hujy23 日期没问题 后面的编号001、002......如何实现

**Comment by hujy23** [comment]
@nuosong 会自动加上的~试试看

**Comment by nuosong** [comment]
@hujy23 确实可以 非常感谢 但是只能 无后缀、0、1、2、3、4、5、6、7、8、9、10、11......貌似不能实现固定位数

**Comment by hujy23** [comment]
@nuosong en的确有点强迫症不友好，不过本强迫症不觉得这个2018-04-04_092805密恐，很精确很满足 🤣
