### ISSUE TITLE
快速保存后自动复制图片路径到剪贴板

### ISSUE THREAD

**Issue by xfanplus** [liulex/Snipaste-Feedback#99]
快速保存截图能否增加一个选项，选中以后，快速保存截图完成之后自动复制图片文件路径到剪贴板，这个功能对于写Markdown时贴图非常有用，谢谢！

**Comment by liulex** [comment]
同 #38

**Comment by karas1999** [comment]
这个需求跟#38并不是一样的. #38 是需要复制图片到剪贴板, 而这个需求是要复制图片的完整路径. 完全不同的. 目前快速保存截图后复制图片路径确实是很麻烦的事情. 这对于使用Markdown或者Org-mode的人来说特别不方便. 每次要打开存储图片的目录, 再手动地复制地址栏的地址, 加上图片文件的名称. 希望有更方便的办法.

**Comment by KazamaSion** [comment]
Markdown 如果是用于网络文章的发布的话，比起本地路径，图床的支持度才是你的优先事项。本地路径除非你只是想要在本地看（还要编辑器支持），是没有任何用的。

**Comment by karas1999** [comment]
Markdown不是只用于网络文章的. Markdown可以用于本地文档编辑. 看看所有主流编辑器都有Markdown插件就可知道了. 编辑完之后可以用Pandoc导出为PDF, docx, html, PPT等各种格式, 这些格式每种都可以有内嵌图片, 所以Markdown的内连本地图片功能是很重要的. 放在网上的图片对于日常文档编辑来说反而不常用.
